/**
 * @mockup admin-mockups/design_files/sp4-game-detail.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Private Game Detail Page
 *
 * Issue #3664: Private game PDF support — detail page with PDF upload and RAG chat.
 *
 * Server Component: resolves route params and delegates rendering to the
 * PrivateGameDetailClient which fetches game data on the client.
 *
 * Route: /private-games/[id]
 */

import { PrivateGameDetailClient } from '@/components/private-game/PrivateGameDetailClient';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Props {
  params: Promise<{ id: string }>;
}

// ---------------------------------------------------------------------------
// Page Component
// ---------------------------------------------------------------------------

export default async function PrivateGameDetailPage({ params }: Props) {
  const { id } = await params;
  return <PrivateGameDetailClient privateGameId={id} />;
}
