/**
 * @mockup admin-mockups/design_files/sp4-play-records-new.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Create Play Record Page
 *
 * Multi-step wizard for creating new play records.
 * Issue #3892: Play Records Frontend UI
 *
 * #2348: Reads ?gameNightId= from URL and prefills the form via
 * useGameNightPrefill (date/location/game/roster from completed GameNight).
 * Next.js 16 requires useSearchParams under <Suspense> — inner content
 * component reads params; default export wraps it.
 */

'use client';

import { Suspense, useState } from 'react';

import { ArrowLeft } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { toast } from 'sonner';

import { FormPageContainer } from '@/components/layout/PageContainer';
import { SessionCreateForm, type PlayerEntry } from '@/components/play-records/SessionCreateForm';
import { Button } from '@/components/ui/primitives/button';
import { useTranslation } from '@/hooks/useTranslation';
import { playRecordsApi } from '@/lib/api/play-records.api';
import type { SessionCreateForm as SessionFormData } from '@/lib/api/schemas/play-records.schemas';
import { useGameNightPrefill } from '@/lib/domain-hooks/useGameNightPrefill';
import { useCreatePlayRecord } from '@/lib/domain-hooks/usePlayRecords';

function NewPlayRecordContent() {
  const router = useRouter();
  const { t } = useTranslation();
  const createRecord = useCreatePlayRecord();
  const searchParams = useSearchParams();
  const gameNightId = searchParams.get('gameNightId');
  const { prefill, isLoading } = useGameNightPrefill(gameNightId);
  // #2847 (#BB): the roster is persisted after create via extra calls, which are
  // not part of the create mutation — track our own saving flag so the wizard
  // stays disabled for the whole sequence.
  const [isSaving, setIsSaving] = useState(false);

  // Issue #2847 (#BB): the create wizard collected players, per-player scores and
  // a location, but the submit only sent the base CreatePlayRecordRequest — the
  // record persisted empty ("Planned", players:[], location:null). CreatePlayRecord
  // does not accept players/scores/location, so persist them with the dedicated
  // follow-up endpoints (addPlayer / recordScore / update) after the record exists.
  const handleSubmit = async (data: SessionFormData, players: PlayerEntry[]) => {
    setIsSaving(true);
    try {
      const recordId = await createRecord.mutateAsync({
        gameId: data.gameId,
        gameName: data.gameName,
        sessionDate: data.sessionDate.toISOString(),
        visibility: data.visibility,
        groupId: data.groupId,
        scoringDimensions: data.enableScoring ? data.scoringDimensions : undefined,
        dimensionUnits: data.enableScoring ? data.dimensionUnits : undefined,
      });

      // Persist the roster. addPlayer returns 204 (no id), so re-fetch afterwards
      // to resolve the created player ids before recording scores.
      for (const player of players) {
        await playRecordsApi.addPlayer(recordId, { displayName: player.name });
      }

      // Per-player score → first scoring dimension (or "points"). Only when
      // scoring is enabled and a numeric value was entered.
      const scoredPlayers = players.filter(
        p => p.score.trim() !== '' && !Number.isNaN(Number(p.score))
      );
      if (data.enableScoring && scoredPlayers.length > 0) {
        const dimension = data.scoringDimensions?.[0] ?? 'points';
        const unit = data.dimensionUnits?.[dimension];
        const record = await playRecordsApi.getRecord(recordId);
        for (const player of scoredPlayers) {
          const persisted = record.players.find(rp => rp.displayName === player.name);
          if (!persisted) continue;
          await playRecordsApi.recordScore(recordId, {
            playerId: persisted.id,
            dimension,
            value: Number(player.score),
            unit,
          });
        }
      }

      // Location is not part of CreatePlayRecordRequest — persist it via update.
      const location = data.location?.trim();
      if (location) {
        await playRecordsApi.updateRecord(recordId, { location });
      }

      toast.success(t('playRecords.new.success.toast'), {
        description: t('playRecords.new.success.toastDescription'),
      });

      router.push(`/play-records/${recordId}`);
    } catch (error) {
      toast.error(t('playRecords.new.error.saveFailed'), {
        description:
          error instanceof Error ? error.message : t('playRecords.new.error.saveFailedDescription'),
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    router.push('/play-records');
  };

  // While the GameNight prefill is loading, show a skeleton.
  // Only shown when a gameNightId is present (backward-compat: no-op when absent).
  if (gameNightId && isLoading) {
    return (
      <FormPageContainer className="p-6 space-y-4">
        <div className="h-8 bg-muted animate-pulse rounded w-48" />
        <div className="h-12 bg-muted animate-pulse rounded" />
        <div className="h-32 bg-muted animate-pulse rounded" />
      </FormPageContainer>
    );
  }

  return (
    <FormPageContainer className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={handleCancel}
          aria-label={t('playRecords.new.a11y.backToList')}
        >
          <ArrowLeft className="w-5 h-5" />
        </Button>
        <div>
          <h1 className="text-3xl font-bold">{t('playRecords.new.pageTitle')}</h1>
          <p className="text-muted-foreground mt-1">{t('playRecords.new.pageSubtitle')}</p>
        </div>
      </div>

      {/* Form — prefill?.initialValues/initialPlayers are undefined when no gameNightId */}
      <SessionCreateForm
        initialValues={prefill?.initialValues}
        initialPlayers={prefill?.initialPlayers}
        onSubmit={handleSubmit}
        onCancel={handleCancel}
        isSubmitting={createRecord.isPending || isSaving}
      />
    </FormPageContainer>
  );
}

export default function NewPlayRecordPage() {
  return (
    <Suspense
      fallback={
        <FormPageContainer className="p-6">
          <div className="h-8 bg-muted animate-pulse rounded w-48" />
        </FormPageContainer>
      }
    >
      <NewPlayRecordContent />
    </Suspense>
  );
}
