/**
 * @mockup admin-mockups/design_files/librogame-runthrough-session-end.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Live Session Main Page — /sessions/live/[sessionId]
 *
 * Game Night Improvvisata — Task 15
 * Phase 5: Game Night — Task 4 (PlayModeMobile on mobile)
 *
 * Desktop: Renders the SessionCardParent component as the primary session overview.
 * Mobile (<lg): Renders PlayModeMobile with 4-tab layout.
 */

'use client';

import { use } from 'react';

import { SessionCardParent } from '@/components/session/live/SessionCardParent';

import { PlayModeMobile } from './play-mode-mobile';

interface LiveSessionPageProps {
  params: Promise<{ sessionId: string }>;
}

export default function LiveSessionPage({ params }: LiveSessionPageProps) {
  const { sessionId } = use(params);

  return (
    <>
      <div className="lg:hidden">
        <PlayModeMobile sessionId={sessionId} />
      </div>
      <div className="hidden lg:block">
        <SessionCardParent sessionId={sessionId} />
      </div>
    </>
  );
}
