namespace Api.BoundedContexts.BusinessSimulations.Domain.Enums;

/// <summary>
/// Source of a financial ledger entry.
/// Issue #3720: Financial Ledger Data Model
/// </summary>
public enum LedgerEntrySource
{
    /// <summary>Automatically generated by the system (e.g., token consumption, subscription billing)</summary>
    Auto = 0,

    /// <summary>Manually created by an administrator</summary>
    Manual = 1
}
