/** @vitest-environment jsdom */
import { render, screen, fireEvent, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type {
  PublishedMechanicCardDto,
  PublishedMechanicCitationDto,
} from '@/lib/api/schemas/mechanic-card.schemas';

// ─── Stub the shared PDF viewer so pdfjs is never loaded in jsdom. ──────────────
vi.mock('@/components/pdf/PdfQuoteViewer', () => ({
  PdfQuoteViewer: (props: { documentId: string; page: number; quote: string }) => (
    <div
      data-testid="pdf-quote-viewer"
      data-doc={props.documentId}
      data-page={props.page}
      data-quote={props.quote}
    />
  ),
}));

// ─── Mock sonner toast. ─────────────────────────────────────────────────────────
const toastSuccess = vi.hoisted(() => vi.fn());
vi.mock('sonner', () => ({
  toast: { success: toastSuccess, error: vi.fn() },
}));

// ─── Controllable breakpoint. ───────────────────────────────────────────────────
const mediaMatches = vi.hoisted(() => ({ value: true })); // default: desktop
vi.mock('@/hooks/useMediaQuery', () => ({
  useMediaQuery: () => mediaMatches.value,
}));

import { MechanicCitationPanel } from '../MechanicCitationPanel';

const CITATION: PublishedMechanicCitationDto = {
  pdfId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  pdfPage: 12,
  quote: 'only on your own turn',
};

const CARD: Pick<
  PublishedMechanicCardDto,
  'gameName' | 'publisher' | 'publicationYear' | 'documentName' | 'sourceAnalysisId'
> = {
  gameName: 'Catan',
  publisher: 'Kosmos',
  publicationYear: 1995,
  documentName: 'Catan Rulebook',
  sourceAnalysisId: '99999999-9999-4999-8999-999999999999',
};

const EXPECTED_APA =
  'Kosmos. (1995). Catan: Catan Rulebook (p. 12).\n' +
  '[Excerpt]: "only on your own turn"\n' +
  'Generated by MeepleAI mechanic extractor (analysis_id=99999999-9999-4999-8999-999999999999).';

/** Set `window.matchMedia` for the drawer's internal breakpoint hook. */
function setBreakpoint(desktop: boolean): void {
  Object.defineProperty(window, 'matchMedia', {
    configurable: true,
    writable: true,
    value: vi.fn().mockReturnValue({
      matches: desktop,
      media: '(min-width: 768px)',
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      addListener: vi.fn(),
      removeListener: vi.fn(),
      onchange: null,
      dispatchEvent: vi.fn(),
    }),
  });
}

/**
 * jsdom lacks the PointerEvent capture / scroll / transform APIs vaul uses.
 * Install the same shims the Drawer primitive test uses so the mobile (vaul)
 * branch mounts without crashing. getComputedStyle is patched exactly once.
 */
const realGetComputedStyle = window.getComputedStyle.bind(window);
function installJsdomDrawerShims(): void {
  if (typeof Element.prototype.hasPointerCapture !== 'function') {
    Element.prototype.hasPointerCapture = () => false;
  }
  if (typeof Element.prototype.setPointerCapture !== 'function') {
    Element.prototype.setPointerCapture = () => {};
  }
  if (typeof Element.prototype.releasePointerCapture !== 'function') {
    Element.prototype.releasePointerCapture = () => {};
  }
  if (typeof Element.prototype.scrollIntoView !== 'function') {
    Element.prototype.scrollIntoView = () => {};
  }
  vi.spyOn(window, 'getComputedStyle').mockImplementation(((
    el: Element,
    pseudo?: string | null
  ) => {
    const cs = realGetComputedStyle(el, pseudo ?? undefined);
    if (!cs.transform) {
      try {
        Object.defineProperty(cs, 'transform', { configurable: true, value: 'none' });
      } catch {
        // ignore — already defined
      }
    }
    return cs;
  }) as typeof window.getComputedStyle);
}

describe('MechanicCitationPanel', () => {
  beforeEach(() => {
    mediaMatches.value = true; // desktop Sheet (useMediaQuery mock)
    toastSuccess.mockClear();
    setBreakpoint(true);
    installJsdomDrawerShims();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('renders nothing when there is no citation', () => {
    const { container } = render(
      <MechanicCitationPanel citation={null} card={CARD} isOpen onClose={vi.fn()} />
    );
    expect(container.querySelector('[data-testid="mechanic-citation-panel-body"]')).toBeNull();
  });

  it('renders the header (document + page), the PDF viewer, and the footer actions', () => {
    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);

    const body = screen.getByTestId('mechanic-citation-panel-body');
    expect(within(body).getByText('Catan Rulebook')).toBeInTheDocument();
    expect(within(body).getByText('AI-generated, human-reviewed')).toBeInTheDocument();
    expect(within(body).getByText(/pagina 12/)).toBeInTheDocument();

    const viewer = screen.getByTestId('pdf-quote-viewer');
    expect(viewer).toHaveAttribute('data-page', '12');
    expect(viewer).toHaveAttribute('data-doc', CITATION.pdfId);

    expect(screen.getByTestId('mechanic-citation-copy')).toBeEnabled();
    // "Segnala errore" is an inert placeholder (M3.1 not built).
    expect(screen.getByTestId('mechanic-citation-report')).toBeDisabled();
  });

  it('copies the APA citation to the clipboard and toasts on success', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText } });

    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    fireEvent.click(screen.getByTestId('mechanic-citation-copy'));

    await waitFor(() => expect(writeText).toHaveBeenCalledWith(EXPECTED_APA));
    expect(toastSuccess).toHaveBeenCalledWith('Citazione copiata');
    // No fallback modal on the happy path.
    expect(screen.queryByTestId('mechanic-citation-copy-fallback')).not.toBeInTheDocument();
  });

  it('opens the manual fallback modal (pre-selected textarea) when clipboard is absent', async () => {
    // Remove clipboard support.
    Object.assign(navigator, { clipboard: undefined });

    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    fireEvent.click(screen.getByTestId('mechanic-citation-copy'));

    const modal = await screen.findByTestId('mechanic-citation-copy-fallback');
    expect(modal).toBeInTheDocument();
    const textarea = screen.getByLabelText('Testo della citazione') as HTMLTextAreaElement;
    expect(textarea).toHaveValue(EXPECTED_APA);
    expect(textarea).toHaveAttribute('readonly');
    expect(screen.getByText(/Premi Ctrl\+C per copiare/)).toBeInTheDocument();
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  it('falls back to the manual modal when clipboard.writeText rejects', async () => {
    const writeText = vi.fn().mockRejectedValue(new Error('denied'));
    Object.assign(navigator, { clipboard: { writeText } });

    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    fireEvent.click(screen.getByTestId('mechanic-citation-copy'));

    await screen.findByTestId('mechanic-citation-copy-fallback');
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  it('invokes onClose when the Sheet requests to close (ESC / overlay)', () => {
    const onClose = vi.fn();
    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={onClose} />);
    // Radix closes on Escape → onOpenChange(false) → our onClose.
    fireEvent.keyDown(document.body, { key: 'Escape', code: 'Escape' });
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('renders the bottom Drawer surface on mobile (<768px)', async () => {
    mediaMatches.value = false; // useMediaQuery → mobile
    setBreakpoint(false); // vaul's own useDrawerBreakpoint → mobile
    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    // vaul mounts its content asynchronously via a portal.
    expect(await screen.findByTestId('mechanic-citation-panel-drawer')).toBeInTheDocument();
    expect(screen.queryByTestId('mechanic-citation-panel-sheet')).not.toBeInTheDocument();
  });

  it('renders the right Sheet surface on desktop (≥768px)', () => {
    mediaMatches.value = true; // desktop
    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    expect(screen.getByTestId('mechanic-citation-panel-sheet')).toBeInTheDocument();
    expect(screen.queryByTestId('mechanic-citation-panel-drawer')).not.toBeInTheDocument();
  });

  it('announces the opened citation via an aria-live region', () => {
    render(<MechanicCitationPanel citation={CITATION} card={CARD} isOpen onClose={vi.fn()} />);
    const live = screen.getByTestId('mechanic-citation-live');
    expect(live).toHaveAttribute('aria-live', 'polite');
    expect(live).toHaveTextContent(/Catan Rulebook.*pagina 12/);
  });
});
