// OPS-02: AI Insights metrics (Issue #4124)
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Api.Observability;

internal static partial class MeepleAiMetrics
{
    #region AI Insights Metrics (Issue #4124)

    /// <summary>
    /// Counter for total insight generation requests.
    /// Issue #4124: Tracks dashboard insights endpoint usage.
    /// </summary>
    public static readonly Counter<long> InsightGenerationTotal = Meter.CreateCounter<long>(
        name: "meepleai.insights.generation.total",
        unit: "requests",
        description: "Total number of insight generation requests");

    /// <summary>
    /// Histogram for insight generation duration in milliseconds.
    /// Issue #4124: Tracks P95 latency for SLO compliance (&lt;1s target).
    /// </summary>
    public static readonly Histogram<double> InsightGenerationDuration = Meter.CreateHistogram<double>(
        name: "meepleai.insights.generation.duration",
        unit: "ms",
        description: "Insight generation duration in milliseconds");

    /// <summary>
    /// Counter for insight generation errors by analyzer type.
    /// Issue #4124: Tracks failures per analyzer for root cause analysis.
    /// </summary>
    public static readonly Counter<long> InsightGenerationErrors = Meter.CreateCounter<long>(
        name: "meepleai.insights.generation.errors",
        unit: "errors",
        description: "Insight generation errors by analyzer type");

    /// <summary>
    /// Histogram for per-analyzer execution duration in milliseconds.
    /// Issue #4124: Identifies slow analyzers for performance optimization.
    /// </summary>
    public static readonly Histogram<double> InsightAnalyzerDuration = Meter.CreateHistogram<double>(
        name: "meepleai.insights.analyzer.duration",
        unit: "ms",
        description: "Per-analyzer execution duration in milliseconds");

    /// <summary>
    /// Counter for insights generated by type.
    /// Issue #4124: Tracks distribution of insight types.
    /// </summary>
    public static readonly Counter<long> InsightsGeneratedByType = Meter.CreateCounter<long>(
        name: "meepleai.insights.generated.total",
        unit: "insights",
        description: "Total insights generated by type");

    /// <summary>
    /// Counter for insight cache hits.
    /// Issue #4124: Tracks cache effectiveness for insights endpoint.
    /// </summary>
    public static readonly Counter<long> InsightCacheHits = Meter.CreateCounter<long>(
        name: "meepleai.insights.cache.hits",
        unit: "hits",
        description: "Insight cache hits");

    /// <summary>
    /// Counter for insight cache misses.
    /// Issue #4124: Tracks cache miss rate for insights endpoint.
    /// </summary>
    public static readonly Counter<long> InsightCacheMisses = Meter.CreateCounter<long>(
        name: "meepleai.insights.cache.misses",
        unit: "misses",
        description: "Insight cache misses");

    /// <summary>
    /// Counter for insight feedback submissions.
    /// Issue #4124: Tracks user feedback for accuracy measurement.
    /// </summary>
    public static readonly Counter<long> InsightFeedbackTotal = Meter.CreateCounter<long>(
        name: "meepleai.insights.feedback.total",
        unit: "submissions",
        description: "Total insight feedback submissions");

    /// <summary>
    /// Counter for insight performance degradation events.
    /// Issue #4124: Fires when generation exceeds 1000ms threshold.
    /// Used by Prometheus alerting to trigger performance alerts.
    /// </summary>
    public static readonly Counter<long> InsightPerformanceDegraded = Meter.CreateCounter<long>(
        name: "meepleai.insights.performance.degraded",
        unit: "events",
        description: "Insight generation exceeded performance threshold (1000ms)");

    /// <summary>
    /// Performance threshold for insight generation in milliseconds.
    /// Issue #4124: DoD target is response time &lt;1s (P95).
    /// </summary>
    public const double InsightPerformanceThresholdMs = 1000.0;

    /// <summary>
    /// Records insight generation with duration and analyzer breakdown.
    /// Issue #4124: Helper method for comprehensive insight metrics.
    /// </summary>
    /// <param name="totalDurationMs">Total generation duration in milliseconds</param>
    /// <param name="insightCount">Number of insights generated</param>
    /// <param name="cacheHit">Whether result came from cache</param>
    /// <param name="analyzerDurations">Optional per-analyzer durations (analyzer_name → duration_ms)</param>
    public static void RecordInsightGeneration(
        double totalDurationMs,
        int insightCount,
        bool cacheHit,
        IDictionary<string, double>? analyzerDurations = null)
    {
        var tags = new TagList
        {
            { "cache_hit", cacheHit }
        };

        InsightGenerationTotal.Add(1, tags);
        InsightGenerationDuration.Record(totalDurationMs, tags);

        if (cacheHit)
        {
            InsightCacheHits.Add(1);
        }
        else
        {
            InsightCacheMisses.Add(1);
        }

        if (analyzerDurations != null)
        {
            foreach (var (analyzer, durationMs) in analyzerDurations)
            {
                var analyzerTags = new TagList { { "analyzer", analyzer.ToLowerInvariant() } };
                InsightAnalyzerDuration.Record(durationMs, analyzerTags);
            }
        }
    }

    /// <summary>
    /// Records insight feedback submission with relevance tracking.
    /// Issue #4124: Tracks feedback for accuracy calculation (target &gt;75%).
    /// </summary>
    /// <param name="insightType">Type of insight that received feedback</param>
    /// <param name="isRelevant">Whether user marked the insight as relevant</param>
    public static void RecordInsightFeedback(string insightType, bool isRelevant)
    {
        var tags = new TagList
        {
            { "insight_type", insightType.ToLowerInvariant() },
            { "relevant", isRelevant }
        };

        InsightFeedbackTotal.Add(1, tags);
    }

    #endregion
}
