// OPS-02: RAG (Retrieval-Augmented Generation) metrics
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Api.Observability;

internal static partial class MeepleAiMetrics
{
    /// <summary>
    /// Counter for total RAG requests
    /// </summary>
    public static readonly Counter<long> RagRequestsTotal = Meter.CreateCounter<long>(
        name: "meepleai.rag.requests.total",
        unit: "requests",
        description: "Total number of RAG (Retrieval-Augmented Generation) requests");

    /// <summary>
    /// Histogram for RAG request duration in milliseconds
    /// </summary>
    public static readonly Histogram<double> RagRequestDuration = Meter.CreateHistogram<double>(
        name: "meepleai.rag.request.duration",
        unit: "ms",
        description: "RAG request duration in milliseconds");

    /// <summary>
    /// Histogram for confidence score distribution (0.0 to 1.0)
    /// </summary>
    public static readonly Histogram<double> ConfidenceScore = Meter.CreateHistogram<double>(
        name: "meepleai.rag.confidence.score",
        unit: "score",
        description: "Confidence score distribution for RAG responses");

    /// <summary>
    /// Histogram for RAG Time-To-First-Token (TTFT) in milliseconds.
    /// Issue #5541: SLO metric — measures from request start to first LLM token.
    /// Includes embedding + vector search + prompt building + LLM first token.
    /// </summary>
    public static readonly Histogram<double> RagFirstTokenLatency = Meter.CreateHistogram<double>(
        name: "meepleai.rag.first_token_latency",
        unit: "ms",
        description: "RAG Time-To-First-Token latency in milliseconds (request start → first LLM response)");

    /// <summary>
    /// Counter for RAG errors by type
    /// </summary>
    public static readonly Counter<long> RagErrorsTotal = Meter.CreateCounter<long>(
        name: "meepleai.rag.errors.total",
        unit: "errors",
        description: "Total number of RAG errors by type");

    // === RAG Retrieval Quality Metrics ===

    public static readonly Histogram<int> RagRetrievalChunkCount = Meter.CreateHistogram<int>(
        name: "meepleai.rag.retrieval.chunk_count",
        unit: "chunks",
        description: "Number of chunks returned per RAG retrieval");

    public static readonly Histogram<double> RagRetrievalAvgScore = Meter.CreateHistogram<double>(
        name: "meepleai.rag.retrieval.avg_score",
        unit: "score",
        description: "Average similarity score of retrieved chunks");

    public static readonly Counter<long> RagEnhancementActivations = Meter.CreateCounter<long>(
        name: "meepleai.rag.enhancement.activations",
        unit: "activations",
        description: "RAG enhancement activations by type");

    public static readonly Counter<long> RagRetrievalFallbacks = Meter.CreateCounter<long>(
        name: "meepleai.rag.retrieval.fallbacks",
        unit: "fallbacks",
        description: "RAG retrieval fallback events by type");

    public static readonly Counter<long> RagCragVerdicts = Meter.CreateCounter<long>(
        name: "meepleai.rag.crag.verdicts",
        unit: "evaluations",
        description: "CRAG retrieval evaluation verdicts");

    public static readonly Counter<long> RagAdaptiveRoutingDecisions = Meter.CreateCounter<long>(
        name: "meepleai.rag.adaptive.decisions",
        unit: "decisions",
        description: "Adaptive RAG routing decisions by complexity level");

    public static readonly Histogram<int> RagFusionQueryCount = Meter.CreateHistogram<int>(
        name: "meepleai.rag.fusion.query_count",
        unit: "queries",
        description: "Number of query variants generated by RAG-Fusion");

    /// <summary>
    /// Counter for total vector searches
    /// </summary>
    public static readonly Counter<long> VectorSearchTotal = Meter.CreateCounter<long>(
        name: "meepleai.vector.search.total",
        unit: "searches",
        description: "Total number of vector searches");

    /// <summary>
    /// Histogram for vector search duration in milliseconds
    /// </summary>
    public static readonly Histogram<double> VectorSearchDuration = Meter.CreateHistogram<double>(
        name: "meepleai.vector.search.duration",
        unit: "ms",
        description: "Vector search duration in milliseconds");

    /// <summary>
    /// Histogram for number of results returned from vector search
    /// </summary>
    public static readonly Histogram<int> VectorResultsCount = Meter.CreateHistogram<int>(
        name: "meepleai.vector.results.count",
        unit: "results",
        description: "Number of results returned from vector search");

    /// <summary>
    /// Histogram for vector indexing duration in milliseconds
    /// </summary>
    public static readonly Histogram<double> VectorIndexingDuration = Meter.CreateHistogram<double>(
        name: "meepleai.vector.indexing.duration",
        unit: "ms",
        description: "Vector indexing duration in milliseconds");

    /// <summary>
    /// Histogram for vector search component scores in hybrid search
    /// </summary>
    public static readonly Histogram<double> HybridSearchVectorScore = Meter.CreateHistogram<double>(
        name: "meepleai.search.vector.score",
        unit: "score",
        description: "Vector search component scores");

    /// <summary>
    /// Histogram for keyword search component scores in hybrid search
    /// </summary>
    public static readonly Histogram<double> HybridSearchKeywordScore = Meter.CreateHistogram<double>(
        name: "meepleai.search.keyword.score",
        unit: "score",
        description: "Keyword search component scores");

    /// <summary>
    /// Histogram for RRF fusion scores in hybrid search
    /// </summary>
    public static readonly Histogram<double> HybridSearchRrfScore = Meter.CreateHistogram<double>(
        name: "meepleai.search.rrf.score",
        unit: "score",
        description: "RRF fusion scores");

    /// <summary>
    /// Counter for hybrid search requests
    /// </summary>
    public static readonly Counter<long> HybridSearchTotal = Meter.CreateCounter<long>(
        name: "meepleai.search.hybrid.total",
        unit: "searches",
        description: "Total hybrid search requests");

    /// <summary>
    /// Records a RAG request with duration and metadata
    /// </summary>
    public static void RecordRagRequest(double durationMs, string? gameId = null, bool success = true)
    {
        var tags = new TagList();
        if (!string.IsNullOrEmpty(gameId))
        {
            tags.Add("game.id", gameId);
        }
        tags.Add("success", success);

        RagRequestsTotal.Add(1, tags);
        RagRequestDuration.Record(durationMs, tags);
    }

    /// <summary>
    /// Records a vector search operation
    /// </summary>
    public static void RecordVectorSearch(double durationMs, int resultsCount, string? collectionName = null)
    {
        var tags = new TagList();
        if (!string.IsNullOrEmpty(collectionName))
        {
            tags.Add("collection", collectionName);
        }

        VectorSearchTotal.Add(1, tags);
        VectorSearchDuration.Record(durationMs, tags);
        VectorResultsCount.Record(resultsCount, tags);
    }

    /// <summary>
    /// Records hybrid search with component scores
    /// </summary>
    public static void RecordHybridSearch(
        double? vectorScore = null,
        double? keywordScore = null,
        double? rrfScore = null)
    {
        HybridSearchTotal.Add(1);

        if (vectorScore.HasValue)
        {
            HybridSearchVectorScore.Record(vectorScore.Value);
        }

        if (keywordScore.HasValue)
        {
            HybridSearchKeywordScore.Record(keywordScore.Value);
        }

        if (rrfScore.HasValue)
        {
            HybridSearchRrfScore.Record(rrfScore.Value);
        }
    }
}
