/**
 * @mockup admin-mockups/design_files/onboarding.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
'use client';

import type { JSX } from 'react';
import { useEffect } from 'react';

import { Loader2 } from 'lucide-react';
import { useRouter } from 'next/navigation';

import { useAuth } from '@/components/auth/AuthProvider';

import { OnboardingGenericWizard } from './OnboardingGenericWizard';

/**
 * /onboarding entry point — generic (not invited) users.
 *
 * Asse D follow-up P3 (umbrella #1895 sub-issue #1899 follow-up). The legacy
 * `OnboardingTourClient` 5-step page-flow has been replaced by the 3-step
 * `OnboardingGenericWizard` built on the asse-B `WizardModal` primitive.
 *
 * Invited users (token-based) continue to use the dedicated 5-step
 * `OnboardingWizard` mounted by `/accept-invite` — that flow is untouched.
 */
export default function OnboardingPage(): JSX.Element | null {
  const router = useRouter();
  const { user, loading, refreshUser } = useAuth();

  useEffect(() => {
    void refreshUser();
  }, [refreshUser]);

  useEffect(() => {
    if (!loading && user?.onboardingCompleted) {
      router.replace('/library');
    }
  }, [loading, user, router]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-amber-500" aria-label="Caricamento" />
      </div>
    );
  }

  if (!user || user.onboardingCompleted) {
    return null;
  }

  const userName = user.displayName?.trim() || null;
  return <OnboardingGenericWizard userName={userName} />;
}
