/**
 * @mockup admin-mockups/design_files/sp4-kb-hub.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
import { redirect } from 'next/navigation';

/**
 * Knowledge Base index — no standalone listing page exists.
 * Knowledge bases are per-game, accessible from the library.
 */
export default function KnowledgeBasePage() {
  redirect('/library');
}
