/**
 * @mockup admin-mockups/design_files/librogame-runthrough-setup-wizard.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
'use client';

/**
 * New Session Page
 *
 * Issue #5041 — Sessions Redesign Phase 1
 * Issue #123 — Game Night Quick Start Wizard entry point
 * Phase 5: Game Night — Task 3 (SessionWizardMobile on mobile)
 * Issue #2089 — Task 3.9: replaced `lg:hidden` / `hidden lg:block` dual render with
 *   `useMediaQuery` conditional render. Previously BOTH wizards lived in the DOM:
 *   confusing for a11y/screen-readers, E2E selectors, and bumped first-paint cost.
 *
 * Shows "Serata di Gioco" quick start option + existing 5-step wizard.
 * On mobile (<lg), renders the simplified SessionWizardMobile instead.
 */

import { useCallback, useState, Suspense } from 'react';

import { PartyPopper } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';

import { GameNightWizard } from '@/components/game-night/GameNightWizard';
import { SessionCreationWizard } from '@/components/session/SessionCreationWizard';
import { Button } from '@/components/ui/primitives/button';
import { useMediaQuery } from '@/hooks/useMediaQuery';

import { SessionWizardMobile } from './session-wizard-mobile';

const DESKTOP_BREAKPOINT_QUERY = '(min-width: 1024px)';

function MobileWizardSection() {
  const searchParams = useSearchParams();
  const prefilledGameId = searchParams.get('gameId') ?? undefined;
  const prefilledGameName = searchParams.get('gameName') ?? undefined;
  return (
    <SessionWizardMobile prefilledGameId={prefilledGameId} prefilledGameName={prefilledGameName} />
  );
}

function DesktopWizardSection() {
  const [showWizard, setShowWizard] = useState(false);
  const router = useRouter();

  const handleWizardComplete = useCallback(
    (sessionId: string) => {
      router.push(`/sessions/${sessionId}/play`);
    },
    [router]
  );

  return (
    <div className="container mx-auto px-4 py-6 space-y-6">
      {/* Game Night Quick Start */}
      {!showWizard ? (
        <div
          className="rounded-xl border-2 border-amber-500/30 bg-amber-500/5 p-6"
          data-testid="game-night-entry"
        >
          <h2 className="font-quicksand font-bold text-xl mb-2">Serata di Gioco</h2>
          <p className="text-sm text-muted-foreground mb-4">
            Trova un gioco, carica il regolamento e inizia subito — l&apos;agente AI ti assiste.
          </p>
          <Button
            onClick={() => setShowWizard(true)}
            className="bg-amber-600 hover:bg-amber-700 text-white"
            data-testid="start-game-night-button"
          >
            <PartyPopper className="h-4 w-4 mr-2" aria-hidden="true" />
            Inizia Serata di Gioco
          </Button>
        </div>
      ) : (
        <div className="rounded-xl border border-border p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-quicksand font-bold text-xl">Serata di Gioco</h2>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowWizard(false)}
              data-testid="close-wizard-button"
            >
              Chiudi
            </Button>
          </div>
          <GameNightWizard onComplete={handleWizardComplete} />
        </div>
      )}

      {/* Existing Session Creation Wizard */}
      {!showWizard && <SessionCreationWizard />}
    </div>
  );
}

export default function NewSessionPage() {
  // Issue #2089: viewport-aware conditional render eliminates DOM duplication.
  // useMediaQuery returns false during SSR (no window). To avoid hydration mismatch
  // we render NEITHER section server-side; both sections are client-only modules anyway.
  const isDesktop = useMediaQuery(DESKTOP_BREAKPOINT_QUERY);

  return (
    <Suspense fallback={null}>
      {isDesktop ? (
        <DesktopWizardSection />
      ) : (
        <div className="container mx-auto px-4 py-6">
          <MobileWizardSection />
        </div>
      )}
    </Suspense>
  );
}
