#!/usr/bin/env tsx
/**
 * WS-F.3 — Mockup ownership status dashboard generator.
 *
 * Walks `admin-mockups/design_files/*.html`, parses each header per AC-F.5,
 * and renders a markdown dashboard at
 * `docs/for-developers/audits/mockup-ownership-status.md`.
 *
 * Runs from `mockup-ownership-summary.yml` weekly cron (and workflow_dispatch).
 * The output is the canonical "at a glance" view of mockup coverage; the
 * conformity gate, drift detection, and waiver flows pull their data from
 * the underlying header files, not from this artifact.
 *
 * Stale-canonical promotion: a mockup declared `canonical` whose
 * `@last-verified` is more than 30 days old is rendered as "🟡 canonical
 * (stale)" — the header itself isn't rewritten (that would require a human
 * decision to revalidate or accept drift). The dashboard surfaces the
 * staleness; AC-F.5 verified status is the formal equivalent.
 *
 * Refs: #1072 (WS-F), #1066 (umbrella), AC-F.5 dashboard.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  parseMockupHeader,
  STATUS_VALUES,
  type MockupHeader,
  type Status,
} from './parse-mockup-header';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_MOCKUPS_DIR = resolve(HERE, '../../../admin-mockups/design_files');
const DEFAULT_OUTPUT_PATH = resolve(
  HERE,
  '../../../docs/for-developers/audits/mockup-ownership-status.md'
);

const STALE_THRESHOLD_DAYS = 30;

/** Status emoji + human label as rendered in the dashboard. */
const STATUS_BADGE: Record<Status | 'unmapped', { emoji: string; label: string }> = {
  canonical: { emoji: '🟢', label: 'canonical' },
  verified: { emoji: '🟡', label: 'verified' },
  drifted: { emoji: '🟠', label: 'drifted' },
  'pending-implementation': { emoji: '🔵', label: 'pending-implementation' },
  archived: { emoji: '⚪', label: 'archived' },
  unmapped: { emoji: '❌', label: 'unmapped (no header)' },
};

export interface ScanEntry {
  file: string;
  basename: string;
  header: MockupHeader | null;
  parseError: string | null;
  ageDays: number | null;
  effectiveStatus: Status | 'unmapped';
  isStale: boolean;
}

export function scanMockups(dir: string, now: Date = new Date()): ScanEntry[] {
  const files = readdirSync(dir)
    .filter(f => f.endsWith('.html'))
    .map(f => join(dir, f))
    .sort();

  return files.map(file => scanOne(file, readFileSync(file, 'utf8'), now));
}

export function scanOne(file: string, html: string, now: Date): ScanEntry {
  const base = basename(file);
  const result = parseMockupHeader(html);

  if (!result.ok) {
    return {
      file,
      basename: base,
      header: null,
      parseError: result.error,
      ageDays: null,
      effectiveStatus: 'unmapped',
      isStale: false,
    };
  }

  const verified = new Date(result.header.lastVerified + 'T00:00:00Z');
  const ageDays = Math.floor((now.getTime() - verified.getTime()) / (24 * 3600 * 1000));
  const isStale = result.header.status === 'canonical' && ageDays > STALE_THRESHOLD_DAYS;

  return {
    file,
    basename: base,
    header: result.header,
    parseError: null,
    ageDays,
    // We don't promote canonical → verified in the rendered status itself;
    // see isStale flag rendered as " (stale)" suffix.
    effectiveStatus: result.header.status,
    isStale,
  };
}

export function generateStatusMarkdown(scan: ScanEntry[], now: Date = new Date()): string {
  const ts = now.toISOString().replace(/\.\d+Z$/, 'Z');
  const counts = countByStatus(scan);

  const summaryLines = [
    `# Mockup Ownership Status`,
    ``,
    `> **WS-F.3** dashboard — auto-generated by \`mockup-ownership-summary.yml\` weekly cron.`,
    `> **Last generated**: ${ts}`,
    `> **Edits to this file** will be overwritten on the next run. Source of truth: \`@route\` / \`@status\` / \`@last-verified\` headers in \`admin-mockups/design_files/*.html\`.`,
    ``,
    `## Summary`,
    ``,
    `| Status | Count |`,
    `|--------|-------|`,
    ...STATUS_VALUES.map(
      s => `| ${STATUS_BADGE[s].emoji} ${STATUS_BADGE[s].label} | ${counts[s]} |`
    ),
    `| ${STATUS_BADGE.unmapped.emoji} ${STATUS_BADGE.unmapped.label} | ${counts.unmapped} |`,
    `| **Total** | **${scan.length}** |`,
    ``,
    `Stale-canonical (canonical & verified >${STALE_THRESHOLD_DAYS}d ago): **${scan.filter(e => e.isStale).length}**`,
    ``,
    `## Detail`,
    ``,
    `| Mockup | Route | Status | Verified-by | Verified | Age |`,
    `|--------|-------|--------|-------------|----------|-----|`,
  ];

  const sorted = [...scan].sort(
    (a, b) =>
      statusOrder(a.effectiveStatus) - statusOrder(b.effectiveStatus) ||
      a.basename.localeCompare(b.basename)
  );

  for (const entry of sorted) {
    const badge = STATUS_BADGE[entry.effectiveStatus];
    const route = entry.header ? '`' + entry.header.routes.join('` `') + '`' : '_(unmapped)_';
    const statusCell = entry.isStale
      ? `${badge.emoji} ${badge.label} _(stale)_`
      : `${badge.emoji} ${badge.label}`;
    const verifiedBy = entry.header ? `\`${entry.header.verifiedBy}\`` : '—';
    const verified = entry.header ? entry.header.lastVerified : '—';
    const age = entry.ageDays === null ? '—' : `${entry.ageDays}d`;
    summaryLines.push(
      `| \`${entry.basename}\` | ${route} | ${statusCell} | ${verifiedBy} | ${verified} | ${age} |`
    );
  }

  if (scan.some(e => e.parseError)) {
    summaryLines.push(``, `## Parse errors (non-allowlisted)`, ``);
    for (const entry of scan.filter(e => e.parseError && /^[^N]/.test(e.parseError))) {
      summaryLines.push(`- \`${entry.basename}\`: ${entry.parseError}`);
    }
  }

  summaryLines.push(
    ``,
    `## Legend`,
    ``,
    ...Object.entries(STATUS_BADGE).map(
      ([key, b]) => `- ${b.emoji} **${b.label}** — ${legendDescription(key as Status | 'unmapped')}`
    ),
    ``,
    `## Refs`,
    ``,
    `- Spec: \`docs/for-developers/specs/2026-05-12-mockup-conformity-roadmap.md\` §3 WS-F, AC-F.5`,
    `- Umbrella: [#1066](https://github.com/meepleAi-app/meepleai-monorepo/issues/1066)`,
    `- WS-F issue: [#1072](https://github.com/meepleAi-app/meepleai-monorepo/issues/1072)`,
    ``
  );

  return summaryLines.join('\n');
}

function statusOrder(s: Status | 'unmapped'): number {
  // canonical first (most active), unmapped last (least informative).
  return [
    'canonical',
    'verified',
    'drifted',
    'pending-implementation',
    'archived',
    'unmapped',
  ].indexOf(s);
}

function legendDescription(s: Status | 'unmapped'): string {
  switch (s) {
    case 'canonical':
      return `verified within ${STALE_THRESHOLD_DAYS}d, conformity gate green (or expected to be)`;
    case 'verified':
      return `verified once, but verification is older than ${STALE_THRESHOLD_DAYS}d (stale)`;
    case 'drifted':
      return 'conformity gate currently failing on this route';
    case 'pending-implementation':
      return 'mockup canonical but live route not yet implemented';
    case 'archived':
      return 'intentionally retired; no live verification expected';
    case 'unmapped':
      return 'no `@route` header (legacy or excluded from WS-F.1 allowlist)';
  }
}

export function countByStatus(scan: ScanEntry[]): Record<Status | 'unmapped', number> {
  const counts: Record<Status | 'unmapped', number> = {
    canonical: 0,
    verified: 0,
    drifted: 0,
    'pending-implementation': 0,
    archived: 0,
    unmapped: 0,
  };
  for (const entry of scan) counts[entry.effectiveStatus] += 1;
  return counts;
}

const invokedAsCli =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (invokedAsCli) {
  const dir =
    process.argv.find(a => a.startsWith('--mockups='))?.slice('--mockups='.length) ??
    DEFAULT_MOCKUPS_DIR;
  const out =
    process.argv.find(a => a.startsWith('--out='))?.slice('--out='.length) ?? DEFAULT_OUTPUT_PATH;
  const now = new Date();

  const scan = scanMockups(dir, now);
  const md = generateStatusMarkdown(scan, now);

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, md, 'utf8');

  const counts = countByStatus(scan);
  console.log(`✓ Wrote ${out}`);
  console.log(
    `  ${scan.length} mockups: ${counts.canonical} canonical, ${counts.verified} verified, ` +
      `${counts.drifted} drifted, ${counts['pending-implementation']} pending, ` +
      `${counts.archived} archived, ${counts.unmapped} unmapped`
  );
}
