/**
 * @mockup admin-mockups/design_files/sp7-game-night-summary.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Game Night Summary Page (Issue #1255 cluster game-nights PR 2).
 *
 * Thin wrapper: resolves the dynamic `id` param and delegates rendering
 * to `NightSummaryClientView` which integrates `NightSummaryView` (Screen M)
 * from `components/features/game-nights/summary/`.
 *
 * Source mockup: admin-mockups/design_files/sp7-game-night-summary.{html,jsx}
 * (mergiato con PR #1250 chiudendo issue #487).
 */

'use client';

import { use } from 'react';

import { NightSummaryClientView } from './_components/NightSummaryClientView';

export default function GameNightSummaryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  return <NightSummaryClientView nightId={id} />;
}
