"""Build GitHub issue title + body from a route's audit findings."""
from __future__ import annotations

from scripts.v2_audit.finding import Finding
from scripts.v2_audit.confidence_scorer import eligible_for_issue


def build_issue_title(route: str, findings: list[Finding]) -> str:
    eligible = [f for f in findings if eligible_for_issue(f)]
    return f"[audit] Route {route}: {len(eligible)} findings"


def build_issue_body(findings: list[Finding], mockups: list[str]) -> str:
    eligible = [f for f in findings if eligible_for_issue(f)]
    critical = [f for f in eligible if f.severity == "critical"]
    important = [f for f in eligible if f.severity == "important"]

    lines = ["## Findings", ""]

    if critical:
        lines.append(f"### Critical ({len(critical)})")
        for f in critical:
            _append_finding(lines, f)
        lines.append("")

    if important:
        lines.append(f"### Important ({len(important)})")
        for f in important:
            _append_finding(lines, f)
        lines.append("")

    lines.append("## References")
    for m in mockups:
        lines.append(f"- Mockup: `admin-mockups/design_files/{m}`")
    lines.append("- Matrix: `docs/for-developers/frontend/v2-migration-matrix.md`")
    lines.append("- Nav map: `docs/superpowers/specs/nav-map.md`")
    lines.append("- Report: `docs/superpowers/specs/audit-report.md`")
    lines.append("")
    lines.append("🤖 Generated by `scripts/v2_audit/create_issues.py`")

    return "\n".join(lines)


def _append_finding(lines: list[str], f: Finding):
    lines.append(f"- [ ] `{f.component}` ({f.dimension}): {f.description}")
    for k, v in f.evidence.items():
        lines.append(f"  - `{k}`: `{v}`")
