namespace Api.BoundedContexts.SharedGameCatalog.Domain.ValueObjects;

/// <summary>
/// Enum representing the source of a GameStateTemplate generation.
/// </summary>
public enum GenerationSource
{
    /// <summary>
    /// Template was generated by AI from rulebook analysis.
    /// </summary>
    AI = 0,

    /// <summary>
    /// Template was manually created or edited by a user.
    /// </summary>
    Manual = 1
}
