using System.Text;

namespace Api.BoundedContexts.Administration.Infrastructure.Services.Formatters;

/// <summary>
/// PDF report formatter (Markdown-based)
/// ISSUE-916: Formats reports as PDF using markdown conversion
/// NOTE: Currently generates markdown format - can be enhanced with QuestPDF later
/// </summary>
public sealed class PdfReportFormatter : IReportFormatter
{
    public byte[] Format(ReportContent content)
    {
        var sb = new StringBuilder();

        // Title and metadata
        sb.AppendLine($"# {content.Title}");
        sb.AppendLine();
        sb.AppendLine(content.Description);
        sb.AppendLine();
        sb.AppendLine($"**Generated**: {content.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        // Metadata section
        if (content.Metadata.Count > 0)
        {
            sb.AppendLine("## Metadata");
            sb.AppendLine();
            foreach (var (key, value) in content.Metadata)
            {
                sb.AppendLine($"- **{key}**: {value}");
            }
            sb.AppendLine();
        }

        // Sections
        foreach (var section in content.Sections)
        {
            sb.AppendLine($"## {section.Title}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(section.Description))
            {
                sb.AppendLine(section.Description);
                sb.AppendLine();
            }

            if (section.Data.Count > 0)
            {
                // Markdown table
                var columns = section.Data[0].Values.Keys.ToList();

                // Header
                sb.AppendLine($"| {string.Join(" | ", columns)} |");
                sb.AppendLine($"| {string.Join(" | ", columns.Select(_ => "---"))} |");

                // Data rows
                foreach (var row in section.Data)
                {
                    var values = columns.Select(col =>
                    {
                        row.Values.TryGetValue(col, out var value);
                        return value?.ToString() ?? string.Empty;
                    });
                    sb.AppendLine($"| {string.Join(" | ", values)} |");
                }

                sb.AppendLine();
            }
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine($"*Report generated by MeepleAI Administration Console*");

        // TODO: Convert markdown to actual PDF using a library like QuestPDF
        // For now, return markdown as bytes
        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    public string GetFileExtension() => "pdf";

    public string GetContentType() => "application/pdf";
}
