namespace Api.BoundedContexts.KnowledgeBase.Domain.ValueObjects;

/// <summary>
/// Value object representing a candidate chess move with evaluation.
/// Issue #3770: Generated by Move Generator for strategic analysis.
/// </summary>
public sealed record CandidateMove
{
    public required ChessPiece Piece { get; init; }
    public required ChessPosition From { get; init; }
    public required ChessPosition To { get; init; }
    public ChessPiece? CapturedPiece { get; init; }
    public required MoveScore Score { get; init; }
    public required MovePriority Priority { get; init; }
    public bool IsCheck { get; init; }
    public bool IsPromotion { get; init; }
    public string? PromotionPiece { get; init; }  // "Queen", "Rook", etc.

    /// <summary>
    /// Indicates if move is a capture.
    /// </summary>
    public bool IsCapture => CapturedPiece != null;

    /// <summary>
    /// Creates a candidate move with validation.
    /// </summary>
    public static CandidateMove Create(
        ChessPiece piece,
        ChessPosition from,
        ChessPosition to,
        ChessPiece? capturedPiece,
        MoveScore score,
        MovePriority priority,
        bool isCheck = false,
        bool isPromotion = false,
        string? promotionPiece = null)
    {
        ArgumentNullException.ThrowIfNull(piece);
        ArgumentNullException.ThrowIfNull(from);
        ArgumentNullException.ThrowIfNull(to);
        ArgumentNullException.ThrowIfNull(score);

        // Validate from/to are different
        if (string.Equals(from.Notation, to.Notation, StringComparison.Ordinal))
            throw new ArgumentException("From and To positions must be different", nameof(to));

        // Validate promotion consistency
        if (isPromotion && string.IsNullOrWhiteSpace(promotionPiece))
            throw new ArgumentException("PromotionPiece required when IsPromotion is true", nameof(promotionPiece));

        if (!isPromotion && !string.IsNullOrWhiteSpace(promotionPiece))
            throw new ArgumentException("PromotionPiece must be null when IsPromotion is false", nameof(promotionPiece));

        return new CandidateMove
        {
            Piece = piece,
            From = from,
            To = to,
            CapturedPiece = capturedPiece,
            Score = score,
            Priority = priority,
            IsCheck = isCheck,
            IsPromotion = isPromotion,
            PromotionPiece = promotionPiece
        };
    }

    /// <summary>
    /// Converts to algebraic notation (e.g., "e4", "Nf3", "Qxd5+").
    /// </summary>
    public string ToAlgebraicNotation()
    {
        var notation = string.Empty;

        // Piece prefix (skip for pawns unless capture)
        if (!string.Equals(Piece.Type, "Pawn", StringComparison.Ordinal))
        {
            notation += Piece.Type[0];  // N, B, R, Q, K
        }
        else if (IsCapture)
        {
            notation += From.Notation[0];  // e.g., "exd5" (pawn on e-file takes)
        }

        // Capture indicator
        if (IsCapture)
            notation += 'x';

        // Destination
        notation += To.Notation;

        // Promotion
        if (IsPromotion && !string.IsNullOrWhiteSpace(PromotionPiece))
            notation += $"={PromotionPiece[0]}";  // e.g., "e8=Q"

        // Check indicator
        if (IsCheck)
            notation += '+';

        return notation;
    }

    /// <summary>
    /// Gets move description for display.
    /// </summary>
    public string GetDescription() =>
        $"{Piece.Type} {From.Notation}→{To.Notation}" +
        (IsCapture ? $" (captures {CapturedPiece!.Type})" : string.Empty) +
        (IsCheck ? " (check)" : string.Empty);
}
