using Api.BoundedContexts.KnowledgeBase.Domain.ValueObjects;
using Api.SharedKernel.Domain.Entities;

namespace Api.BoundedContexts.KnowledgeBase.Domain.Entities;

/// <summary>
/// Represents a text embedding generated by an embedding model.
/// Not an aggregate root - managed by VectorDocument.
/// </summary>
internal sealed class Embedding : Entity<Guid>
{
    public Guid VectorDocumentId { get; private set; }
    public string TextContent { get; private set; }
    public Vector Vector { get; private set; }
    public string Model { get; private set; }
    public int ChunkIndex { get; private set; }
    public int PageNumber { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public string Language { get; private set; } = "en";
    public Guid? SourceChunkId { get; private set; }
    public bool IsTranslation { get; private set; }

    /// <summary>
    /// Issue #1391: bitwise <c>GameBookRole</c> set copied from the parent
    /// <c>TextChunk.RoleTags</c> so semantic-mode pgvector queries can apply the
    /// role-match boost without joining. Stored as <c>int</c> on the wire to keep
    /// the COPY pipeline neutral. Defaults to 0 (no roles) when the source chunk
    /// is missing or the ingestion path predates the role classifier.
    /// </summary>
    public int RoleTags { get; private set; }

    /// <summary>
    /// Private constructor for EF Core.
    /// </summary>
#pragma warning disable CS8618
    private Embedding() : base()
#pragma warning restore CS8618
    {
    }

    /// <summary>
    /// Creates a new embedding.
    /// </summary>
    public Embedding(
        Guid id,
        Guid vectorDocumentId,
        string textContent,
        Vector vector,
        string model,
        int chunkIndex,
        int pageNumber,
        string language = "en",
        Guid? sourceChunkId = null,
        bool isTranslation = false,
        int roleTags = 0) : base(id)
    {
        if (string.IsNullOrWhiteSpace(textContent))
            throw new ArgumentException("Text content cannot be empty", nameof(textContent));

        if (string.IsNullOrWhiteSpace(model))
            throw new ArgumentException("Model cannot be empty", nameof(model));

        if (chunkIndex < 0)
            throw new ArgumentException("Chunk index must be non-negative", nameof(chunkIndex));

        if (pageNumber < 1)
            throw new ArgumentException("Page number must be positive", nameof(pageNumber));

        VectorDocumentId = vectorDocumentId;
        TextContent = textContent;
        Vector = vector ?? throw new ArgumentNullException(nameof(vector));
        Model = model;
        ChunkIndex = chunkIndex;
        PageNumber = pageNumber;
        CreatedAt = DateTime.UtcNow;
        Language = language ?? "en";
        SourceChunkId = sourceChunkId;
        IsTranslation = isTranslation;
        RoleTags = roleTags;
    }

    /// <summary>
    /// Calculates similarity to another embedding.
    /// </summary>
    public double CalculateSimilarity(Embedding other)
    {
        return Vector.CosineSimilarity(other.Vector);
    }
}
