using Api.SharedKernel;
using Api.SharedKernel.Domain.Entities;

namespace Api.BoundedContexts.SharedGameCatalog.Domain.Entities;

/// <summary>
/// Represents a quick question that can be asked about a game in the chat interface.
/// Questions can be AI-generated from rulebook analysis or manually created by administrators.
/// </summary>
public sealed class QuickQuestion : Entity<Guid>
{
    private Guid _sharedGameId;
    private string _text = string.Empty;
    private string _emoji = string.Empty;
    private QuestionCategory _category;
    private int _displayOrder;
    private readonly bool _isGenerated;
    private readonly DateTime _createdAt;
    private bool _isActive;

    // Public properties (Id inherited from Entity<Guid>)
    public Guid SharedGameId => _sharedGameId;
    public string Text => _text;
    public string Emoji => _emoji;
    public QuestionCategory Category => _category;
    public int DisplayOrder => _displayOrder;
    public bool IsGenerated => _isGenerated;
    public DateTime CreatedAt => _createdAt;
    public bool IsActive => _isActive;

    // Private constructor for EF Core
    private QuickQuestion() { }

    // Internal constructor for aggregate reconstitution (no events)
    internal QuickQuestion(
        Guid id,
        Guid sharedGameId,
        string text,
        string emoji,
        QuestionCategory category,
        int displayOrder,
        bool isGenerated,
        DateTime createdAt,
        bool isActive) : base(id)
    {
        _sharedGameId = sharedGameId;
        _text = text;
        _emoji = emoji;
        _category = category;
        _displayOrder = displayOrder;
        _isGenerated = isGenerated;
        _createdAt = createdAt;
        _isActive = isActive;
    }

    /// <summary>
    /// Creates a new quick question generated by AI from rulebook analysis.
    /// </summary>
    /// <param name="sharedGameId">The ID of the game this question belongs to.</param>
    /// <param name="text">The question text (max 200 characters).</param>
    /// <param name="category">The category of the question.</param>
    /// <param name="displayOrder">The display order (0-based).</param>
    /// <returns>A new AI-generated quick question.</returns>
    /// <exception cref="ArgumentException">Thrown when validation fails.</exception>
    public static QuickQuestion CreateFromAI(
        Guid sharedGameId,
        string text,
        QuestionCategory category,
        int displayOrder)
    {
        ValidateSharedGameId(sharedGameId);
        ValidateText(text);
        ValidateDisplayOrder(displayOrder);

        var emoji = GetEmojiForCategory(category);

        return new QuickQuestion(
            Guid.NewGuid(),
            sharedGameId,
            text.Trim(),
            emoji,
            category,
            displayOrder,
            isGenerated: true,
            DateTime.UtcNow,
            isActive: true);
    }

    /// <summary>
    /// Creates a new quick question manually created by an administrator.
    /// </summary>
    /// <param name="sharedGameId">The ID of the game this question belongs to.</param>
    /// <param name="text">The question text (max 200 characters).</param>
    /// <param name="emoji">The emoji to display (1-2 characters).</param>
    /// <param name="category">The category of the question.</param>
    /// <param name="displayOrder">The display order (0-based).</param>
    /// <returns>A new manually created quick question.</returns>
    /// <exception cref="ArgumentException">Thrown when validation fails.</exception>
    public static QuickQuestion CreateManual(
        Guid sharedGameId,
        string text,
        string emoji,
        QuestionCategory category,
        int displayOrder)
    {
        ValidateSharedGameId(sharedGameId);
        ValidateText(text);
        ValidateEmoji(emoji);
        ValidateDisplayOrder(displayOrder);

        return new QuickQuestion(
            Guid.NewGuid(),
            sharedGameId,
            text.Trim(),
            emoji.Trim(),
            category,
            displayOrder,
            isGenerated: false,
            DateTime.UtcNow,
            isActive: true);
    }

    /// <summary>
    /// Updates the question text.
    /// </summary>
    public void UpdateText(string text)
    {
        ValidateText(text);
        _text = text.Trim();
    }

    /// <summary>
    /// Updates the emoji.
    /// </summary>
    public void UpdateEmoji(string emoji)
    {
        ValidateEmoji(emoji);
        _emoji = emoji.Trim();
    }

    /// <summary>
    /// Updates the category and automatically assigns the appropriate emoji.
    /// </summary>
    public void UpdateCategory(QuestionCategory category)
    {
        _category = category;
        _emoji = GetEmojiForCategory(category);
    }

    /// <summary>
    /// Updates the display order.
    /// </summary>
    public void UpdateDisplayOrder(int displayOrder)
    {
        ValidateDisplayOrder(displayOrder);
        _displayOrder = displayOrder;
    }

    /// <summary>
    /// Activates the question.
    /// </summary>
    public void Activate() => _isActive = true;

    /// <summary>
    /// Deactivates the question.
    /// </summary>
    public void Deactivate() => _isActive = false;

    // Validation methods
    private static void ValidateSharedGameId(Guid sharedGameId)
    {
        if (sharedGameId == Guid.Empty)
            throw new ArgumentException("SharedGameId cannot be empty", nameof(sharedGameId));
    }

    private static void ValidateText(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            throw new ArgumentException("Question text cannot be empty", nameof(text));

        if (text.Length > 200)
            throw new ArgumentException("Question text cannot exceed 200 characters", nameof(text));
    }

    private static void ValidateEmoji(string emoji)
    {
        if (string.IsNullOrWhiteSpace(emoji))
            throw new ArgumentException("Emoji cannot be empty", nameof(emoji));

        if (emoji.Length > 2)
            throw new ArgumentException("Emoji cannot exceed 2 characters", nameof(emoji));
    }

    private static void ValidateDisplayOrder(int displayOrder)
    {
        if (displayOrder < 0)
            throw new ArgumentException("Display order cannot be negative", nameof(displayOrder));
    }

    /// <summary>
    /// Gets the appropriate emoji for a question category.
    /// </summary>
    private static string GetEmojiForCategory(QuestionCategory category) => category switch
    {
        QuestionCategory.Gameplay => "🎮",
        QuestionCategory.Rules => "📖",
        QuestionCategory.Winning => "🏆",
        QuestionCategory.Setup => "⚙️",
        QuestionCategory.Strategy => "💡",
        QuestionCategory.Clarifications => "❓",
        _ => "❓"
    };
}
