import { describe, expect, it } from 'vitest';

import {
  formatApaCitation,
  truncateAtWordBoundary,
  type ApaCitationInput,
} from '../citation-format';

describe('truncateAtWordBoundary', () => {
  it('returns short text unchanged (≤ maxWords)', () => {
    expect(truncateAtWordBoundary('one two three', 25)).toBe('one two three');
  });

  it('returns text unchanged when word count equals the limit (no ellipsis)', () => {
    const five = 'a b c d e';
    expect(truncateAtWordBoundary(five, 5)).toBe('a b c d e');
  });

  it('truncates to exactly maxWords + ellipsis when over the limit', () => {
    const words = Array.from({ length: 30 }, (_, i) => `w${i + 1}`).join(' ');
    const result = truncateAtWordBoundary(words, 25);
    expect(result).toBe(`${Array.from({ length: 25 }, (_, i) => `w${i + 1}`).join(' ')}…`);
    // 25 words + trailing ellipsis, never a 26th word.
    expect(result.split(' ')).toHaveLength(25);
    expect(result.endsWith('…')).toBe(true);
  });

  it('never splits a word mid-token', () => {
    const words =
      'supercalifragilistic expialidocious antidisestablishmentarianism floccinaucinihilipilification';
    const result = truncateAtWordBoundary(words, 2);
    expect(result).toBe('supercalifragilistic expialidocious…');
  });

  it('uses the default 25-word budget when maxWords is omitted', () => {
    const words = Array.from({ length: 40 }, (_, i) => `x${i}`).join(' ');
    expect(truncateAtWordBoundary(words).split(' ')).toHaveLength(25);
  });

  it('collapses internal whitespace and trims edges', () => {
    expect(truncateAtWordBoundary('  hello   world  ', 25)).toBe('hello world');
  });

  it('returns empty string for empty / whitespace-only input (no dangling ellipsis)', () => {
    expect(truncateAtWordBoundary('', 25)).toBe('');
    expect(truncateAtWordBoundary('   ', 25)).toBe('');
  });
});

describe('formatApaCitation', () => {
  const base: ApaCitationInput = {
    publisher: 'Kosmos',
    publicationYear: 1995,
    gameTitle: 'Catan',
    documentName: 'Catan Rulebook',
    pdfPage: 12,
    quote: 'You may only trade on your own turn.',
    analysisId: '99999999-9999-4999-8999-999999999999',
  };

  it('produces the exact APA block (AC-3) with all fields present', () => {
    expect(formatApaCitation(base)).toBe(
      'Kosmos. (1995). Catan: Catan Rulebook (p. 12).\n' +
        '[Excerpt]: "You may only trade on your own turn."\n' +
        'Generated by MeepleAI mechanic extractor (analysis_id=99999999-9999-4999-8999-999999999999).'
    );
  });

  it('falls back to [publisher unknown] when publisher is missing', () => {
    expect(formatApaCitation({ ...base, publisher: null })).toContain(
      '[publisher unknown]. (1995).'
    );
    expect(formatApaCitation({ ...base, publisher: '   ' })).toContain(
      '[publisher unknown]. (1995).'
    );
  });

  it('falls back to [n.d.] when publicationYear is missing', () => {
    expect(formatApaCitation({ ...base, publicationYear: null })).toContain('Kosmos. ([n.d.]).');
  });

  it('falls back to Rulebook when documentName is missing', () => {
    expect(formatApaCitation({ ...base, documentName: null })).toContain(
      'Catan: Rulebook (p. 12).'
    );
    expect(formatApaCitation({ ...base, documentName: '  ' })).toContain(
      'Catan: Rulebook (p. 12).'
    );
  });

  it('renders (p. n/a) when the page is missing', () => {
    expect(formatApaCitation({ ...base, pdfPage: null })).toContain('(p. n/a).');
  });

  it('renders an empty excerpt when the quote is missing', () => {
    expect(formatApaCitation({ ...base, quote: null })).toContain('[Excerpt]: ""');
  });

  it('applies every fallback simultaneously', () => {
    expect(
      formatApaCitation({
        publisher: null,
        publicationYear: null,
        gameTitle: 'Mystery Game',
        documentName: null,
        pdfPage: null,
        quote: null,
        analysisId: 'abc',
      })
    ).toBe(
      '[publisher unknown]. ([n.d.]). Mystery Game: Rulebook (p. n/a).\n' +
        '[Excerpt]: ""\n' +
        'Generated by MeepleAI mechanic extractor (analysis_id=abc).'
    );
  });
});
