/**
 * E2E — rich inline-citation UX on the public mechanic card (ME-M2.1, Issue #530).
 *
 * `/games/[id]/card` is an `(authenticated)` route gated by proxy.ts. Under
 * PLAYWRIGHT_AUTH_BYPASS we seed the session + role cookies (`seedMockRoleCookies`)
 * so the proxy resolves the user, and mock `/auth/me` + `/session/status`
 * (`mockAuthEndpoints`) so AuthProvider doesn't hang.
 *
 * The card endpoint `GET /api/v1/games/{id}/card` is mocked via
 * `page.context().route(...)` (NOT `page.route` — project convention). The card
 * DTO carries the 3 new #530 fields (`sourceAnalysisId`, `publicationYear`,
 * `documentName`) that feed the APA "copy citation" output.
 *
 * The PDF fetch (`/api/v1/pdfs/{id}/download`) is stubbed with a minimal valid
 * one-page PDF so pdfjs mounts without a real file.
 *
 * Scenarios (BDD): hover tooltip · 25-word truncation · click opens panel ·
 * ESC restores focus · copy APA · clipboard-fallback modal · mobile Drawer.
 *
 * NOTE: not run in CI here (needs a dev server); this file must compile + typecheck.
 */
import { test, expect, type Page, type Route } from '@playwright/test';

import { mockAuthEndpoints, seedMockRoleCookies } from './_helpers/seedAuthSession';
import { seedCookieConsent } from './_helpers/seedCookieConsent';

const GAME_ID = '00000000-0000-4000-8000-000000000530';
const PDF_ID = 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';

// A long quote (>25 words) so we can assert word-boundary truncation in the tooltip.
const LONG_QUOTE =
  'On your turn you may trade resources with the bank at a rate of four to one, ' +
  'or with other players at any rate you can mutually agree upon, but never during ' +
  'another player turn under any circumstances whatsoever here.';

const SAMPLE_CARD = {
  cardId: '11111111-1111-4111-8111-111111111111',
  sharedGameId: GAME_ID,
  title: 'Catan — Mechanics',
  version: 3,
  publishedAt: '2026-05-01T00:00:00Z',
  gameName: 'Catan',
  publisher: 'Kosmos',
  language: 'en',
  sourceAnalysisId: '99999999-9999-4999-8999-999999999999',
  publicationYear: 1995,
  documentName: 'Catan Rulebook',
  sections: [
    {
      section: 'Summary',
      claims: [
        {
          id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
          claim: 'Players collect resources to build settlements and cities.',
          citations: [{ pdfId: PDF_ID, pdfPage: 12, quote: LONG_QUOTE }],
        },
      ],
    },
  ],
};

// The exact APA string the panel should copy for the citation above.
const EXPECTED_APA =
  'Kosmos. (1995). Catan: Catan Rulebook (p. 12).\n' +
  '[Excerpt]: "' +
  LONG_QUOTE +
  '"\n' +
  'Generated by MeepleAI mechanic extractor (analysis_id=99999999-9999-4999-8999-999999999999).';

// Minimal single-page PDF (valid enough for pdfjs to open).
const MINIMAL_PDF = [
  '%PDF-1.1',
  '1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj',
  '2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj',
  '3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]>>endobj',
  'trailer<</Root 1 0 R>>',
  '%%EOF',
].join('\n');

async function seedAuth(page: Page): Promise<void> {
  await seedMockRoleCookies(page, 'User');
  await seedCookieConsent(page);
  await mockAuthEndpoints(page);
}

async function mockCardAndPdf(page: Page): Promise<void> {
  await page.context().route(/\/api\/v1\/games\/[^/]+\/card(\?.*)?$/, async (route: Route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(SAMPLE_CARD),
    });
  });
  await page.context().route(/\/api\/v1\/pdfs\/[^/]+\/download(\?.*)?$/, async (route: Route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/pdf',
      body: MINIMAL_PDF,
    });
  });
}

const badgeTestId = `mechanic-card-citation-${PDF_ID}-12`;

test.describe('Mechanic card citations — /games/[id]/card (#530)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAuth(page);
    await mockCardAndPdf(page);
    await page.goto(`/games/${GAME_ID}/card`, { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId('mechanic-card-title')).toHaveText('Catan');
  });

  test('hovering a citation badge shows the truncated (≤25-word) quote tooltip', async ({
    page,
  }) => {
    const badge = page.getByTestId(badgeTestId);
    await badge.hover();

    const tooltip = page.getByRole('tooltip');
    await expect(tooltip).toBeVisible();

    // Truncated to 25 words + ellipsis, never a 26th word.
    const text = (await tooltip.textContent())?.trim() ?? '';
    expect(text.endsWith('…')).toBe(true);
    const wordCount = text.replace(/…$/, '').trim().split(/\s+/).length;
    expect(wordCount).toBe(25);
  });

  test('clicking a badge opens the responsive citation panel with the source', async ({ page }) => {
    await page.getByTestId(badgeTestId).click();

    const panel = page.getByTestId('mechanic-citation-panel-sheet');
    await expect(panel).toBeVisible();
    await expect(page.getByText('Catan Rulebook')).toBeVisible();
    await expect(page.getByTestId('mechanic-citation-copy')).toBeVisible();
  });

  test('ESC closes the panel and restores focus to the badge that opened it', async ({ page }) => {
    const badge = page.getByTestId(badgeTestId);
    await badge.focus();
    await badge.press('Enter');

    await expect(page.getByTestId('mechanic-citation-panel-sheet')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByTestId('mechanic-citation-panel-sheet')).toBeHidden();

    // Focus returns to the triggering badge.
    await expect(badge).toBeFocused();
  });

  test('“Copia citazione” writes the exact APA string to the clipboard', async ({
    page,
    context,
  }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.getByTestId(badgeTestId).click();
    await page.getByTestId('mechanic-citation-copy').click();

    const clip = await page.evaluate(() => navigator.clipboard.readText());
    expect(clip).toBe(EXPECTED_APA);
  });

  test('falls back to a manual copy modal when the Clipboard API is unavailable', async ({
    page,
  }) => {
    // Strip navigator.clipboard before the panel renders.
    await page.addInitScript(() => {
      Object.defineProperty(navigator, 'clipboard', { value: undefined, configurable: true });
    });
    await page.reload({ waitUntil: 'domcontentloaded' });

    await page.getByTestId(badgeTestId).click();
    await page.getByTestId('mechanic-citation-copy').click();

    const fallback = page.getByTestId('mechanic-citation-copy-fallback');
    await expect(fallback).toBeVisible();
    await expect(fallback.getByText(/Premi Ctrl\+C per copiare/)).toBeVisible();
    await expect(page.getByLabel('Testo della citazione')).toHaveValue(EXPECTED_APA);
  });

  test('renders a bottom Drawer instead of the Sheet on a mobile viewport', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 780 });
    await page.getByTestId(badgeTestId).click();

    await expect(page.getByTestId('mechanic-citation-panel-drawer')).toBeVisible();
    await expect(page.getByTestId('mechanic-citation-panel-sheet')).toHaveCount(0);
  });
});
