using Api.BoundedContexts.DocumentProcessing.Application.Queries;
using Api.Infrastructure;
using Api.Infrastructure.Entities;
using Api.Services.Pdf;
using Api.SharedKernel.Application.Services;
using Api.Tests.Constants;
using FluentAssertions;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Xunit;

namespace Api.Tests.BoundedContexts.DocumentProcessing.Application.Queries;

/// <summary>
/// Unit tests for DownloadPdfQueryHandler.
/// Issue #3568: the blob fileId is a random GUID generated by StoreAsync and persisted inside
/// FilePath ({category}/{resourceKey}/{fileId}_{name}); it is NOT the pdfId. The handler used to pass
/// the pdfId-derived bucket key as the fileId, so the lookup searched pdfs/{pdfId}/{pdfId}_* and
/// matched nothing — a 404 on files that exist in storage.
/// </summary>
[Trait("Category", TestCategories.Unit)]
[Trait("BoundedContext", "DocumentProcessing")]
public class DownloadPdfQueryHandlerTests
{
    private static MeepleAiDbContext CreateDbContext() =>
        new(new DbContextOptionsBuilder<MeepleAiDbContext>()
                .UseInMemoryDatabase(Guid.NewGuid().ToString())
                .Options,
            new Mock<IMediator>().Object,
            new Mock<IDomainEventCollector>().Object);

    private static readonly Guid uploaderId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    private static PdfDocumentEntity SeedPdf(MeepleAiDbContext ctx, Guid pdfId, string filePath)
    {
        var pdf = new PdfDocumentEntity
        {
            Id = pdfId,
            FileName = "rulebook.pdf",
            FilePath = filePath,
            ContentType = "application/pdf",
            ProcessingState = "Ready",
            SharedGameId = Guid.NewGuid(),
            UploadedByUserId = uploaderId
        };
        ctx.PdfDocuments.Add(pdf);
        ctx.SaveChanges();
        return pdf;
    }

    [Fact]
    public async Task Handle_UsesFileIdFromFilePath_NotThePdfId()
    {
        // Arrange — the stored fileId differs from the pdfId, as StoreAsync always produces
        var pdfId = Guid.Parse("d1e43e9e-9b8f-4ea5-b300-72db7b94c66f");
        var bucketKey = pdfId.ToString("N");
        const string storedFileId = "728c58a174b4425ab5330a64276eecad";

        using var ctx = CreateDbContext();
        SeedPdf(ctx, pdfId, $"pdfs/{bucketKey}/{storedFileId}_wingspan_en_rulebook.pdf");

        string? capturedFileId = null;
        string? capturedResourceKey = null;
        var blob = new Mock<IBlobStorageService>();
        blob.Setup(b => b.RetrieveAsync(It.IsAny<string>(), BlobCategory.Pdf, It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<string, BlobCategory, string, CancellationToken>((f, _, r, _) =>
            {
                capturedFileId = f;
                capturedResourceKey = r;
            })
            .ReturnsAsync(() => new MemoryStream([1, 2, 3]));

        var handler = new DownloadPdfQueryHandler(ctx, blob.Object, NullLogger<DownloadPdfQueryHandler>.Instance);

        // Act
        var result = await handler.Handle(new DownloadPdfQuery(pdfId, uploaderId, false), default);

        // Assert
        result.Should().NotBeNull();
        capturedFileId.Should().Be(storedFileId, "the fileId must come from FilePath, not from the pdfId");
        capturedResourceKey.Should().Be(bucketKey, "the resourceKey is still the pdfId-derived bucket");
    }

    /// <summary>
    /// Issue #3568: the resourceKey is not the pdfId either. `UploadPdfCommandHandler` stores under
    /// `gameId ?? privateGameId`, `UploadSharedGamePdfCommandHandler` under `shared-game-{id}`, the
    /// import wizard under `wizard-temp` — only the seeded corpus happens to use the pdfId. Both blob
    /// backends resolve by exact `{category}/{resourceKey}/{fileId}_` prefix, so reading with the
    /// pdfId-derived bucket looks in a folder that does not exist and 404s a file that is there.
    /// </summary>
    [Fact]
    public async Task Handle_UsesResourceKeyFromFilePath_WhenItIsNotThePdfId()
    {
        var pdfId = Guid.NewGuid();
        const string gameId = "7f3a1c2e-0000-4444-8888-abcdefabcdef"; // the upload-time resourceKey
        const string storedFileId = "0123456789abcdef0123456789abcdef";

        using var ctx = CreateDbContext();
        SeedPdf(ctx, pdfId, $"pdfs/{gameId}/{storedFileId}_rulebook.pdf");

        string? capturedFileId = null;
        string? capturedResourceKey = null;
        var blob = new Mock<IBlobStorageService>();
        blob.Setup(b => b.RetrieveAsync(It.IsAny<string>(), BlobCategory.Pdf, It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<string, BlobCategory, string, CancellationToken>((f, _, r, _) =>
            {
                capturedFileId = f;
                capturedResourceKey = r;
            })
            .ReturnsAsync(() => new MemoryStream([1]));

        var handler = new DownloadPdfQueryHandler(ctx, blob.Object, NullLogger<DownloadPdfQueryHandler>.Instance);

        var result = await handler.Handle(new DownloadPdfQuery(pdfId, uploaderId, false), default);

        result.Should().NotBeNull();
        capturedFileId.Should().Be(storedFileId);
        capturedResourceKey.Should().Be(gameId, "the file lives under the upload-time resourceKey, not under the pdfId");
    }

    [Fact]
    public async Task Handle_WhenFilePathHasNoRecoverableFileId_FallsBackToBucketKey()
    {
        // A legacy FilePath that does not match {resourceKey}/{fileId}_{name}: keep the old lookup
        // rather than failing outright.
        var pdfId = Guid.NewGuid();
        using var ctx = CreateDbContext();
        SeedPdf(ctx, pdfId, "legacy-path-without-separator-or-underscore");

        string? capturedFileId = null;
        var blob = new Mock<IBlobStorageService>();
        blob.Setup(b => b.RetrieveAsync(It.IsAny<string>(), BlobCategory.Pdf, It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<string, BlobCategory, string, CancellationToken>((f, _, _, _) => capturedFileId = f)
            .ReturnsAsync(() => new MemoryStream([1]));

        var handler = new DownloadPdfQueryHandler(ctx, blob.Object, NullLogger<DownloadPdfQueryHandler>.Instance);

        await handler.Handle(new DownloadPdfQuery(pdfId, uploaderId, false), default);

        capturedFileId.Should().Be(pdfId.ToString("N"));
    }

    [Fact]
    public async Task Handle_WhenBlobIsMissing_ReturnsNull()
    {
        var pdfId = Guid.NewGuid();
        var bucketKey = pdfId.ToString("N");
        using var ctx = CreateDbContext();
        SeedPdf(ctx, pdfId, $"pdfs/{bucketKey}/abcdef_rulebook.pdf");

        var blob = new Mock<IBlobStorageService>();
        blob.Setup(b => b.RetrieveAsync(It.IsAny<string>(), It.IsAny<BlobCategory>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Stream?)null);

        var handler = new DownloadPdfQueryHandler(ctx, blob.Object, NullLogger<DownloadPdfQueryHandler>.Instance);

        var result = await handler.Handle(new DownloadPdfQuery(pdfId, uploaderId, false), default);

        result.Should().BeNull();
    }
}
