namespace Api.Infrastructure.Entities.SharedGameCatalog;

/// <summary>
/// Persistence entity for GameStateTemplate.
/// Defines the state structure to track for a game, generated by AI or created manually.
/// </summary>
public class GameStateTemplateEntity
{
    /// <summary>
    /// Unique identifier for the template.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// FK to the shared game.
    /// </summary>
    public Guid SharedGameId { get; set; }

    /// <summary>
    /// Name of the template.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// JSON Schema defining the game state structure (stored as JSONB in PostgreSQL).
    /// </summary>
    public string? SchemaJson { get; set; }

    /// <summary>
    /// Version string (e.g., "1.0", "2.1").
    /// </summary>
    public string Version { get; set; } = "1.0";

    /// <summary>
    /// Whether this is the active version for the game.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Source of generation (0=AI, 1=Manual).
    /// </summary>
    public int Source { get; set; }

    /// <summary>
    /// AI confidence score (0-1). Null for manual templates.
    /// </summary>
    public decimal? ConfidenceScore { get; set; }

    /// <summary>
    /// When the template was generated/created.
    /// </summary>
    public DateTime GeneratedAt { get; set; }

    /// <summary>
    /// User who created this template.
    /// </summary>
    public Guid CreatedBy { get; set; }

    // Navigation properties
    public SharedGameEntity SharedGame { get; set; } = default!;
}
