/**
 * Citation formatting utilities — ME-M2.1 (Issue #530).
 *
 * Pure, side-effect-free helpers shared by the citation badge (tooltip preview)
 * and the citation panel (APA-style "copy as quote" output). Kept framework-free
 * so they are trivial to unit-test to the exact string.
 */

/** Default word budget for a tooltip quote preview (spec AC: 25 words). */
export const DEFAULT_TOOLTIP_MAX_WORDS = 25;

/** Fallback document label when the source PDF name is unknown. */
export const DOCUMENT_NAME_FALLBACK = 'Rulebook';
/** APA marker for an unknown publisher. */
export const PUBLISHER_UNKNOWN = '[publisher unknown]';
/** APA marker for "no date" (year unknown). */
export const NO_DATE = '[n.d.]';

/**
 * Truncate `text` to at most `maxWords` words, appended with a single-character
 * ellipsis (`…`) when truncated. NEVER splits a word: it always cuts on a word
 * boundary. Leading/trailing whitespace is trimmed and internal runs of
 * whitespace are collapsed to a single space so the preview reads cleanly.
 *
 * - `text` with ≤ `maxWords` words is returned unchanged (aside from the
 *   whitespace normalization above).
 * - Empty / whitespace-only input returns `''` (no dangling ellipsis).
 */
export function truncateAtWordBoundary(
  text: string,
  maxWords: number = DEFAULT_TOOLTIP_MAX_WORDS
): string {
  const words = text.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return '';
  if (words.length <= maxWords) return words.join(' ');
  return `${words.slice(0, maxWords).join(' ')}…`;
}

/** Input for {@link formatApaCitation}. Mirrors the public card + citation DTO fields. */
export interface ApaCitationInput {
  readonly publisher: string | null | undefined;
  readonly publicationYear: number | null | undefined;
  readonly gameTitle: string;
  readonly documentName: string | null | undefined;
  readonly pdfPage: number | null | undefined;
  readonly quote: string | null | undefined;
  readonly analysisId: string;
}

/**
 * Build the exact APA-style attribution block a user copies to cite a rulebook
 * excerpt (spec AC-3). Produces, verbatim:
 *
 * ```
 * {publisher}. ({year}). {gameTitle}: {documentName} (p. {pdfPage}).
 * [Excerpt]: "{quote}"
 * Generated by MeepleAI mechanic extractor (analysis_id={uuid}).
 * ```
 *
 * Fallbacks: publisher → `[publisher unknown]`; year → `[n.d.]`; documentName →
 * `Rulebook`. A missing page renders as `(p. n/a)`; a missing quote renders as
 * an empty excerpt. The three lines are joined by `\n`.
 */
export function formatApaCitation(input: ApaCitationInput): string {
  const publisher = normalizeText(input.publisher) ?? PUBLISHER_UNKNOWN;
  const year = input.publicationYear == null ? NO_DATE : String(input.publicationYear);
  const documentName = normalizeText(input.documentName) ?? DOCUMENT_NAME_FALLBACK;
  const gameTitle = input.gameTitle;
  const page = input.pdfPage == null ? 'n/a' : String(input.pdfPage);
  const quote = normalizeText(input.quote) ?? '';

  const reference = `${publisher}. (${year}). ${gameTitle}: ${documentName} (p. ${page}).`;
  const excerpt = `[Excerpt]: "${quote}"`;
  const generated = `Generated by MeepleAI mechanic extractor (analysis_id=${input.analysisId}).`;

  return `${reference}\n${excerpt}\n${generated}`;
}

/** Trim a possibly-nullish string; return `null` when it is empty/whitespace. */
function normalizeText(value: string | null | undefined): string | null {
  if (value == null) return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}
