using System;
using System.Reflection;

namespace Api.DevTools;

/// <summary>
/// Generic dispatch proxy that routes method calls to either a real or mock
/// implementation based on runtime toggle state from <see cref="IMockToggleReader"/>.
/// </summary>
/// <typeparam name="TService">
/// Service interface type. Must be an interface. Can be internal (accessible within Api.dll)
/// or public. The dynamic subclass generated by <see cref="DispatchProxy"/> inherits from
/// this class in the same assembly context, so internal interfaces are fully accessible.
/// </typeparam>
internal class MockAwareProxy<TService> : DispatchProxy where TService : class
{
    private TService _real = default!;
    private TService _mock = default!;
    private IMockToggleReader _toggles = default!;
    private string _serviceName = default!;

    /// <summary>
    /// Creates a proxy instance that dispatches to <paramref name="real"/> or
    /// <paramref name="mock"/> depending on the toggle state for <paramref name="serviceName"/>.
    /// </summary>
    /// <param name="real">The real service implementation.</param>
    /// <param name="mock">The mock service implementation.</param>
    /// <param name="toggles">Toggle state reader used on every invocation.</param>
    /// <param name="serviceName">
    /// The service name key checked via <see cref="IMockToggleReader.IsMocked"/>.
    /// </param>
    /// <returns>A <typeparamref name="TService"/> proxy instance.</returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="real"/>, <paramref name="mock"/>, or
    /// <paramref name="toggles"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="serviceName"/> is null or whitespace.
    /// </exception>
    public static TService Create(
        TService real,
        TService mock,
        IMockToggleReader toggles,
        string serviceName)
    {
        ArgumentNullException.ThrowIfNull(real);
        ArgumentNullException.ThrowIfNull(mock);
        ArgumentNullException.ThrowIfNull(toggles);
        ArgumentException.ThrowIfNullOrWhiteSpace(serviceName);

        var proxy = Create<TService, MockAwareProxy<TService>>();
        var impl = (MockAwareProxy<TService>)(object)proxy!;
        impl._real = real;
        impl._mock = mock;
        impl._toggles = toggles;
        impl._serviceName = serviceName;
        return proxy!;
    }

    /// <inheritdoc/>
    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
    {
        if (targetMethod is null)
        {
            throw new InvalidOperationException("DispatchProxy invoked with a null targetMethod.");
        }

        var target = _toggles.IsMocked(_serviceName) ? _mock : _real;
        try
        {
            return targetMethod.Invoke(target, args);
        }
        catch (TargetInvocationException tie) when (tie.InnerException is not null)
        {
            // Unwrap so callers see the original exception type, not TargetInvocationException.
            System.Runtime.ExceptionServices.ExceptionDispatchInfo
                .Capture(tie.InnerException)
                .Throw();
            throw; // unreachable — satisfies compiler flow analysis
        }
    }
}
