#pragma warning disable MA0048 // File name must match type name - Contains related DTOs
using Api.BoundedContexts.GameToolkit.Domain.Enums;

namespace Api.BoundedContexts.GameToolkit.Application.DTOs;

/// <summary>
/// Structured response from LLM for auto-generating a GameToolkit.
/// Used with ILlmService.GenerateJsonAsync&lt;AiToolkitSuggestionDto&gt;().
/// Fields ConfidenceScore/ChunksAnalyzed/KbCoveragePercent/RequiresHumanReview
/// are NOT generated by the LLM — they are populated by the handler after generation.
/// </summary>
internal record AiToolkitSuggestionDto(
    string ToolkitName,
    List<AiDiceToolSuggestion> DiceTools,
    List<AiCounterToolSuggestion> CounterTools,
    List<AiTimerToolSuggestion> TimerTools,
    AiScoringTemplateSuggestion? ScoringTemplate,
    AiTurnTemplateSuggestion? TurnTemplate,
    AiOverrideSuggestion? Overrides,
    string Reasoning,
    // P0: tool types intentionally excluded by LLM (with justification)
    List<AiExcludedToolSuggestion>? ExcludedTools = null,
    // P0: populated by handler (not LLM) — default values safe for deserialization
    float ConfidenceScore = 0f,
    int ChunksAnalyzed = 0,
    float KbCoveragePercent = 0f,
    bool RequiresHumanReview = true
);

internal record AiDiceToolSuggestion(
    string Name,
    DiceType DiceType,
    int Quantity,
    string[]? CustomFaces,
    bool IsInteractive,
    string? Color
);

internal record AiCounterToolSuggestion(
    string Name,
    int MinValue,
    int MaxValue,
    int DefaultValue,
    bool IsPerPlayer,
    string? Icon,
    string? Color
);

internal record AiTimerToolSuggestion(
    string Name,
    int DurationSeconds,
    TimerType TimerType,
    bool AutoStart,
    string? Color,
    bool IsPerPlayer,
    int? WarningThresholdSeconds
);

internal record AiScoringTemplateSuggestion(
    string[] Dimensions,
    string DefaultUnit,
    ScoreType ScoreType
);

internal record AiTurnTemplateSuggestion(
    TurnOrderType TurnOrderType,
    string[] Phases
);

internal record AiOverrideSuggestion(
    bool OverridesTurnOrder,
    bool OverridesScoreboard,
    bool OverridesDiceSet
);

/// <summary>
/// P0: Tool type intentionally not included by the LLM, with reason.
/// Example: { ToolType = "CardTool", Reason = "Catan does not use a card deck according to the rules." }
/// </summary>
internal record AiExcludedToolSuggestion(
    string ToolType,
    string Reason
);
