import type { ComponentCategory } from '@/components/showcase/types';

export type AppArea = 'shared' | 'admin' | 'auth' | 'chat' | 'library' | 'public';

export interface MockVariant {
  name: string;
  props: Record<string, unknown>;
}

export interface ComponentEntry {
  id: string;
  name: string;
  importPath: string;
  category: ComponentCategory;
  areas: AppArea[];
  tier: 'interactive' | 'static';
  description: string;
  mockProps?: Record<string, unknown>;
  mockVariants?: MockVariant[];
  tags?: string[];
  compositions?: string[];
}

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ─── Data Display ─────────────────────────────────────────────────────────

  {
    id: 'meeple-card',
    name: 'MeepleCard',
    importPath: '@/components/ui/data-display/meeple-card/MeepleCard',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Universal card component for displaying games, players, collections, and events.',
    tags: ['card', 'entity', 'game', 'player'],
    compositions: ['game-list', 'player-roster'],
  },
  {
    id: 'meeple-card-compact',
    name: 'MeepleCardCompact',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardCompact',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Compact variant of MeepleCard for dense list views.',
    tags: ['card', 'compact', 'list'],
  },
  {
    id: 'meeple-card-expanded',
    name: 'MeepleCardExpanded',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardExpanded',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Expanded variant of MeepleCard showing full details.',
    tags: ['card', 'expanded', 'detail'],
  },
  {
    id: 'meeple-card-featured',
    name: 'MeepleCardFeatured',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardFeatured',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Featured variant of MeepleCard for hero placement.',
    tags: ['card', 'featured', 'hero'],
  },
  {
    id: 'meeple-card-grid',
    name: 'MeepleCardGrid',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardGrid',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Grid variant of MeepleCard optimised for grid layouts.',
    tags: ['card', 'grid'],
  },
  {
    id: 'meeple-card-hero',
    name: 'MeepleCardHero',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardHero',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Hero variant of MeepleCard for full-width banner display.',
    tags: ['card', 'hero', 'banner'],
  },
  {
    id: 'meeple-card-list',
    name: 'MeepleCardList',
    importPath: '@/components/ui/data-display/meeple-card/variants/MeepleCardList',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'List variant of MeepleCard for horizontal row display.',
    tags: ['card', 'list', 'row'],
  },
  {
    id: 'carta-estesa',
    name: 'CartaEstesa',
    importPath: '@/components/ui/data-display/meeple-card/CartaEstesa',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Extended card layout with back-face and flip animation support.',
    tags: ['card', 'flip', 'extended'],
  },
  {
    id: 'meeple-card-compound',
    name: 'MeepleCardCompound',
    importPath: '@/components/ui/data-display/meeple-card-compound',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Compound card component combining multiple card sub-components.',
    tags: ['card', 'compound', 'composite'],
  },
  {
    id: 'meeple-card-browser',
    name: 'MeepleCardBrowser',
    importPath: '@/components/ui/data-display/meeple-card-browser/MeepleCardBrowser',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description:
      'Full browsing UI with deck-stack drawer and card link bar for navigating entity cards.',
    tags: ['browser', 'deck', 'navigation', 'card'],
  },
  {
    id: 'extra-meeple-card',
    name: 'ExtraMeepleCard',
    importPath: '@/components/ui/data-display/extra-meeple-card/ExtraMeepleCard',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description:
      'Extended card with tabbed detail drawer for AI, history, media, scoreboard, and toolkit tabs.',
    tags: ['card', 'drawer', 'tabs', 'detail'],
    compositions: ['game-detail-card'],
  },
  {
    id: 'extra-meeple-card-drawer',
    name: 'ExtraMeepleCardDrawer',
    importPath: '@/components/ui/data-display/extra-meeple-card/ExtraMeepleCardDrawer',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Slide-up drawer component for the ExtraMeepleCard detail view.',
    tags: ['drawer', 'card', 'detail'],
  },
  {
    id: 'entity-extra-meeple-card',
    name: 'EntityExtraMeepleCard',
    importPath: '@/components/ui/data-display/extra-meeple-card/EntityExtraMeepleCard',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Entity-aware wrapper around ExtraMeepleCard that auto-resolves entity type.',
    tags: ['card', 'entity', 'detail'],
  },
  {
    id: 'entity-list-view',
    name: 'EntityListView',
    importPath: '@/components/ui/data-display/entity-list-view/entity-list-view',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description:
      'Filterable, sortable, paginated list view for any entity type with grid and table modes.',
    tags: ['list', 'filter', 'sort', 'entity'],
    compositions: ['game-list', 'player-roster'],
  },
  {
    id: 'game-carousel',
    name: 'GameCarousel',
    importPath: '@/components/ui/data-display/game-carousel',
    category: 'Data Display',
    areas: ['shared', 'library'],
    tier: 'interactive',
    description: 'Horizontally scrollable carousel for displaying game cards.',
    tags: ['carousel', 'game', 'scroll'],
    compositions: ['game-list'],
  },
  {
    id: 'meeple-info-card',
    name: 'MeepleInfoCard',
    importPath: '@/components/ui/data-display/meeple-info-card',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Info card overlay displaying detailed meeple entity metadata.',
    tags: ['info', 'card', 'metadata'],
  },
  {
    id: 'data-table',
    name: 'DataTable',
    importPath: '@/components/ui/data-display/data-table',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'interactive',
    description: 'Full-featured data table with sorting, filtering, and pagination.',
    tags: ['table', 'data', 'sort', 'filter'],
    compositions: ['admin-users-table'],
  },
  {
    id: 'accordion',
    name: 'Accordion',
    importPath: '@/components/ui/data-display/accordion',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Collapsible accordion component for showing/hiding content sections.',
    tags: ['accordion', 'collapse', 'expand'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    importPath: '@/components/ui/data-display/avatar',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'User avatar component with image fallback to initials.',
    tags: ['avatar', 'user', 'image'],
  },
  {
    id: 'badge',
    name: 'Badge',
    importPath: '@/components/ui/data-display/badge',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Small badge label for status indicators and counts.',
    tags: ['badge', 'label', 'status'],
  },
  {
    id: 'card',
    name: 'Card',
    importPath: '@/components/ui/data-display/card',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Base card container with header, content, and footer slots.',
    tags: ['card', 'container', 'layout'],
  },
  {
    id: 'card-grid-skeletons',
    name: 'CardGridSkeletons',
    importPath: '@/components/ui/data-display/CardGridSkeletons',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Loading skeleton grid that matches the shape of card grid layouts.',
    tags: ['skeleton', 'loading', 'grid'],
  },
  {
    id: 'citation-link',
    name: 'CitationLink',
    importPath: '@/components/ui/data-display/citation-link',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Inline citation link with source preview tooltip for AI chat responses.',
    tags: ['citation', 'link', 'ai', 'source'],
  },
  {
    id: 'collapsible',
    name: 'Collapsible',
    importPath: '@/components/ui/data-display/collapsible',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Toggle-able collapsible section for progressive disclosure.',
    tags: ['collapsible', 'toggle', 'expand'],
  },
  {
    id: 'collection-limit-indicator',
    name: 'CollectionLimitIndicator',
    importPath: '@/components/ui/data-display/CollectionLimitIndicator',
    category: 'Data Display',
    areas: ['shared', 'library'],
    tier: 'static',
    description: 'Displays current vs maximum collection size for tier-limited users.',
    tags: ['collection', 'limit', 'tier'],
  },
  {
    id: 'confidence-badge',
    name: 'ConfidenceBadge',
    importPath: '@/components/ui/data-display/confidence-badge',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'interactive',
    description: 'Visual badge showing AI response confidence score with colour coding.',
    tags: ['confidence', 'ai', 'score', 'badge'],
    compositions: ['rag-debug'],
  },
  {
    id: 'entity-link-badge',
    name: 'EntityLinkBadge',
    importPath: '@/components/ui/data-display/entity-link/entity-link-badge',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Corner badge showing entity relationship type on a card.',
    tags: ['entity', 'link', 'badge', 'relationship'],
  },
  {
    id: 'entity-link-card',
    name: 'EntityLinkCard',
    importPath: '@/components/ui/data-display/entity-link/entity-link-card',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Card displaying a related entity with link type and navigation.',
    tags: ['entity', 'link', 'card', 'relationship'],
  },
  {
    id: 'entity-link-chip',
    name: 'EntityLinkChip',
    importPath: '@/components/ui/data-display/entity-link/entity-link-chip',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Compact chip displaying entity link type with icon.',
    tags: ['entity', 'link', 'chip'],
  },
  {
    id: 'entity-link-preview-row',
    name: 'EntityLinkPreviewRow',
    importPath: '@/components/ui/data-display/entity-link/entity-link-preview-row',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Footer row previewing linked entities with count overflow.',
    tags: ['entity', 'link', 'preview', 'row'],
  },
  {
    id: 'entity-relationship-graph',
    name: 'EntityRelationshipGraph',
    importPath: '@/components/ui/data-display/entity-link/entity-relationship-graph',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Interactive React Flow graph visualising entity relationships.',
    tags: ['graph', 'entity', 'relationship', 'react-flow'],
  },
  {
    id: 'related-entities-section',
    name: 'RelatedEntitiesSection',
    importPath: '@/components/ui/data-display/entity-link/related-entities-section',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Section component showing related entities with list/graph toggle.',
    tags: ['entity', 'related', 'section'],
  },
  {
    id: 'add-entity-link-modal',
    name: 'AddEntityLinkModal',
    importPath: '@/components/ui/data-display/entity-link/add-entity-link-modal',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Modal dialog for creating entity relationship links.',
    tags: ['entity', 'link', 'modal', 'create'],
  },
  {
    id: 'compact-icon-bar',
    name: 'CompactIconBar',
    importPath: '@/components/ui/data-display/entity-link/compact-icon-bar',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Compact row of icon buttons for entity link actions.',
    tags: ['icon', 'bar', 'compact', 'actions'],
  },
  {
    id: 'list-page-header',
    name: 'ListPageHeader',
    importPath: '@/components/ui/data-display/ListPageHeader',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Standardised page header for list pages with title, subtitle, and action slot.',
    tags: ['header', 'page', 'list'],
  },
  {
    id: 'rating-stars',
    name: 'RatingStars',
    importPath: '@/components/ui/data-display/rating-stars',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Star rating display component with configurable max and precision.',
    tags: ['rating', 'stars', 'score'],
  },
  {
    id: 'stat-card',
    name: 'StatCard',
    importPath: '@/components/ui/data-display/stat-card',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'KPI stat card with value, label, and optional trend indicator.',
    tags: ['stat', 'kpi', 'metric'],
  },
  {
    id: 'status-card',
    name: 'StatusCard',
    importPath: '@/components/ui/data-display/status-card',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Card showing service or entity status with colour-coded indicator.',
    tags: ['status', 'card', 'indicator'],
  },
  {
    id: 'table',
    name: 'Table',
    importPath: '@/components/ui/data-display/table',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Base HTML table component with styled rows, headers, and cells.',
    tags: ['table', 'base', 'primitive'],
  },
  {
    id: 'tooltip-data-display',
    name: 'Tooltip',
    importPath: '@/components/ui/data-display/tooltip',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Data-display tooltip wrapper for labelling icons and truncated text.',
    tags: ['tooltip', 'label'],
  },
  {
    id: 'user-role-badge',
    name: 'UserRoleBadge',
    importPath: '@/components/ui/data-display/user-role-badge',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Badge displaying a user role (Admin, Moderator, User) with colour coding.',
    tags: ['user', 'role', 'badge'],
  },
  {
    id: 'user-status-indicator',
    name: 'UserStatusIndicator',
    importPath: '@/components/ui/data-display/user-status-indicator',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Small dot indicator showing online/offline/away user status.',
    tags: ['user', 'status', 'online'],
  },
  {
    id: 'activity-list',
    name: 'ActivityList',
    importPath: '@/components/ui/data-display/activity-list/activity-list',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Chronological activity feed list with icon and timestamp per item.',
    tags: ['activity', 'feed', 'timeline'],
  },
  // ─── MeepleCard Features ──────────────────────────────────────────────────
  {
    id: 'agent-model-info',
    name: 'AgentModelInfo',
    importPath: '@/components/ui/data-display/meeple-card-features/AgentModelInfo',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Displays AI model name and version info on an agent card.',
    tags: ['agent', 'model', 'info'],
  },
  {
    id: 'bulk-select-checkbox',
    name: 'BulkSelectCheckbox',
    importPath: '@/components/ui/data-display/meeple-card-features/BulkSelectCheckbox',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Overlay checkbox on cards for bulk selection operations.',
    tags: ['checkbox', 'bulk', 'select'],
  },
  {
    id: 'card-agent-action',
    name: 'CardAgentAction',
    importPath: '@/components/ui/data-display/meeple-card-features/CardAgentAction',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Action button on a card for launching the associated AI agent.',
    tags: ['agent', 'action', 'card'],
  },
  {
    id: 'card-navigation-footer',
    name: 'CardNavigationFooter',
    importPath: '@/components/ui/data-display/meeple-card-features/CardNavigationFooter',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Card footer with prev/next navigation and breadcrumb context.',
    tags: ['card', 'navigation', 'footer'],
  },
  {
    id: 'document-status-badge',
    name: 'DocumentStatusBadge',
    importPath: '@/components/ui/data-display/meeple-card-features/DocumentStatusBadge',
    category: 'Data Display',
    areas: ['shared', 'admin'],
    tier: 'static',
    description: 'Badge showing document processing status (pending, indexed, failed).',
    tags: ['document', 'status', 'badge'],
  },
  {
    id: 'drag-handle',
    name: 'DragHandle',
    importPath: '@/components/ui/data-display/meeple-card-features/DragHandle',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Grip handle for drag-and-drop reordering of card lists.',
    tags: ['drag', 'handle', 'sort'],
  },
  {
    id: 'flip-card',
    name: 'FlipCard',
    importPath: '@/components/ui/data-display/meeple-card-features/FlipCard',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Card with CSS 3D flip animation revealing a back face.',
    tags: ['flip', 'card', 'animation'],
  },
  {
    id: 'game-back-content',
    name: 'GameBackContent',
    importPath: '@/components/ui/data-display/meeple-card-features/GameBackContent',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Back face content for a flipped game card with stats and lore.',
    tags: ['game', 'card', 'back', 'flip'],
  },
  {
    id: 'hover-preview',
    name: 'HoverPreview',
    importPath: '@/components/ui/data-display/meeple-card-features/HoverPreview',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Popover preview shown on card hover with summary information.',
    tags: ['hover', 'preview', 'popover'],
  },
  {
    id: 'quick-actions-menu',
    name: 'QuickActionsMenu',
    importPath: '@/components/ui/data-display/meeple-card-features/QuickActionsMenu',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Overflow dropdown menu for quick card actions (edit, delete, share).',
    tags: ['menu', 'actions', 'dropdown'],
  },
  {
    id: 'session-action-buttons',
    name: 'SessionActionButtons',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionActionButtons',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Action buttons on a session card (start, pause, end).',
    tags: ['session', 'actions', 'buttons'],
  },
  {
    id: 'session-back-content',
    name: 'SessionBackContent',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionBackContent',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Back face content for a session card showing scores and players.',
    tags: ['session', 'card', 'back'],
  },
  {
    id: 'session-player-popup',
    name: 'SessionPlayerPopup',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionPlayerPopup',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Popup showing player details within a session context.',
    tags: ['session', 'player', 'popup'],
  },
  {
    id: 'session-score-modal',
    name: 'SessionScoreModal',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionScoreModal',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Modal for entering and editing player scores during a session.',
    tags: ['session', 'score', 'modal'],
  },
  {
    id: 'session-score-table',
    name: 'SessionScoreTable',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionScoreTable',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Table listing player scores in a session.',
    tags: ['session', 'score', 'table'],
  },
  {
    id: 'session-status-badge',
    name: 'SessionStatusBadge',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionStatusBadge',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Badge indicating session state (active, paused, completed).',
    tags: ['session', 'status', 'badge'],
  },
  {
    id: 'session-turn-sequence',
    name: 'SessionTurnSequence',
    importPath: '@/components/ui/data-display/meeple-card-features/SessionTurnSequence',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Visual display of player turn order in an active session.',
    tags: ['session', 'turn', 'order'],
  },
  {
    id: 'snapshot-history-slider',
    name: 'SnapshotHistorySlider',
    importPath: '@/components/ui/data-display/meeple-card-features/SnapshotHistorySlider',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Timeline slider for scrubbing through session state snapshots.',
    tags: ['snapshot', 'history', 'slider', 'time-travel'],
  },
  {
    id: 'status-badge',
    name: 'StatusBadge',
    importPath: '@/components/ui/data-display/meeple-card-features/StatusBadge',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Generic status badge with configurable colour and label.',
    tags: ['status', 'badge', 'generic'],
  },
  {
    id: 'time-travel-overlay',
    name: 'TimeTravelOverlay',
    importPath: '@/components/ui/data-display/meeple-card-features/TimeTravelOverlay',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Overlay UI for time-travel mode showing historical state.',
    tags: ['time-travel', 'overlay', 'history'],
  },
  {
    id: 'wishlist-button',
    name: 'WishlistButton',
    importPath: '@/components/ui/data-display/meeple-card-features/WishlistButton',
    category: 'Data Display',
    areas: ['shared', 'library'],
    tier: 'interactive',
    description: 'Toggle button for adding/removing a game from the wishlist.',
    tags: ['wishlist', 'toggle', 'game'],
  },
  {
    id: 'chat-agent-info',
    name: 'ChatAgentInfo',
    importPath: '@/components/ui/data-display/meeple-card-features/ChatAgentInfo',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Displays agent name and model info in a chat card.',
    tags: ['chat', 'agent', 'info'],
  },
  {
    id: 'chat-game-context',
    name: 'ChatGameContext',
    importPath: '@/components/ui/data-display/meeple-card-features/ChatGameContext',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Shows the game context associated with a chat session.',
    tags: ['chat', 'game', 'context'],
  },
  {
    id: 'chat-stats-display',
    name: 'ChatStatsDisplay',
    importPath: '@/components/ui/data-display/meeple-card-features/ChatStatsDisplay',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Displays token usage and response time stats for a chat.',
    tags: ['chat', 'stats', 'tokens'],
  },
  {
    id: 'chat-status-badge',
    name: 'ChatStatusBadge',
    importPath: '@/components/ui/data-display/meeple-card-features/ChatStatusBadge',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Badge showing the active/idle/error status of a chat session.',
    tags: ['chat', 'status', 'badge'],
  },
  {
    id: 'chat-unread-badge',
    name: 'ChatUnreadBadge',
    importPath: '@/components/ui/data-display/meeple-card-features/ChatUnreadBadge',
    category: 'Data Display',
    areas: ['shared', 'chat'],
    tier: 'static',
    description: 'Numeric badge showing unread message count on a chat card.',
    tags: ['chat', 'unread', 'badge', 'count'],
  },
  {
    id: 'meeple-card-info-button',
    name: 'MeepleCardInfoButton',
    importPath: '@/components/ui/data-display/meeple-card-info-button',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Info icon button that opens the card detail drawer.',
    tags: ['card', 'info', 'button'],
  },
  {
    id: 'meeple-card-quick-actions',
    name: 'MeepleCardQuickActions',
    importPath: '@/components/ui/data-display/meeple-card-quick-actions',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Quick action overlay appearing on card hover with primary actions.',
    tags: ['card', 'actions', 'hover'],
  },
  {
    id: 'meeple-card-mobile-tags',
    name: 'MeepleCardMobileTags',
    importPath: '@/components/ui/data-display/meeple-card-mobile-tags',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: 'Mobile-optimised tag strip for MeepleCard that truncates with overflow.',
    tags: ['card', 'tags', 'mobile'],
  },

  // ─── Feedback ─────────────────────────────────────────────────────────────

  {
    id: 'alert',
    name: 'Alert',
    importPath: '@/components/ui/feedback/alert',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Inline alert banner with severity variants (info, warning, error, success).',
    tags: ['alert', 'banner', 'notification'],
    compositions: ['form-feedback'],
  },
  {
    id: 'alert-dialog',
    name: 'AlertDialog',
    importPath: '@/components/ui/feedback/alert-dialog',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible alert dialog requiring explicit user confirmation.',
    tags: ['alert', 'dialog', 'confirm'],
  },
  {
    id: 'collection-limit-indicator-feedback',
    name: 'CollectionLimitIndicator',
    importPath: '@/components/ui/feedback/collection-limit-indicator',
    category: 'Feedback',
    areas: ['shared', 'library'],
    tier: 'interactive',
    description: 'Progress indicator showing collection usage vs. tier limit.',
    tags: ['collection', 'limit', 'progress'],
  },
  {
    id: 'collection-progress-bar',
    name: 'CollectionProgressBar',
    importPath: '@/components/ui/feedback/collection-progress-bar',
    category: 'Feedback',
    areas: ['shared', 'library'],
    tier: 'static',
    description: 'Linear progress bar for collection slot usage.',
    tags: ['collection', 'progress', 'bar'],
  },
  {
    id: 'feedback-confidence-badge',
    name: 'ConfidenceBadge',
    importPath: '@/components/ui/feedback/ConfidenceBadge',
    category: 'Feedback',
    areas: ['shared', 'admin'],
    tier: 'interactive',
    description: 'Feedback variant of confidence badge with tooltip explanation.',
    tags: ['confidence', 'badge', 'ai'],
  },
  {
    id: 'confirm-dialog',
    name: 'ConfirmDialog',
    importPath: '@/components/ui/feedback/confirm-dialog',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Simple confirm/cancel dialog for destructive action confirmation.',
    tags: ['confirm', 'dialog', 'destructive'],
  },
  {
    id: 'impersonation-banner',
    name: 'ImpersonationBanner',
    importPath: '@/components/ui/feedback/impersonation-banner',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'static',
    description: 'Sticky banner alerting admins when they are impersonating a user.',
    tags: ['impersonation', 'banner', 'admin'],
  },
  {
    id: 'offline-banner',
    name: 'OfflineBanner',
    importPath: '@/components/ui/feedback/offline-banner',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Banner shown when the app detects network connectivity loss.',
    tags: ['offline', 'banner', 'network'],
  },
  {
    id: 'offline-faq-badge',
    name: 'OfflineFaqBadge',
    importPath: '@/components/ui/feedback/offline-faq-badge',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'static',
    description: 'Badge indicating a FAQ is available offline.',
    tags: ['offline', 'faq', 'badge'],
  },
  {
    id: 'progress',
    name: 'Progress',
    importPath: '@/components/ui/feedback/progress',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible linear progress bar with animated fill.',
    tags: ['progress', 'bar', 'loading'],
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    importPath: '@/components/ui/feedback/skeleton',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Animated loading skeleton placeholder matching content shape.',
    tags: ['skeleton', 'loading', 'placeholder'],
  },
  {
    id: 'sonner',
    name: 'Sonner',
    importPath: '@/components/ui/feedback/sonner',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'static',
    description: 'Toast notification container using the Sonner library.',
    tags: ['toast', 'notification', 'sonner'],
  },
  {
    id: 'tier-badge',
    name: 'TierBadge',
    importPath: '@/components/ui/feedback/tier-badge',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Badge displaying user subscription tier (Free, Premium, Contributor).',
    tags: ['tier', 'badge', 'subscription'],
    compositions: ['tier-gate-demo'],
  },
  {
    id: 'upgrade-prompt',
    name: 'UpgradePrompt',
    importPath: '@/components/ui/feedback/upgrade-prompt',
    category: 'Feedback',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Contextual upgrade prompt shown when a user hits a tier limit.',
    tags: ['upgrade', 'tier', 'prompt', 'upsell'],
  },

  // ─── Forms ────────────────────────────────────────────────────────────────

  {
    id: 'button',
    name: 'Button',
    importPath: '@/components/ui/primitives/button',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Core button component with size and variant props.',
    tags: ['button', 'action', 'interactive'],
    compositions: ['form-feedback'],
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    importPath: '@/components/ui/primitives/checkbox',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible checkbox input with indeterminate state support.',
    tags: ['checkbox', 'input', 'form'],
  },
  {
    id: 'input',
    name: 'Input',
    importPath: '@/components/ui/primitives/input',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Styled text input field with validation state variants.',
    tags: ['input', 'text', 'form'],
  },
  {
    id: 'label',
    name: 'Label',
    importPath: '@/components/ui/primitives/label',
    category: 'Forms',
    areas: ['shared'],
    tier: 'static',
    description: 'Accessible form label with required indicator support.',
    tags: ['label', 'form', 'a11y'],
  },
  {
    id: 'radio-group',
    name: 'RadioGroup',
    importPath: '@/components/ui/primitives/radio-group',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible radio button group with keyboard navigation.',
    tags: ['radio', 'group', 'form'],
  },
  {
    id: 'resizable',
    name: 'Resizable',
    importPath: '@/components/ui/primitives/resizable',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Resizable panel layout with draggable dividers.',
    tags: ['resizable', 'panel', 'layout'],
  },
  {
    id: 'scroll-area',
    name: 'ScrollArea',
    importPath: '@/components/ui/primitives/scroll-area',
    category: 'Forms',
    areas: ['shared'],
    tier: 'static',
    description: 'Custom scrollable area with styled scrollbar.',
    tags: ['scroll', 'area', 'container'],
  },
  {
    id: 'slider',
    name: 'Slider',
    importPath: '@/components/ui/primitives/slider',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Range slider input with configurable min, max, and step.',
    tags: ['slider', 'range', 'input'],
  },
  {
    id: 'textarea',
    name: 'Textarea',
    importPath: '@/components/ui/primitives/textarea',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Multi-line text input with auto-resize support.',
    tags: ['textarea', 'input', 'multiline'],
  },
  {
    id: 'toggle',
    name: 'Toggle',
    importPath: '@/components/ui/primitives/toggle',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Toggle button that maintains pressed/unpressed state.',
    tags: ['toggle', 'button', 'state'],
  },
  {
    id: 'toggle-group',
    name: 'ToggleGroup',
    importPath: '@/components/ui/primitives/toggle-group',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Group of toggle buttons with single or multi-select mode.',
    tags: ['toggle', 'group', 'select'],
  },
  {
    id: 'switch',
    name: 'Switch',
    importPath: '@/components/ui/forms/switch',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible on/off toggle switch.',
    tags: ['switch', 'toggle', 'boolean'],
  },
  {
    id: 'form',
    name: 'Form',
    importPath: '@/components/ui/forms/form',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'React Hook Form integration with accessible error and description slots.',
    tags: ['form', 'validation', 'rhf'],
  },
  {
    id: 'date-range-picker',
    name: 'DateRangePicker',
    importPath: '@/components/ui/inputs/date-range-picker',
    category: 'Forms',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Calendar-based date range picker for filtering by date span.',
    tags: ['date', 'range', 'picker', 'calendar'],
  },

  // ─── Navigation ───────────────────────────────────────────────────────────

  {
    id: 'action-grid',
    name: 'ActionGrid',
    importPath: '@/components/ui/navigation/action-grid',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Grid of labelled action buttons for quick navigation shortcuts.',
    tags: ['action', 'grid', 'shortcuts'],
    compositions: ['admin-quick-actions'],
  },
  {
    id: 'breadcrumb-trail',
    name: 'BreadcrumbTrail',
    importPath: '@/components/ui/navigation/breadcrumb-trail',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'static',
    description: 'Breadcrumb navigation trail with auto-generated paths.',
    tags: ['breadcrumb', 'navigation', 'trail'],
  },
  {
    id: 'card-focus-layout',
    name: 'CardFocusLayout',
    importPath: '@/components/ui/navigation/card-focus-layout',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'static',
    description: 'Layout wrapper that gives focus to a single featured card.',
    tags: ['layout', 'focus', 'card'],
  },
  {
    id: 'card-stack-panel',
    name: 'CardStackPanel',
    importPath: '@/components/ui/navigation/card-stack-panel',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Left panel showing a stack of navigation cards in hand-fan style.',
    tags: ['card', 'stack', 'panel', 'navigation'],
  },
  {
    id: 'command',
    name: 'Command',
    importPath: '@/components/ui/navigation/command',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Command palette with fuzzy search for navigating the app.',
    tags: ['command', 'palette', 'search'],
  },
  {
    id: 'dropdown-menu',
    name: 'DropdownMenu',
    importPath: '@/components/ui/navigation/dropdown-menu',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible dropdown menu with keyboard navigation support.',
    tags: ['dropdown', 'menu', 'navigation'],
  },
  {
    id: 'focused-card-area',
    name: 'FocusedCardArea',
    importPath: '@/components/ui/navigation/focused-card-area',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'static',
    description: 'Content area that highlights a single focused entity card.',
    tags: ['card', 'focus', 'area'],
  },
  {
    id: 'hand-stack',
    name: 'HandStack',
    importPath: '@/components/ui/navigation/hand-stack',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Fan-stack of cards resembling a hand of playing cards.',
    tags: ['hand', 'stack', 'card', 'fan'],
  },
  {
    id: 'separator',
    name: 'Separator',
    importPath: '@/components/ui/navigation/separator',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'static',
    description: 'Horizontal or vertical visual separator/divider.',
    tags: ['separator', 'divider', 'line'],
  },
  {
    id: 'sheet',
    name: 'Sheet',
    importPath: '@/components/ui/navigation/sheet',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Slide-in side panel for contextual navigation or forms.',
    tags: ['sheet', 'drawer', 'panel', 'slide'],
  },
  {
    id: 'tabs',
    name: 'Tabs',
    importPath: '@/components/ui/navigation/tabs',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible tab panel with keyboard navigation.',
    tags: ['tabs', 'navigation', 'panel'],
  },
  {
    id: 'theme-toggle',
    name: 'ThemeToggle',
    importPath: '@/components/ui/navigation/ThemeToggle',
    category: 'Navigation',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Button to toggle between light and dark theme.',
    tags: ['theme', 'dark', 'light', 'toggle'],
  },

  // ─── Overlays ─────────────────────────────────────────────────────────────

  {
    id: 'alert-dialog-primitives',
    name: 'AlertDialogPrimitives',
    importPath: '@/components/ui/overlays/alert-dialog-primitives',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Radix Alert Dialog primitives for composing custom confirm dialogs.',
    tags: ['alert-dialog', 'primitives', 'radix'],
  },
  {
    id: 'confirmation-dialog',
    name: 'ConfirmationDialog',
    importPath: '@/components/ui/overlays/confirmation-dialog',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Pre-composed confirmation dialog with title, description, and action buttons.',
    tags: ['confirmation', 'dialog', 'modal'],
  },
  {
    id: 'dialog',
    name: 'Dialog',
    importPath: '@/components/ui/overlays/dialog',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible modal dialog with overlay and focus trapping.',
    tags: ['dialog', 'modal', 'overlay'],
    compositions: ['form-feedback'],
  },
  {
    id: 'hover-card',
    name: 'HoverCard',
    importPath: '@/components/ui/overlays/hover-card',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Card-style popover triggered on hover for rich previews.',
    tags: ['hover', 'card', 'popover'],
  },
  {
    id: 'popover',
    name: 'Popover',
    importPath: '@/components/ui/overlays/popover',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Floating popover panel anchored to a trigger element.',
    tags: ['popover', 'overlay', 'floating'],
  },
  {
    id: 'select',
    name: 'Select',
    importPath: '@/components/ui/overlays/select',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible select dropdown with search and multi-select support.',
    tags: ['select', 'dropdown', 'form'],
  },
  {
    id: 'smart-tooltip',
    name: 'SmartTooltip',
    importPath: '@/components/ui/overlays/smart-tooltip',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Tooltip that automatically detects truncated text and adds title.',
    tags: ['tooltip', 'smart', 'truncate'],
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    importPath: '@/components/ui/overlays/tooltip',
    category: 'Overlays',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Accessible tooltip with configurable side and delay.',
    tags: ['tooltip', 'overlay', 'label'],
  },
  {
    id: 'bulk-collection-warning',
    name: 'BulkCollectionWarning',
    importPath: '@/components/ui/dialogs/bulk-collection-warning',
    category: 'Overlays',
    areas: ['shared', 'library'],
    tier: 'interactive',
    description:
      'Warning dialog shown before bulk-adding games that would exceed collection limit.',
    tags: ['collection', 'warning', 'bulk', 'dialog'],
  },
  {
    id: 'collection-removal-warning',
    name: 'CollectionRemovalWarning',
    importPath: '@/components/ui/dialogs/collection-removal-warning',
    category: 'Overlays',
    areas: ['shared', 'library'],
    tier: 'interactive',
    description: 'Confirmation dialog for removing a game from a collection.',
    tags: ['collection', 'remove', 'warning', 'dialog'],
  },
  {
    id: 'admin-confirmation-dialog',
    name: 'AdminConfirmationDialog',
    importPath: '@/components/ui/admin/admin-confirmation-dialog',
    category: 'Overlays',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Admin-specific confirmation dialog with elevated warning styling.',
    tags: ['admin', 'confirm', 'dialog'],
  },

  // ─── Animations ───────────────────────────────────────────────────────────

  {
    id: 'fade-in',
    name: 'FadeIn',
    importPath: '@/components/ui/animations/FadeIn',
    category: 'Animations',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Wraps children in a fade-in animation on mount.',
    tags: ['fade', 'animation', 'entrance'],
  },
  {
    id: 'modal-animations',
    name: 'ModalAnimations',
    importPath: '@/components/ui/animations/ModalAnimations',
    category: 'Animations',
    areas: ['shared'],
    tier: 'static',
    description: 'Animation presets for modal entrance and exit transitions.',
    tags: ['modal', 'animation', 'transition'],
  },
  {
    id: 'page-transition',
    name: 'PageTransition',
    importPath: '@/components/ui/animations/PageTransition',
    category: 'Animations',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Wraps page content in a smooth route-change transition.',
    tags: ['page', 'transition', 'route'],
  },
  {
    id: 'stagger-children',
    name: 'StaggerChildren',
    importPath: '@/components/ui/animations/StaggerChildren',
    category: 'Animations',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Staggers the entrance animation of child elements in sequence.',
    tags: ['stagger', 'animation', 'children'],
  },

  // ─── Tags ─────────────────────────────────────────────────────────────────

  {
    id: 'tag-badge',
    name: 'TagBadge',
    importPath: '@/components/ui/tags/TagBadge',
    category: 'Tags',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Styled tag badge with optional click handler for filtering.',
    tags: ['tag', 'badge', 'filter'],
  },
  {
    id: 'tag-overflow',
    name: 'TagOverflow',
    importPath: '@/components/ui/tags/TagOverflow',
    category: 'Tags',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Tag list that shows visible tags and collapses overflow into a count chip.',
    tags: ['tag', 'overflow', 'list'],
  },
  {
    id: 'tag-strip',
    name: 'TagStrip',
    importPath: '@/components/ui/tags/TagStrip',
    category: 'Tags',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Horizontal scrollable strip of tag badges.',
    tags: ['tag', 'strip', 'scroll'],
    compositions: ['game-list'],
  },

  // ─── Gates ────────────────────────────────────────────────────────────────

  {
    id: 'feature-gate',
    name: 'FeatureGate',
    importPath: '@/components/ui/gates/FeatureGate',
    category: 'Gates',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Conditionally renders children based on feature flag status.',
    tags: ['gate', 'feature', 'flag'],
    compositions: ['tier-gate-demo'],
  },
  {
    id: 'permission-gate',
    name: 'PermissionGate',
    importPath: '@/components/ui/gates/permission-gate',
    category: 'Gates',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Renders children only if the user has the specified permission.',
    tags: ['gate', 'permission', 'auth'],
  },
  {
    id: 'role-gate',
    name: 'RoleGate',
    importPath: '@/components/ui/gates/role-gate',
    category: 'Gates',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Renders children only if the user has the specified role.',
    tags: ['gate', 'role', 'auth'],
  },
  {
    id: 'tier-gate',
    name: 'TierGate',
    importPath: '@/components/ui/gates/tier-gate',
    category: 'Gates',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Renders children or an upgrade prompt based on user subscription tier.',
    tags: ['gate', 'tier', 'subscription'],
    compositions: ['tier-gate-demo'],
  },

  // ─── Meeple ───────────────────────────────────────────────────────────────

  {
    id: 'chat-message',
    name: 'ChatMessage',
    importPath: '@/components/ui/meeple/chat-message',
    category: 'Meeple',
    areas: ['chat', 'shared'],
    tier: 'interactive',
    description: 'Chat bubble displaying user or AI message with citation support.',
    tags: ['chat', 'message', 'ai', 'bubble'],
    compositions: ['chat-flow'],
  },
  {
    id: 'feedback-buttons',
    name: 'FeedbackButtons',
    importPath: '@/components/ui/meeple/feedback-buttons',
    category: 'Meeple',
    areas: ['chat', 'shared'],
    tier: 'interactive',
    description: 'Thumbs up/down feedback buttons for rating AI responses.',
    tags: ['feedback', 'rating', 'ai'],
  },
  {
    id: 'meeple-avatar',
    name: 'MeepleAvatar',
    importPath: '@/components/ui/meeple/meeple-avatar',
    category: 'Meeple',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Branded avatar using meeple icon with colour variants per entity type.',
    tags: ['avatar', 'meeple', 'brand'],
  },
  {
    id: 'meeple-logo',
    name: 'MeepleLogo',
    importPath: '@/components/ui/meeple/meeple-logo',
    category: 'Meeple',
    areas: ['shared'],
    tier: 'interactive',
    description: 'MeepleAI brand logo with size and colour theme variants.',
    tags: ['logo', 'brand', 'meeple'],
  },
  {
    id: 'motion-button',
    name: 'MotionButton',
    importPath: '@/components/ui/meeple/motion-button',
    category: 'Meeple',
    areas: ['shared'],
    tier: 'interactive',
    description: 'Button with Framer Motion press and hover animations.',
    tags: ['button', 'motion', 'animation'],
  },

  // ─── Agent ────────────────────────────────────────────────────────────────

  {
    id: 'agent-stats-display',
    name: 'AgentStatsDisplay',
    importPath: '@/components/ui/agent/AgentStatsDisplay',
    category: 'Agent',
    areas: ['shared', 'admin'],
    tier: 'interactive',
    description: 'Displays agent performance metrics (latency, token usage, accuracy).',
    tags: ['agent', 'stats', 'metrics'],
  },
  {
    id: 'agent-status-badge',
    name: 'AgentStatusBadge',
    importPath: '@/components/ui/agent/AgentStatusBadge',
    category: 'Agent',
    areas: ['shared', 'admin'],
    tier: 'interactive',
    description: 'Badge showing agent operational status (online, degraded, offline).',
    tags: ['agent', 'status', 'badge'],
  },

  // ─── Icons ────────────────────────────────────────────────────────────────

  {
    id: 'dice-icon-3d',
    name: 'DiceIcon3D',
    importPath: '@/components/ui/icons/dice-icon-3d',
    category: 'Data Display',
    areas: ['shared'],
    tier: 'static',
    description: '3D-style dice icon SVG for decorative use.',
    tags: ['icon', 'dice', '3d', 'decoration'],
  },

  // ─── Background ───────────────────────────────────────────────────────────

  {
    id: 'background-texture',
    name: 'BackgroundTexture',
    importPath: '@/components/ui/BackgroundTexture',
    category: 'Layout',
    areas: ['shared'],
    tier: 'static',
    description: 'Subtle background texture overlay for page sections.',
    tags: ['background', 'texture', 'decoration'],
  },

  // ─── Admin — Layout ───────────────────────────────────────────────────────

  {
    id: 'admin-shell',
    name: 'AdminShell',
    importPath: '@/components/admin/layout/AdminShell',
    category: 'Layout',
    areas: ['admin'],
    tier: 'static',
    description: 'Root layout shell for admin pages with sidebar and top nav.',
    tags: ['admin', 'layout', 'shell'],
  },
  {
    id: 'admin-top-nav',
    name: 'AdminTopNav',
    importPath: '@/components/admin/layout/AdminTopNav',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Top navigation bar for the admin dashboard with section links.',
    tags: ['admin', 'nav', 'top'],
  },
  {
    id: 'admin-contextual-sidebar',
    name: 'AdminContextualSidebar',
    importPath: '@/components/admin/layout/AdminContextualSidebar',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Contextual sidebar that shows section-specific navigation links.',
    tags: ['admin', 'sidebar', 'navigation'],
  },
  {
    id: 'admin-mobile-nav',
    name: 'AdminMobileNav',
    importPath: '@/components/admin/layout/AdminMobileNav',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Mobile-specific bottom navigation for admin dashboard.',
    tags: ['admin', 'mobile', 'nav'],
  },
  {
    id: 'admin-mobile-tab-bar',
    name: 'AdminMobileTabBar',
    importPath: '@/components/admin/layout/AdminMobileTabBar',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Mobile tab bar for switching between admin sections.',
    tags: ['admin', 'mobile', 'tabs'],
  },
  {
    id: 'admin-hub-tab-bar',
    name: 'AdminHubTabBar',
    importPath: '@/components/admin/layout/AdminHubTabBar',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Tab bar for admin hub pages showing sub-section tabs.',
    tags: ['admin', 'hub', 'tabs'],
  },
  {
    id: 'admin-hub-quick-link',
    name: 'AdminHubQuickLink',
    importPath: '@/components/admin/layout/AdminHubQuickLink',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Quick link card on admin hub pages for fast navigation.',
    tags: ['admin', 'hub', 'link'],
  },
  {
    id: 'admin-hub-empty-state',
    name: 'AdminHubEmptyState',
    importPath: '@/components/admin/layout/AdminHubEmptyState',
    category: 'Layout',
    areas: ['admin'],
    tier: 'static',
    description: 'Empty state placeholder for admin hub pages with no content.',
    tags: ['admin', 'empty', 'state'],
  },
  {
    id: 'admin-error-boundary',
    name: 'AdminErrorBoundary',
    importPath: '@/components/admin/layout/AdminErrorBoundary',
    category: 'Layout',
    areas: ['admin'],
    tier: 'static',
    description: 'Error boundary component for graceful admin page error handling.',
    tags: ['admin', 'error', 'boundary'],
  },
  {
    id: 'emergency-banner',
    name: 'EmergencyBanner',
    importPath: '@/components/admin/layout/EmergencyBanner',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'High-visibility banner for critical system alerts in the admin UI.',
    tags: ['admin', 'emergency', 'banner', 'alert'],
  },

  // ─── Admin — Charts ───────────────────────────────────────────────────────

  {
    id: 'pipeline-diagram',
    name: 'PipelineDiagram',
    importPath: '@/components/admin/rag/PipelineDiagram',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Six-node flow diagram visualising the RAG retrieval pipeline.',
    tags: ['rag', 'pipeline', 'diagram', 'flow'],
    compositions: ['rag-debug'],
  },
  {
    id: 'waterfall-chart',
    name: 'WaterfallChart',
    importPath: '@/components/admin/rag/WaterfallChart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Chrome DevTools-style waterfall chart for pipeline step timing.',
    tags: ['waterfall', 'chart', 'timing', 'rag'],
    compositions: ['rag-debug'],
  },
  {
    id: 'strategy-badge',
    name: 'StrategyBadge',
    importPath: '@/components/admin/rag/StrategyBadge',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Badge labelling a RAG retrieval strategy with colour coding.',
    tags: ['strategy', 'badge', 'rag'],
  },
  {
    id: 'timeline-step',
    name: 'TimelineStep',
    importPath: '@/components/admin/rag/TimelineStep',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Expandable timeline step showing RAG pipeline phase details.',
    tags: ['timeline', 'step', 'rag'],
  },
  {
    id: 'rag-confidence-badge',
    name: 'RagConfidenceBadge',
    importPath: '@/components/admin/rag/ConfidenceBadge',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Admin-specific confidence badge with detailed score breakdown tooltip.',
    tags: ['confidence', 'badge', 'rag', 'admin'],
  },
  {
    id: 'ai-usage-donut',
    name: 'AIUsageDonut',
    importPath: '@/components/admin/charts/AIUsageDonut',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Donut chart showing AI usage breakdown by model or strategy.',
    tags: ['chart', 'donut', 'ai', 'usage'],
  },
  {
    id: 'api-requests-chart',
    name: 'APIRequestsChart',
    importPath: '@/components/admin/charts/APIRequestsChart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Line chart showing API request volume over time.',
    tags: ['chart', 'api', 'requests', 'timeline'],
  },
  {
    id: 'charts-section',
    name: 'ChartsSection',
    importPath: '@/components/admin/charts/ChartsSection',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Composed section grouping multiple admin dashboard charts.',
    tags: ['charts', 'section', 'dashboard'],
  },
  {
    id: 'usage-kpi-cards',
    name: 'UsageKpiCards',
    importPath: '@/components/admin/usage/KpiCards',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'KPI card grid for the OpenRouter usage monitoring page.',
    tags: ['kpi', 'usage', 'cards', 'monitoring'],
  },
  {
    id: 'request-timeline-chart',
    name: 'RequestTimelineChart',
    importPath: '@/components/admin/usage/RequestTimelineChart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Timeline chart for LLM request volume and latency.',
    tags: ['chart', 'requests', 'timeline'],
  },
  {
    id: 'cost-breakdown-panel',
    name: 'CostBreakdownPanel',
    importPath: '@/components/admin/usage/CostBreakdownPanel',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Panel with cost breakdown by model and time period.',
    tags: ['cost', 'breakdown', 'chart'],
  },
  {
    id: 'free-quota-indicator',
    name: 'FreeQuotaIndicator',
    importPath: '@/components/admin/usage/FreeQuotaIndicator',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Visual indicator for free-tier model quota consumption.',
    tags: ['quota', 'free', 'indicator'],
  },
  {
    id: 'rate-limit-gauge',
    name: 'RateLimitGauge',
    importPath: '@/components/admin/usage/RateLimitGauge',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Circular gauge showing current RPM usage vs. rate limit.',
    tags: ['rate-limit', 'gauge', 'rpm'],
  },
  {
    id: 'recent-requests-table',
    name: 'RecentRequestsTable',
    importPath: '@/components/admin/usage/RecentRequestsTable',
    category: 'Charts',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Table of recent LLM requests with model, tokens, cost, and latency.',
    tags: ['requests', 'table', 'llm'],
  },
  {
    id: 'agent-kpi-cards',
    name: 'AgentKpiCards',
    importPath: '@/components/admin/agents/agent-kpi-cards',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'KPI card grid for the agent monitoring overview page.',
    tags: ['agent', 'kpi', 'cards'],
  },
  {
    id: 'metrics-kpi-cards',
    name: 'MetricsKpiCards',
    importPath: '@/components/admin/agents/MetricsKpiCards',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'KPI cards showing agent metrics: total chats, avg latency, satisfaction.',
    tags: ['metrics', 'kpi', 'agent'],
  },
  {
    id: 'usage-chart',
    name: 'UsageChart',
    importPath: '@/components/admin/agents/UsageChart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Bar/line chart for agent usage volume over time.',
    tags: ['usage', 'chart', 'agent'],
  },
  {
    id: 'usage-trend-chart',
    name: 'UsageTrendChart',
    importPath: '@/components/admin/agents/usage-trend-chart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Trend line chart comparing agent usage across periods.',
    tags: ['usage', 'trend', 'chart'],
  },
  {
    id: 'cost-breakdown-chart',
    name: 'CostBreakdownChart',
    importPath: '@/components/admin/agents/CostBreakdownChart',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Stacked bar chart for LLM cost breakdown by agent.',
    tags: ['cost', 'chart', 'agent'],
  },

  // ─── Admin — Agent ────────────────────────────────────────────────────────

  {
    id: 'agent-builder-header',
    name: 'AgentBuilderHeader',
    importPath: '@/components/admin/agent-builder/AgentBuilderHeader',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Header bar for the multi-step agent builder wizard.',
    tags: ['agent', 'builder', 'header'],
  },
  {
    id: 'agent-builder-steps',
    name: 'AgentBuilderSteps',
    importPath: '@/components/admin/agent-builder/AgentBuilderSteps',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Step indicator for the agent builder wizard showing current progress.',
    tags: ['agent', 'builder', 'steps', 'wizard'],
  },
  {
    id: 'agent-preview-panel',
    name: 'AgentPreviewPanel',
    importPath: '@/components/admin/agent-builder/AgentPreviewPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Live preview panel showing agent configuration summary.',
    tags: ['agent', 'preview', 'panel'],
  },
  {
    id: 'basic-info-step',
    name: 'BasicInfoStep',
    importPath: '@/components/admin/agent-builder/BasicInfoStep',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Step 1 of agent builder: name, description, and entity type.',
    tags: ['agent', 'builder', 'form'],
  },
  {
    id: 'prompt-editor-step',
    name: 'PromptEditorStep',
    importPath: '@/components/admin/agent-builder/PromptEditorStep',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Step 2 of agent builder: system prompt editor with variable tokens.',
    tags: ['agent', 'prompt', 'editor'],
  },
  {
    id: 'review-step',
    name: 'ReviewStep',
    importPath: '@/components/admin/agent-builder/ReviewStep',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Final review step summarising agent configuration before save.',
    tags: ['agent', 'review', 'summary'],
  },
  {
    id: 'tools-strategy-step',
    name: 'ToolsStrategyStep',
    importPath: '@/components/admin/agent-builder/ToolsStrategyStep',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Step for configuring agent tools and retrieval strategy.',
    tags: ['agent', 'tools', 'strategy'],
  },
  {
    id: 'agent-builder-form',
    name: 'AgentBuilderForm',
    importPath: '@/components/admin/agent-definitions/AgentBuilderForm',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Form for creating and editing agent definitions.',
    tags: ['agent', 'definition', 'form'],
  },
  {
    id: 'builder-filters',
    name: 'BuilderFilters',
    importPath: '@/components/admin/agent-definitions/BuilderFilters',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Filter panel for the agent definitions list.',
    tags: ['agent', 'filter', 'definition'],
  },
  {
    id: 'builder-table',
    name: 'BuilderTable',
    importPath: '@/components/admin/agent-definitions/BuilderTable',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Table listing agent definitions with action columns.',
    tags: ['agent', 'table', 'definition'],
  },
  {
    id: 'agent-config-panel',
    name: 'AgentConfigPanel',
    importPath: '@/components/admin/agents/AgentConfigPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Configuration panel for editing live agent settings.',
    tags: ['agent', 'config', 'panel'],
  },
  {
    id: 'agent-mode-selector',
    name: 'AgentModeSelector',
    importPath: '@/components/admin/agents/AgentModeSelector',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Selector for agent operating mode (standard, debug, test).',
    tags: ['agent', 'mode', 'selector'],
  },
  {
    id: 'test-chat-interface',
    name: 'TestChatInterface',
    importPath: '@/components/admin/agents/TestChatInterface',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Interactive chat UI for testing agent responses in the admin.',
    tags: ['agent', 'chat', 'test'],
  },
  {
    id: 'test-metrics-display',
    name: 'TestMetricsDisplay',
    importPath: '@/components/admin/agents/TestMetricsDisplay',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Displays latency, token counts, and confidence from a test run.',
    tags: ['agent', 'metrics', 'test'],
  },
  {
    id: 'top-agents-table',
    name: 'TopAgentsTable',
    importPath: '@/components/admin/agents/TopAgentsTable',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Table ranking agents by usage, satisfaction, or cost.',
    tags: ['agent', 'table', 'ranking'],
  },
  {
    id: 'comparison-panel',
    name: 'ComparisonPanel',
    importPath: '@/components/admin/agents/ComparisonPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Side-by-side agent comparison panel for A/B analysis.',
    tags: ['agent', 'comparison', 'ab'],
  },
  {
    id: 'phase-model-configuration',
    name: 'PhaseModelConfiguration',
    importPath: '@/components/admin/agent-typologies/PhaseModelConfiguration',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'UI for mapping LLM models to agent pipeline phases.',
    tags: ['agent', 'model', 'phase', 'configuration'],
  },
  {
    id: 'typology-form',
    name: 'TypologyForm',
    importPath: '@/components/admin/agent-typologies/TypologyForm',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Form for creating and editing agent typology definitions.',
    tags: ['agent', 'typology', 'form'],
  },
  {
    id: 'typology-prompt-editor',
    name: 'TypologyPromptEditor',
    importPath: '@/components/admin/agent-typologies/TypologyPromptEditor',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Rich prompt editor for agent typology system prompts.',
    tags: ['agent', 'prompt', 'typology'],
  },

  // ─── Admin — Sandbox ──────────────────────────────────────────────────────

  {
    id: 'sandbox-chat',
    name: 'SandboxChat',
    importPath: '@/components/admin/sandbox/SandboxChat',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Live chat interface inside the RAG sandbox for agent testing.',
    tags: ['sandbox', 'chat', 'rag', 'test'],
    compositions: ['rag-debug'],
  },
  {
    id: 'sandbox-agent-config-panel',
    name: 'SandboxAgentConfigPanel',
    importPath: '@/components/admin/sandbox/AgentConfigPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Configuration panel for adjusting agent settings inside the sandbox.',
    tags: ['sandbox', 'agent', 'config'],
  },
  {
    id: 'pipeline-panel',
    name: 'PipelinePanel',
    importPath: '@/components/admin/sandbox/PipelinePanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Panel showing live RAG pipeline trace during a sandbox query.',
    tags: ['pipeline', 'panel', 'trace'],
  },
  {
    id: 'pipeline-step-card',
    name: 'PipelineStepCard',
    importPath: '@/components/admin/sandbox/PipelineStepCard',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Card displaying details for a single RAG pipeline step.',
    tags: ['pipeline', 'step', 'card'],
  },
  {
    id: 'pipeline-trace-tree',
    name: 'PipelineTraceTree',
    importPath: '@/components/admin/sandbox/PipelineTraceTree',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Tree view of the full pipeline trace hierarchy.',
    tags: ['pipeline', 'trace', 'tree'],
  },
  {
    id: 'retrieved-chunk-card',
    name: 'RetrievedChunkCard',
    importPath: '@/components/admin/sandbox/RetrievedChunkCard',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Card showing a retrieved document chunk with score and metadata.',
    tags: ['rag', 'chunk', 'retrieval'],
  },
  {
    id: 'pipeline-deep-metrics',
    name: 'PipelineDeepMetrics',
    importPath: '@/components/admin/sandbox/PipelineDeepMetrics',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Deep metrics panel for the RAG pipeline showing precision and recall.',
    tags: ['pipeline', 'metrics', 'deep'],
  },
  {
    id: 'debug-side-panel',
    name: 'DebugSidePanel',
    importPath: '@/components/admin/sandbox/DebugSidePanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Debug side panel surfacing raw pipeline state during sandbox sessions.',
    tags: ['debug', 'panel', 'sandbox'],
  },
  {
    id: 'auto-test-runner',
    name: 'AutoTestRunner',
    importPath: '@/components/admin/sandbox/AutoTestRunner',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Automated test runner that executes a suite of agent queries.',
    tags: ['test', 'runner', 'auto', 'agent'],
  },
  {
    id: 'auto-test-summary',
    name: 'AutoTestSummary',
    importPath: '@/components/admin/sandbox/AutoTestSummary',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Summary view for auto test run results with pass/fail breakdown.',
    tags: ['test', 'summary', 'auto'],
  },

  // ─── Admin — Debug Chat ───────────────────────────────────────────────────

  {
    id: 'debug-cost-badge',
    name: 'DebugCostBadge',
    importPath: '@/components/admin/debug-chat/DebugCostBadge',
    category: 'Agent',
    areas: ['admin'],
    tier: 'static',
    description: 'Badge showing token cost for a debug chat request.',
    tags: ['debug', 'cost', 'badge', 'token'],
  },
  {
    id: 'debug-event-card',
    name: 'DebugEventCard',
    importPath: '@/components/admin/debug-chat/DebugEventCard',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Card showing an individual SSE event during a debug chat session.',
    tags: ['debug', 'event', 'card', 'sse'],
  },
  {
    id: 'debug-timeline',
    name: 'DebugTimeline',
    importPath: '@/components/admin/debug-chat/DebugTimeline',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Chronological timeline of events during a debug chat session.',
    tags: ['debug', 'timeline', 'chat'],
  },
  {
    id: 'strategy-selector-bar',
    name: 'StrategySelectorBar',
    importPath: '@/components/admin/debug-chat/StrategySelectorBar',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Tab bar for selecting which RAG strategy to test in debug mode.',
    tags: ['strategy', 'selector', 'debug'],
  },

  // ─── Admin — Knowledge Base ───────────────────────────────────────────────

  {
    id: 'kb-settings',
    name: 'KbSettings',
    importPath: '@/components/admin/knowledge-base/kb-settings',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Settings form for knowledge base configuration.',
    tags: ['knowledge-base', 'settings', 'config'],
  },
  {
    id: 'processing-metrics',
    name: 'ProcessingMetrics',
    importPath: '@/components/admin/knowledge-base/processing-metrics',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Metrics panel showing document processing throughput and error rate.',
    tags: ['processing', 'metrics', 'knowledge-base'],
  },
  {
    id: 'processing-queue',
    name: 'ProcessingQueue',
    importPath: '@/components/admin/knowledge-base/processing-queue',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Live queue of documents pending or in-progress processing.',
    tags: ['queue', 'processing', 'knowledge-base'],
  },
  {
    id: 'rag-pipeline-flow',
    name: 'RagPipelineFlow',
    importPath: '@/components/admin/knowledge-base/rag-pipeline-flow',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Visual flow diagram of the RAG ingestion and retrieval pipeline.',
    tags: ['rag', 'pipeline', 'flow', 'knowledge-base'],
  },
  {
    id: 'upload-settings',
    name: 'UploadSettings',
    importPath: '@/components/admin/knowledge-base/upload-settings',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Settings panel for document upload configuration (chunking, OCR).',
    tags: ['upload', 'settings', 'knowledge-base'],
  },
  {
    id: 'upload-zone',
    name: 'UploadZone',
    importPath: '@/components/admin/knowledge-base/upload-zone',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Drag-and-drop upload zone for adding documents to the knowledge base.',
    tags: ['upload', 'drag-drop', 'knowledge-base'],
  },
  {
    id: 'vector-collection-card',
    name: 'VectorCollectionCard',
    importPath: '@/components/admin/knowledge-base/vector-collection-card',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Card showing a Qdrant vector collection with point count and actions.',
    tags: ['vector', 'collection', 'qdrant'],
  },

  // ─── Admin — Shared Games ─────────────────────────────────────────────────

  {
    id: 'admin-shared-game-card-container',
    name: 'AdminSharedGameCardContainer',
    importPath: '@/components/admin/shared-games/AdminSharedGameCardContainer',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Container wiring admin-specific actions to the shared game card.',
    tags: ['game', 'card', 'admin'],
  },
  {
    id: 'agent-builder-modal',
    name: 'AgentBuilderModal',
    importPath: '@/components/admin/shared-games/AgentBuilderModal',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Modal for configuring an agent linked to a shared game.',
    tags: ['agent', 'modal', 'game'],
  },
  {
    id: 'bgg-search-panel',
    name: 'BggSearchPanel',
    importPath: '@/components/admin/shared-games/BggSearchPanel',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Search panel for looking up games on BoardGameGeek.',
    tags: ['bgg', 'search', 'game'],
  },
  {
    id: 'game-catalog-grid',
    name: 'GameCatalogGrid',
    importPath: '@/components/admin/shared-games/game-catalog-grid',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Grid layout for the shared game catalog with filter integration.',
    tags: ['game', 'catalog', 'grid'],
  },
  {
    id: 'game-form',
    name: 'GameForm',
    importPath: '@/components/admin/shared-games/GameForm',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Form for creating and editing shared game catalog entries.',
    tags: ['game', 'form', 'edit'],
  },
  {
    id: 'game-status-badge',
    name: 'GameStatusBadge',
    importPath: '@/components/admin/shared-games/GameStatusBadge',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Badge showing game approval status (pending, approved, rejected).',
    tags: ['game', 'status', 'badge'],
  },
  {
    id: 'pdf-document-list',
    name: 'PdfDocumentList',
    importPath: '@/components/admin/shared-games/PdfDocumentList',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'List of PDF documents associated with a shared game.',
    tags: ['pdf', 'document', 'list'],
  },
  {
    id: 'pdf-indexing-status',
    name: 'PdfIndexingStatus',
    importPath: '@/components/admin/shared-games/PdfIndexingStatus',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Status indicator for PDF indexing into the vector database.',
    tags: ['pdf', 'indexing', 'status'],
  },
  {
    id: 'pdf-upload-section',
    name: 'PdfUploadSection',
    importPath: '@/components/admin/shared-games/PdfUploadSection',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Section for uploading PDF rulebooks to a shared game with XHR progress.',
    tags: ['pdf', 'upload', 'game'],
  },
  {
    id: 'rag-readiness-indicator',
    name: 'RagReadinessIndicator',
    importPath: '@/components/admin/shared-games/rag-setup/RagReadinessIndicator',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Step-by-step readiness indicator for RAG setup on a shared game.',
    tags: ['rag', 'readiness', 'game'],
  },
  {
    id: 'inline-chat-panel',
    name: 'InlineChatPanel',
    importPath: '@/components/admin/shared-games/rag-setup/InlineChatPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Inline chat panel for testing RAG setup on a shared game.',
    tags: ['chat', 'rag', 'test', 'inline'],
  },
  {
    id: 'agent-setup-panel',
    name: 'AgentSetupPanel',
    importPath: '@/components/admin/shared-games/rag-setup/AgentSetupPanel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Panel guiding admin through linking an agent to a shared game.',
    tags: ['agent', 'setup', 'panel', 'game'],
  },

  // ─── Admin — Users ────────────────────────────────────────────────────────

  {
    id: 'permissions-matrix',
    name: 'PermissionsMatrix',
    importPath: '@/components/admin/users/permissions-matrix',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Matrix UI showing role-to-permission assignments.',
    tags: ['permissions', 'matrix', 'roles'],
  },
  {
    id: 'inline-role-select',
    name: 'InlineRoleSelect',
    importPath: '@/components/admin/users/InlineRoleSelect',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Inline select dropdown for changing a user role in a table.',
    tags: ['role', 'select', 'user'],
  },
  {
    id: 'role-card',
    name: 'RoleCard',
    importPath: '@/components/admin/users/role-card',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Card summarising a user role with description and permission count.',
    tags: ['role', 'card', 'user'],
  },
  {
    id: 'user-activity-table',
    name: 'UserActivityTable',
    importPath: '@/components/admin/users/activity-table',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Table of user activity events with timestamp and action columns.',
    tags: ['user', 'activity', 'table'],
  },
  {
    id: 'user-activity-filters',
    name: 'UserActivityFilters',
    importPath: '@/components/admin/users/activity-filters',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Filter controls for the user activity table.',
    tags: ['user', 'activity', 'filter'],
  },

  // ─── Admin — Alert Rules ──────────────────────────────────────────────────

  {
    id: 'alert-rule-form',
    name: 'AlertRuleForm',
    importPath: '@/components/admin/alert-rules/AlertRuleForm',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Form for creating and editing monitoring alert rules.',
    tags: ['alert', 'rule', 'form', 'monitoring'],
  },
  {
    id: 'alert-rule-list',
    name: 'AlertRuleList',
    importPath: '@/components/admin/alert-rules/AlertRuleList',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'List of configured alert rules with enable/disable toggles.',
    tags: ['alert', 'rule', 'list'],
  },
  {
    id: 'alert-template-gallery',
    name: 'AlertTemplateGallery',
    importPath: '@/components/admin/alert-rules/AlertTemplateGallery',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Gallery of pre-built alert rule templates for quick setup.',
    tags: ['alert', 'template', 'gallery'],
  },

  // ─── Admin — Notifications ────────────────────────────────────────────────

  {
    id: 'channel-selector',
    name: 'ChannelSelector',
    importPath: '@/components/admin/notifications/ChannelSelector',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Multi-select for choosing notification delivery channels.',
    tags: ['notifications', 'channel', 'select'],
  },
  {
    id: 'notification-preview',
    name: 'NotificationPreview',
    importPath: '@/components/admin/notifications/NotificationPreview',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'static',
    description: 'Preview of how a notification will appear to recipients.',
    tags: ['notification', 'preview'],
  },
  {
    id: 'recipient-selector',
    name: 'RecipientSelector',
    importPath: '@/components/admin/notifications/RecipientSelector',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Search and select UI for notification recipients.',
    tags: ['notifications', 'recipient', 'select'],
  },

  // ─── Admin — Invitations ──────────────────────────────────────────────────

  {
    id: 'bulk-invite-dialog',
    name: 'BulkInviteDialog',
    importPath: '@/components/admin/invitations/BulkInviteDialog',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Dialog for sending bulk invitations via CSV email list.',
    tags: ['invitation', 'bulk', 'dialog'],
  },
  {
    id: 'invitation-row',
    name: 'InvitationRow',
    importPath: '@/components/admin/invitations/InvitationRow',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Table row for an invitation with status, expiry, and resend actions.',
    tags: ['invitation', 'row', 'table'],
  },
  {
    id: 'invitation-status-badge',
    name: 'InvitationStatusBadge',
    importPath: '@/components/admin/invitations/InvitationStatusBadge',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Badge showing invitation status (pending, accepted, expired).',
    tags: ['invitation', 'status', 'badge'],
  },
  {
    id: 'invite-user-dialog',
    name: 'InviteUserDialog',
    importPath: '@/components/admin/invitations/InviteUserDialog',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Dialog for inviting a single user by email.',
    tags: ['invitation', 'user', 'dialog'],
  },

  // ─── Admin — Strategies ───────────────────────────────────────────────────

  {
    id: 'strategy-editor',
    name: 'StrategyEditor',
    importPath: '@/components/admin/strategies/StrategyEditor',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Editor for configuring RAG strategy parameters and model mappings.',
    tags: ['strategy', 'editor', 'rag'],
  },

  // ─── Admin — Overview ─────────────────────────────────────────────────────

  {
    id: 'quick-actions-widget',
    name: 'QuickActionsWidget',
    importPath: '@/components/admin/overview/QuickActionsWidget',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Widget with shortcut buttons for frequent admin actions.',
    tags: ['admin', 'overview', 'quick-actions'],
  },
  {
    id: 'system-health-card',
    name: 'SystemHealthCard',
    importPath: '@/components/admin/overview/SystemHealthCard',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Card summarising overall system health with service statuses.',
    tags: ['system', 'health', 'card', 'admin'],
  },

  // ─── Admin — Command Center ───────────────────────────────────────────────

  {
    id: 'command-center-dashboard',
    name: 'CommandCenterDashboard',
    importPath: '@/components/admin/command-center/CommandCenterDashboard',
    category: 'Layout',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Full-page command centre dashboard composing all system monitoring panels.',
    tags: ['command', 'center', 'dashboard', 'admin'],
  },

  // ─── Admin — Games ────────────────────────────────────────────────────────

  {
    id: 'admin-game-wizard',
    name: 'AdminGameWizard',
    importPath: '@/components/admin/games/wizard/AdminGameWizard',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Multi-step wizard for adding a new game to the catalog.',
    tags: ['game', 'wizard', 'admin'],
  },
  {
    id: 'processing-monitor',
    name: 'ProcessingMonitor',
    importPath: '@/components/admin/games/processing/ProcessingMonitor',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Live monitor for game PDF processing jobs.',
    tags: ['processing', 'monitor', 'game'],
  },
  {
    id: 'duplicate-warning-dialog',
    name: 'DuplicateWarningDialog',
    importPath: '@/components/admin/games/import/DuplicateWarningDialog',
    category: 'Overlays',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Warning dialog shown when an imported game may be a duplicate.',
    tags: ['duplicate', 'warning', 'import', 'game'],
  },

  // ─── Admin — Playground ───────────────────────────────────────────────────

  {
    id: 'budget-debug-panel',
    name: 'BudgetDebugPanel',
    importPath: '@/components/admin/playground/budget-debug-panel',
    category: 'Agent',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Debug panel for simulating budget alerts and circuit-breaker triggers.',
    tags: ['budget', 'debug', 'playground'],
  },

  // ─── Admin — Misc ─────────────────────────────────────────────────────────

  {
    id: 'kpi-card',
    name: 'KPICard',
    importPath: '@/components/admin/KPICard',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Single KPI card with metric value, label, and trend delta.',
    tags: ['kpi', 'card', 'metric'],
  },
  {
    id: 'kpi-cards-grid',
    name: 'KPICardsGrid',
    importPath: '@/components/admin/KPICardsGrid',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Responsive grid layout composing multiple KPICard components.',
    tags: ['kpi', 'grid', 'cards'],
  },
  {
    id: 'admin-stat-card',
    name: 'AdminStatCard',
    importPath: '@/components/admin/StatCard',
    category: 'Charts',
    areas: ['admin'],
    tier: 'static',
    description: 'Admin-styled stat card with icon and colour accent.',
    tags: ['stat', 'card', 'admin'],
  },
  {
    id: 'activity-feed',
    name: 'ActivityFeed',
    importPath: '@/components/admin/ActivityFeed',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Real-time activity feed for admin overview showing recent events.',
    tags: ['activity', 'feed', 'realtime', 'admin'],
  },
  {
    id: 'activity-timeline',
    name: 'ActivityTimeline',
    importPath: '@/components/admin/ActivityTimeline',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Vertical timeline of admin activity events with icons.',
    tags: ['activity', 'timeline', 'admin'],
  },
  {
    id: 'alerts-banner',
    name: 'AlertsBanner',
    importPath: '@/components/admin/AlertsBanner',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'static',
    description: 'Dismissible banner listing active system alerts.',
    tags: ['alerts', 'banner', 'admin'],
  },
  {
    id: 'budget-alert-banner',
    name: 'BudgetAlertBanner',
    importPath: '@/components/admin/BudgetAlertBanner',
    category: 'Feedback',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Banner warning when OpenRouter budget thresholds are breached.',
    tags: ['budget', 'alert', 'banner'],
  },
  {
    id: 'bulk-action-bar',
    name: 'BulkActionBar',
    importPath: '@/components/admin/BulkActionBar',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Sticky action bar appearing when rows are selected in admin tables.',
    tags: ['bulk', 'action', 'bar', 'selection'],
  },
  {
    id: 'bulk-actions-toolbar',
    name: 'BulkActionsToolbar',
    importPath: '@/components/admin/bulk-actions-toolbar',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Toolbar with bulk-operation buttons for multi-row table selections.',
    tags: ['bulk', 'toolbar', 'actions'],
  },
  {
    id: 'service-health-matrix',
    name: 'ServiceHealthMatrix',
    importPath: '@/components/admin/ServiceHealthMatrix',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'static',
    description: 'Matrix showing health status for all microservices.',
    tags: ['service', 'health', 'matrix'],
  },
  {
    id: 'ai-models-table',
    name: 'AiModelsTable',
    importPath: '@/components/admin/AiModelsTable',
    category: 'Data Display',
    areas: ['admin'],
    tier: 'interactive',
    description: 'Table listing configured AI models with health and usage columns.',
    tags: ['ai', 'models', 'table'],
  },
];

// ─── Helper Functions ───────────────────────────────────────────────────────

export function getRegistryEntry(id: string): ComponentEntry | undefined {
  return COMPONENT_REGISTRY.find(e => e.id === id);
}

export function filterRegistry(filters: {
  category?: ComponentCategory;
  area?: AppArea;
  tier?: 'interactive' | 'static';
  search?: string;
}): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(entry => {
    if (filters.category && entry.category !== filters.category) return false;
    if (filters.area && !entry.areas.includes(filters.area)) return false;
    if (filters.tier && entry.tier !== filters.tier) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      return (
        entry.name.toLowerCase().includes(q) ||
        entry.description.toLowerCase().includes(q) ||
        (entry.tags?.some(t => t.includes(q)) ?? false)
      );
    }
    return true;
  });
}

export function getCategories(): { category: ComponentCategory; count: number }[] {
  const counts = new Map<ComponentCategory, number>();
  for (const entry of COMPONENT_REGISTRY) {
    counts.set(entry.category, (counts.get(entry.category) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count);
}

export function getAreas(): { area: AppArea; count: number }[] {
  const counts = new Map<AppArea, number>();
  for (const entry of COMPONENT_REGISTRY) {
    for (const area of entry.areas) {
      counts.set(area, (counts.get(area) ?? 0) + 1);
    }
  }
  return Array.from(counts.entries())
    .map(([area, count]) => ({ area, count }))
    .sort((a, b) => b.count - a.count);
}
