"""CLI: scans admin-mockups/design_files/, applies rule engine, emits nav-map.md.

Usage:
  python -m scripts.mockup_demo.build_map [--out PATH]

Output columns: File | Selector | Button text | Destination | Confidence | Rule
"""
from __future__ import annotations
from pathlib import Path
import argparse
import sys

from scripts.mockup_demo.clickable_extractor import extract_clickables
from scripts.mockup_demo.rule_engine import resolve_destination

REPO_ROOT = Path(__file__).resolve().parents[2]
MOCKUPS_DIR = REPO_ROOT / "admin-mockups" / "design_files"
DEFAULT_OUT = REPO_ROOT / "docs" / "superpowers" / "specs" / "nav-map.md"


def _selector(click) -> str:
    """Stable identifier: tag + first 30 chars of text for locating later."""
    return f"{click.tag}:L{click.line_number}:{click.text[:30].strip()}"


def build_map(mockups_dir: Path, out_path: Path) -> int:
    rows = []
    files = sorted(list(mockups_dir.glob("*.html")) + list(mockups_dir.glob("*.jsx")))
    for f in files:
        for click in extract_clickables(f):
            decision = resolve_destination(click)
            rows.append((f.name, click, decision))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("# Mockup Demo Navigation Map\n\n")
        out.write(f"Generated by `scripts/mockup_demo/build_map.py`. "
                  f"Edit destinations in the 'TODO / Ambiguous' section below; "
                  f"do not edit auto-rules unless overriding.\n\n")
        out.write(f"**Total clickables:** {len(rows)}\n\n")
        # Group by file
        by_file: dict[str, list] = {}
        for fname, click, dec in rows:
            by_file.setdefault(fname, []).append((click, dec))

        # Section 1: auto-resolved rows
        out.write("## Auto-resolved\n\n")
        out.write("| File | Selector | Button text | Destination | Confidence | Rule |\n")
        out.write("|---|---|---|---|---|---|\n")
        for fname in sorted(by_file):
            for click, dec in by_file[fname]:
                if dec.destination:
                    text_safe = (click.text or "")[:40].replace("|", "\\|")
                    out.write(
                        f"| `{fname}` | `{_selector(click)}` "
                        f"| {text_safe} | `{dec.destination}` "
                        f"| {dec.confidence:.2f} | {dec.rule} |\n"
                    )

        # Section 2: TODO / Ambiguous
        out.write("\n## TODO / Ambiguous\n\n")
        out.write("Fill in the Destination column. Use `OUT_OF_SCOPE` to apply no-op policy.\n\n")
        out.write("| File | Selector | Button text | Destination | Rationale |\n")
        out.write("|---|---|---|---|---|\n")
        for fname in sorted(by_file):
            for click, dec in by_file[fname]:
                if not dec.destination:
                    text_safe = (click.text or "")[:40].replace("|", "\\|")
                    out.write(
                        f"| `{fname}` | `{_selector(click)}` "
                        f"| {text_safe} | `TODO` | {dec.rationale} |\n"
                    )
    return len(rows)


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--mockups-dir", type=Path, default=MOCKUPS_DIR)
    args = p.parse_args(argv)
    n = build_map(args.mockups_dir, args.out)
    print(f"Wrote {args.out} ({n} clickables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
