/**
 * @mockup admin-mockups/design_files/sp4-discover.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
'use client';

import { Suspense } from 'react';

import { DiscoverHub } from '@/components/features/discover/DiscoverHub';
import { useMiniNavConfig } from '@/hooks/useMiniNavConfig';
import { useTranslation } from '@/hooks/useTranslation';

/**
 * `/discover` — standalone Discover route. Preserved for backward compat
 * (existing bookmarks + cross-links) after Asse D follow-up P2 (#1899) moved
 * the canonical Discover surface to `/games?tab=discover`.
 *
 * The Discover content itself lives in `DiscoverHub`
 * (`components/features/discover/DiscoverHub.tsx`); this route only wires the
 * route-level mini-nav (breadcrumb + single tab) and the Suspense boundary
 * required by `useSearchParams()` in App Router.
 */
function DiscoverPageInner() {
  const { t } = useTranslation();

  useMiniNavConfig({
    breadcrumb: t('pages.discover.miniNav.breadcrumb'),
    tabs: [{ id: 'all', label: t('pages.discover.miniNav.tabAll'), href: '/discover' }],
    activeTabId: 'all',
  });

  return <DiscoverHub />;
}

/**
 * Default export wraps the discover content in a Suspense boundary.
 * Required by Next.js App Router because `useSearchParams()` opts the page
 * out of SSR static prerendering; without Suspense, the build emits a
 * "should be wrapped in a suspense boundary" CSR bailout error.
 */
export default function DiscoverPage() {
  return (
    <Suspense fallback={null}>
      <DiscoverPageInner />
    </Suspense>
  );
}
