using Api.BoundedContexts.GameManagement.Application.Commands.SessionSnapshot;
using Api.BoundedContexts.GameManagement.Domain.Entities.SessionSnapshot;
using Api.BoundedContexts.GameManagement.Domain.Events;
using Api.BoundedContexts.GameManagement.Domain.Repositories;
using Api.SharedKernel.Infrastructure.Persistence;
using MediatR;

namespace Api.BoundedContexts.GameManagement.Application.EventHandlers;

/// <summary>
/// Automatically creates a snapshot when a live session is paused.
/// Enforces a maximum of 20 auto-generated snapshots per session.
/// Issue #5581: Auto-snapshot on Pause + snapshot history.
/// </summary>
internal sealed class SessionPausedAutoSnapshotHandler
    : INotificationHandler<LiveSessionPausedEvent>
{
    private const int MaxAutoSnapshotsPerSession = 20;

    private readonly ILiveSessionRepository _sessionRepository;
    private readonly ISessionSnapshotRepository _snapshotRepository;
    private readonly IMediator _mediator;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<SessionPausedAutoSnapshotHandler> _logger;

    public SessionPausedAutoSnapshotHandler(
        ILiveSessionRepository sessionRepository,
        ISessionSnapshotRepository snapshotRepository,
        IMediator mediator,
        IUnitOfWork unitOfWork,
        ILogger<SessionPausedAutoSnapshotHandler> logger)
    {
        _sessionRepository = sessionRepository ?? throw new ArgumentNullException(nameof(sessionRepository));
        _snapshotRepository = snapshotRepository ?? throw new ArgumentNullException(nameof(snapshotRepository));
        _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task Handle(LiveSessionPausedEvent notification, CancellationToken cancellationToken)
    {
        try
        {
            var session = await _sessionRepository.GetByIdAsync(notification.SessionId, cancellationToken)
                .ConfigureAwait(false);

            if (session == null)
            {
                _logger.LogWarning(
                    "Session {SessionId} not found when creating auto-snapshot on pause",
                    notification.SessionId);
                return;
            }

            var turnNumber = session.CurrentTurnIndex;
            var label = $"Auto \u2014 Pausa turno {turnNumber}";

            // Create snapshot via existing CQRS command
            await _mediator.Send(new CreateSnapshotCommand(
                notification.SessionId,
                SnapshotTrigger.SessionPaused,
                label,
                CreatedByPlayerId: null), cancellationToken).ConfigureAwait(false);

            // Cleanup: enforce max auto-generated snapshots per session
            var autoCount = await _snapshotRepository.CountAutoGeneratedBySessionIdAsync(
                notification.SessionId, cancellationToken).ConfigureAwait(false);

            if (autoCount > MaxAutoSnapshotsPerSession)
            {
                await _snapshotRepository.DeleteOldestAutoGeneratedAsync(
                    notification.SessionId, MaxAutoSnapshotsPerSession, cancellationToken)
                    .ConfigureAwait(false);

                await _unitOfWork.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
            }

            _logger.LogInformation(
                "Auto-snapshot created for session {SessionId} on pause at turn {Turn}",
                notification.SessionId, turnNumber);
        }
#pragma warning disable CA1031
        catch (Exception ex)
        {
            // Log but don't throw — snapshot failure shouldn't block pause operation
            _logger.LogError(
                ex,
                "Failed to create auto-snapshot for session {SessionId} on pause. Error: {Message}",
                notification.SessionId,
                ex.Message);
        }
#pragma warning restore CA1031
    }
}
