/**
 * @mockup admin-mockups/design_files/auth-flow.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Login Page (AUTH-05) - App Router
 *
 * Standalone login page with session expiration handling.
 * Uses AuthLayout wrapper for consistent auth page UX (Issue #2231).
 *
 * Note (FE-IMP-005): Client-side only - AuthModal uses TanStack Query
 */

import { Suspense } from 'react';

import { LoginFallback, LoginPageContent } from './_content';

export default function LoginPage() {
  return (
    <Suspense fallback={<LoginFallback />}>
      <LoginPageContent />
    </Suspense>
  );
}
