/**
 * @mockup admin-mockups/design_files/auth-flow.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Login Page (AUTH-05) - App Router
 *
 * Standalone login page with session expiration handling.
 * Uses AuthLayout wrapper for consistent auth page UX (Issue #2231).
 *
 * #2650: this Server Component reads searchParams (async in Next 16) and passes
 * `from`/`reason` down as props, so the client LoginPageContent renders WITHOUT
 * `useSearchParams` — the email form is server-rendered (no <Suspense> fallback,
 * no client-only hydration gate). Fixes the flaky staging E2E "Auth login form
 * visibile" and removes the loading flash before the form.
 */

import { LoginPageContent } from './_content';

export default async function LoginPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const params = await searchParams;
  const fromParam = typeof params.from === 'string' ? params.from : undefined;
  const reason = typeof params.reason === 'string' ? params.reason : undefined;

  return <LoginPageContent fromParam={fromParam} reason={reason} />;
}
