/**
 * @mockup admin-mockups/design_files/auth-flow.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Register Page - App Router
 *
 * Standalone registration page with AuthModal.
 * Uses AuthLayout wrapper for consistent auth page UX (Issue #2231).
 */

import { Suspense } from 'react';

import { RegisterFallback, RegisterPageContent } from './_content';

export default function RegisterPage() {
  return (
    <Suspense fallback={<RegisterFallback />}>
      <RegisterPageContent />
    </Suspense>
  );
}
