CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE agent_feedback (
        "Id" uuid NOT NULL,
        "MessageId" uuid NOT NULL,
        "Endpoint" character varying(32) NOT NULL,
        "GameId" uuid,
        "UserId" uuid NOT NULL,
        "Outcome" character varying(32) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_agent_feedback" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE ai_request_logs (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "ApiKeyId" uuid,
        "GameId" uuid,
        "Endpoint" character varying(32) NOT NULL,
        "Query" character varying(2048),
        "ResponseSnippet" character varying(1024),
        "LatencyMs" integer NOT NULL,
        "TokenCount" integer NOT NULL DEFAULT 0,
        "PromptTokens" integer NOT NULL DEFAULT 0,
        "CompletionTokens" integer NOT NULL DEFAULT 0,
        "Confidence" double precision,
        "Status" character varying(32) NOT NULL,
        "ErrorMessage" character varying(1024),
        "IpAddress" character varying(64),
        "UserAgent" character varying(256),
        "Model" character varying(128),
        "FinishReason" character varying(64),
        "CreatedAt" timestamp with time zone NOT NULL,
        "RagConfidence" double precision,
        "LlmConfidence" double precision,
        "CitationQuality" double precision,
        "OverallConfidence" double precision,
        "IsLowQuality" boolean NOT NULL,
        CONSTRAINT "PK_ai_request_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE alerts (
        id uuid NOT NULL,
        alert_type character varying(50) NOT NULL,
        severity character varying(20) NOT NULL,
        message text NOT NULL,
        metadata jsonb,
        triggered_at timestamp with time zone NOT NULL,
        resolved_at timestamp with time zone,
        is_active boolean NOT NULL,
        channel_sent jsonb,
        CONSTRAINT "PK_alerts" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE audit_logs (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "Action" character varying(64) NOT NULL,
        "Resource" character varying(128) NOT NULL,
        "ResourceId" character varying(64),
        "Result" character varying(32) NOT NULL,
        "Details" character varying(1024),
        "IpAddress" character varying(64),
        "UserAgent" character varying(256),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE cache_stats (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        game_id uuid NOT NULL,
        question_hash character varying(64) NOT NULL,
        hit_count bigint NOT NULL,
        miss_count bigint NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_hit_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cache_stats" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE games (
        "Id" uuid NOT NULL,
        "Name" character varying(128) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Publisher" text,
        "YearPublished" integer,
        "MinPlayers" integer,
        "MaxPlayers" integer,
        "MinPlayTimeMinutes" integer,
        "MaxPlayTimeMinutes" integer,
        "BggId" integer,
        "BggMetadata" text,
        CONSTRAINT "PK_games" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE prompt_evaluation_results (
        id uuid NOT NULL,
        template_id uuid NOT NULL,
        version_id uuid NOT NULL,
        dataset_id character varying(100) NOT NULL,
        executed_at timestamp with time zone NOT NULL,
        total_queries integer NOT NULL,
        accuracy double precision NOT NULL,
        hallucination_rate double precision NOT NULL,
        avg_confidence double precision NOT NULL,
        citation_correctness double precision NOT NULL,
        avg_latency_ms double precision NOT NULL,
        passed boolean NOT NULL,
        summary character varying(500),
        query_results_json jsonb,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_prompt_evaluation_results" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE users (
        "Id" uuid NOT NULL,
        "Email" character varying(256) NOT NULL,
        "DisplayName" character varying(128),
        "PasswordHash" text,
        "Role" character varying(32) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "TotpSecretEncrypted" character varying(512),
        "IsTwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
        "TwoFactorEnabledAt" timestamp with time zone,
        CONSTRAINT "PK_users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE workflow_error_logs (
        id uuid NOT NULL,
        workflow_id character varying(255) NOT NULL,
        execution_id character varying(255) NOT NULL,
        error_message character varying(5000) NOT NULL,
        node_name character varying(255),
        retry_count integer NOT NULL DEFAULT 0,
        stack_trace character varying(10000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_workflow_error_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE agents (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "StrategyName" character varying(100) NOT NULL,
        "StrategyParametersJson" jsonb NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastInvokedAt" timestamp with time zone,
        "InvocationCount" integer NOT NULL DEFAULT 0,
        "GameId" uuid,
        "Kind" character varying(50),
        "GameEntityId" uuid,
        CONSTRAINT "PK_agents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_agents_games_GameEntityId" FOREIGN KEY ("GameEntityId") REFERENCES games ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE "GameSessions" (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "Status" character varying(32) NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "WinnerName" character varying(256),
        "Notes" character varying(2000),
        "PlayersJson" text NOT NULL DEFAULT '[]',
        CONSTRAINT "PK_GameSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GameSessions_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE api_keys (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "KeyName" character varying(128) NOT NULL,
        "KeyHash" character varying(256) NOT NULL,
        "KeyPrefix" character varying(16) NOT NULL,
        "Scopes" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastUsedAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "RevokedBy" uuid,
        "Metadata" character varying(4096),
        CONSTRAINT "PK_api_keys" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_api_keys_users_RevokedBy" FOREIGN KEY ("RevokedBy") REFERENCES users ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_api_keys_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE "ChatThreads" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "GameId" uuid,
        "Title" text,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastMessageAt" timestamp with time zone NOT NULL,
        "MessagesJson" text NOT NULL,
        CONSTRAINT "PK_ChatThreads" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatThreads_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id"),
        CONSTRAINT "FK_ChatThreads_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE llm_cost_logs (
        id uuid NOT NULL,
        user_id uuid,
        user_role character varying(50) NOT NULL,
        model_id character varying(100) NOT NULL,
        provider character varying(50) NOT NULL,
        prompt_tokens integer NOT NULL,
        completion_tokens integer NOT NULL,
        total_tokens integer NOT NULL,
        input_cost_usd numeric(18,6) NOT NULL,
        output_cost_usd numeric(18,6) NOT NULL,
        total_cost_usd numeric(18,6) NOT NULL,
        endpoint character varying(100) NOT NULL,
        success boolean NOT NULL,
        error_message character varying(500),
        latency_ms integer NOT NULL,
        ip_address character varying(45),
        user_agent character varying(500),
        created_at timestamp with time zone NOT NULL,
        request_date date NOT NULL,
        CONSTRAINT "PK_llm_cost_logs" PRIMARY KEY (id),
        CONSTRAINT "FK_llm_cost_logs_users_user_id" FOREIGN KEY (user_id) REFERENCES users ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE n8n_configs (
        "Id" uuid NOT NULL,
        "Name" character varying(128) NOT NULL,
        "BaseUrl" character varying(512) NOT NULL,
        "ApiKeyEncrypted" character varying(512) NOT NULL,
        "WebhookUrl" character varying(512),
        "IsActive" boolean NOT NULL,
        "LastTestedAt" timestamp with time zone,
        "LastTestResult" character varying(512),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        CONSTRAINT "PK_n8n_configs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_n8n_configs_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE oauth_accounts (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Provider" character varying(20) NOT NULL,
        "ProviderUserId" character varying(255) NOT NULL,
        "AccessTokenEncrypted" text NOT NULL,
        "RefreshTokenEncrypted" text,
        "TokenExpiresAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_oauth_accounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_oauth_accounts_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE password_reset_tokens (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" character varying(256) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_password_reset_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE pdf_documents (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "FileName" character varying(256) NOT NULL,
        "FilePath" character varying(1024) NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "ContentType" character varying(128) NOT NULL,
        "UploadedByUserId" uuid NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        "Metadata" character varying(2048),
        "ExtractedText" text,
        "ProcessingStatus" character varying(32) NOT NULL,
        "ProcessedAt" timestamp with time zone,
        "PageCount" integer,
        "CharacterCount" integer,
        "ProcessingError" character varying(1024),
        "ExtractedTables" character varying(8192),
        "ExtractedDiagrams" character varying(8192),
        "AtomicRules" character varying(8192),
        "TableCount" integer,
        "DiagramCount" integer,
        "AtomicRuleCount" integer,
        "ProcessingProgressJson" text,
        "Language" text NOT NULL,
        search_vector text,
        CONSTRAINT "PK_pdf_documents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_pdf_documents_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_pdf_documents_users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE prompt_templates (
        "Id" uuid NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "Category" character varying(64),
        "CreatedByUserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_prompt_templates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_prompt_templates_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE rule_specs (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "Version" character varying(32) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" uuid,
        "ParentVersionId" uuid,
        "MergedFromVersionIds" character varying(1024),
        "GameEntityId" uuid,
        CONSTRAINT "PK_rule_specs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rule_specs_games_GameEntityId" FOREIGN KEY ("GameEntityId") REFERENCES games ("Id"),
        CONSTRAINT "FK_rule_specs_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_rule_specs_rule_specs_ParentVersionId" FOREIGN KEY ("ParentVersionId") REFERENCES rule_specs ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_rule_specs_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE rulespec_comments (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "Version" character varying(32) NOT NULL,
        "AtomId" uuid,
        "UserId" uuid NOT NULL,
        "CommentText" character varying(2000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "LineNumber" integer,
        "LineContext" character varying(500),
        "ParentCommentId" uuid,
        "IsResolved" boolean NOT NULL DEFAULT FALSE,
        "ResolvedByUserId" uuid,
        "ResolvedAt" timestamp with time zone,
        "MentionedUserIds" character varying(1000) NOT NULL,
        CONSTRAINT "PK_rulespec_comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rulespec_comments_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_rulespec_comments_rulespec_comments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES rulespec_comments ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_rulespec_comments_users_ResolvedByUserId" FOREIGN KEY ("ResolvedByUserId") REFERENCES users ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_rulespec_comments_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE system_configurations (
        "Id" uuid NOT NULL,
        "Key" character varying(500) NOT NULL,
        "Value" text NOT NULL,
        "ValueType" character varying(50) NOT NULL,
        "Description" character varying(1000),
        "Category" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        "RequiresRestart" boolean NOT NULL,
        "Environment" character varying(50) NOT NULL,
        "Version" integer NOT NULL,
        "PreviousValue" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "UpdatedByUserId" uuid,
        "LastToggledAt" timestamp with time zone,
        CONSTRAINT "PK_system_configurations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_system_configurations_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_system_configurations_users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE temp_sessions (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "IpAddress" character varying(64),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL DEFAULT FALSE,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_temp_sessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_temp_sessions_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE user_backup_codes (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CodeHash" character varying(255) NOT NULL,
        "IsUsed" boolean NOT NULL DEFAULT FALSE,
        "UsedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_user_backup_codes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_user_backup_codes_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE user_sessions (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "LastSeenAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "UserAgent" character varying(256),
        "IpAddress" character varying(64),
        CONSTRAINT "PK_user_sessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_user_sessions_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE chats (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "AgentId" uuid NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "LastMessageAt" timestamp with time zone,
        CONSTRAINT "PK_chats" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_chats_agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES agents ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_chats_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_chats_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE text_chunks (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "PdfDocumentId" uuid NOT NULL,
        "Content" text NOT NULL,
        "ChunkIndex" integer NOT NULL,
        "PageNumber" integer,
        "CharacterCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        search_vector text,
        CONSTRAINT "PK_text_chunks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_text_chunks_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_text_chunks_pdf_documents_PdfDocumentId" FOREIGN KEY ("PdfDocumentId") REFERENCES pdf_documents ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE vector_documents (
        "Id" uuid NOT NULL,
        "GameId" uuid NOT NULL,
        "PdfDocumentId" uuid NOT NULL,
        "ChunkCount" integer NOT NULL,
        "TotalCharacters" integer NOT NULL,
        "IndexingStatus" character varying(32) NOT NULL,
        "IndexedAt" timestamp with time zone,
        "IndexingError" text,
        "EmbeddingModel" character varying(128) NOT NULL,
        "EmbeddingDimensions" integer NOT NULL,
        "Metadata" text,
        CONSTRAINT "PK_vector_documents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_vector_documents_games_GameId" FOREIGN KEY ("GameId") REFERENCES games ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_vector_documents_pdf_documents_PdfDocumentId" FOREIGN KEY ("PdfDocumentId") REFERENCES pdf_documents ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE prompt_versions (
        "Id" uuid NOT NULL,
        "TemplateId" uuid NOT NULL,
        "VersionNumber" integer NOT NULL,
        "Content" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Metadata" character varying(4096),
        CONSTRAINT "PK_prompt_versions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_prompt_versions_prompt_templates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES prompt_templates ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_prompt_versions_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE rule_atoms (
        "Id" uuid NOT NULL,
        "RuleSpecId" uuid NOT NULL,
        "Key" character varying(32) NOT NULL,
        "Text" text NOT NULL,
        "Section" character varying(128),
        "PageNumber" integer,
        "LineNumber" integer,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_rule_atoms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rule_atoms_rule_specs_RuleSpecId" FOREIGN KEY ("RuleSpecId") REFERENCES rule_specs ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE chat_logs (
        "Id" uuid NOT NULL,
        "ChatId" uuid NOT NULL,
        "UserId" uuid,
        "Level" character varying(16) NOT NULL,
        "Message" text NOT NULL,
        "MetadataJson" character varying(2048),
        "SequenceNumber" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        "DeletedByUserId" uuid,
        "IsInvalidated" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_chat_logs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_chat_logs_chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES chats ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_chat_logs_users_DeletedByUserId" FOREIGN KEY ("DeletedByUserId") REFERENCES users ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_chat_logs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE TABLE prompt_audit_logs (
        "Id" uuid NOT NULL,
        "TemplateId" uuid NOT NULL,
        "VersionId" uuid,
        "Action" character varying(64) NOT NULL,
        "ChangedByUserId" uuid NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        "Details" character varying(2048),
        CONSTRAINT "PK_prompt_audit_logs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_prompt_audit_logs_prompt_templates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES prompt_templates ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_prompt_audit_logs_prompt_versions_VersionId" FOREIGN KEY ("VersionId") REFERENCES prompt_versions ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_prompt_audit_logs_users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agent_feedback_Endpoint" ON agent_feedback ("Endpoint");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agent_feedback_GameId" ON agent_feedback ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_agent_feedback_MessageId_UserId" ON agent_feedback ("MessageId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agent_feedback_UserId" ON agent_feedback ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agents_GameEntityId" ON agents ("GameEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agents_IsActive" ON agents ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agents_LastInvokedAt" ON agents ("LastInvokedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_agents_Name" ON agents ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_agents_Type" ON agents ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ai_request_logs_CreatedAt" ON ai_request_logs ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ai_request_logs_Endpoint" ON ai_request_logs ("Endpoint");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ai_request_logs_GameId" ON ai_request_logs ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ai_request_logs_UserId" ON ai_request_logs ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_alerts_alert_type_triggered_at" ON alerts (alert_type, triggered_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_alerts_is_active" ON alerts (is_active) WHERE is_active = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_api_keys_IsActive_ExpiresAt" ON api_keys ("IsActive", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_api_keys_KeyHash" ON api_keys ("KeyHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_api_keys_RevokedBy" ON api_keys ("RevokedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_api_keys_UserId" ON api_keys ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_CreatedAt" ON audit_logs ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_UserId" ON audit_logs ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_cache_stats_game_id" ON cache_stats (game_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_cache_stats_question_hash" ON cache_stats (question_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_chat_logs_chat_id_sequence_role ON chat_logs ("ChatId", "SequenceNumber", "Level");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_chat_logs_deleted_at ON chat_logs ("DeletedAt") WHERE "DeletedAt" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_chat_logs_user_id ON chat_logs ("UserId") WHERE "UserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_chat_logs_ChatId_CreatedAt" ON chat_logs ("ChatId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_chat_logs_DeletedByUserId" ON chat_logs ("DeletedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_chats_AgentId" ON chats ("AgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_chats_GameId_StartedAt" ON chats ("GameId", "StartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_chats_UserId_LastMessageAt" ON chats ("UserId", "LastMessageAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ChatThreads_GameId" ON "ChatThreads" ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_ChatThreads_UserId" ON "ChatThreads" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_games_Name" ON games ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_GameSessions_GameId" ON "GameSessions" ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_GameSessions_StartedAt" ON "GameSessions" ("StartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_GameSessions_Status_StartedAt" ON "GameSessions" ("Status", "StartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX ix_llm_cost_logs_created_at ON llm_cost_logs (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX ix_llm_cost_logs_provider_date ON llm_cost_logs (provider, request_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX ix_llm_cost_logs_request_date ON llm_cost_logs (request_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX ix_llm_cost_logs_role_date ON llm_cost_logs (user_role, request_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX ix_llm_cost_logs_user_id ON llm_cost_logs (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_n8n_configs_CreatedByUserId" ON n8n_configs ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_n8n_configs_Name" ON n8n_configs ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_oauth_accounts_Provider" ON oauth_accounts ("Provider");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_oauth_accounts_Provider_ProviderUserId" ON oauth_accounts ("Provider", "ProviderUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_oauth_accounts_UserId" ON oauth_accounts ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_password_reset_tokens_ExpiresAt" ON password_reset_tokens ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_password_reset_tokens_TokenHash" ON password_reset_tokens ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_password_reset_tokens_UserId" ON password_reset_tokens ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_pdf_documents_GameId_UploadedAt" ON pdf_documents ("GameId", "UploadedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_pdf_documents_UploadedByUserId" ON pdf_documents ("UploadedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_audit_logs_Action" ON prompt_audit_logs ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_audit_logs_ChangedAt" ON prompt_audit_logs ("ChangedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_audit_logs_ChangedByUserId" ON prompt_audit_logs ("ChangedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_audit_logs_TemplateId" ON prompt_audit_logs ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_audit_logs_VersionId" ON prompt_audit_logs ("VersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_evaluation_results_executed_at" ON prompt_evaluation_results (executed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_evaluation_results_template_id" ON prompt_evaluation_results (template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_evaluation_results_template_id_version_id_executed_at" ON prompt_evaluation_results (template_id, version_id, executed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_evaluation_results_version_id" ON prompt_evaluation_results (version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_templates_Category" ON prompt_templates ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_templates_CreatedAt" ON prompt_templates ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_templates_CreatedByUserId" ON prompt_templates ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_prompt_templates_Name" ON prompt_templates ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_versions_CreatedAt" ON prompt_versions ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_versions_CreatedByUserId" ON prompt_versions ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_prompt_versions_TemplateId_IsActive" ON prompt_versions ("TemplateId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_prompt_versions_TemplateId_VersionNumber" ON prompt_versions ("TemplateId", "VersionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rule_atoms_RuleSpecId_SortOrder" ON rule_atoms ("RuleSpecId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rule_specs_CreatedByUserId" ON rule_specs ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rule_specs_GameEntityId" ON rule_specs ("GameEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rule_specs_GameId_Version" ON rule_specs ("GameId", "Version");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rule_specs_ParentVersionId" ON rule_specs ("ParentVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_rulespec_comments_game_version_line ON rulespec_comments ("GameId", "Version", "LineNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_rulespec_comments_is_resolved ON rulespec_comments ("IsResolved");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_rulespec_comments_parent_id ON rulespec_comments ("ParentCommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX idx_rulespec_comments_user_id ON rulespec_comments ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rulespec_comments_AtomId" ON rulespec_comments ("AtomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rulespec_comments_GameId_Version" ON rulespec_comments ("GameId", "Version");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_rulespec_comments_ResolvedByUserId" ON rulespec_comments ("ResolvedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_Category" ON system_configurations ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_CreatedByUserId" ON system_configurations ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_Environment" ON system_configurations ("Environment");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_IsActive" ON system_configurations ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_system_configurations_Key_Environment" ON system_configurations ("Key", "Environment");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_UpdatedAt" ON system_configurations ("UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_system_configurations_UpdatedByUserId" ON system_configurations ("UpdatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_temp_sessions_ExpiresAt" ON temp_sessions ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_temp_sessions_TokenHash" ON temp_sessions ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_temp_sessions_UserId" ON temp_sessions ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_text_chunks_ChunkIndex" ON text_chunks ("ChunkIndex");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_text_chunks_GameId" ON text_chunks ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_text_chunks_PageNumber" ON text_chunks ("PageNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_text_chunks_PdfDocumentId" ON text_chunks ("PdfDocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_backup_codes_CodeHash" ON user_backup_codes ("CodeHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_user_backup_codes_UserId" ON user_backup_codes ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_user_backup_codes_UserId_IsUsed" ON user_backup_codes ("UserId", "IsUsed") WHERE "IsUsed" = FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_sessions_TokenHash" ON user_sessions ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_user_sessions_UserId" ON user_sessions ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_vector_documents_GameId" ON vector_documents ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_vector_documents_PdfDocumentId" ON vector_documents ("PdfDocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_workflow_error_logs_created_at" ON workflow_error_logs (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_workflow_error_logs_execution_id" ON workflow_error_logs (execution_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    CREATE INDEX "IX_workflow_error_logs_workflow_id" ON workflow_error_logs (workflow_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251114174048_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251114174048_InitialCreate', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117142947_AddPromptVersionActivationFields') THEN
    ALTER TABLE prompt_versions ADD "ActivatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117142947_AddPromptVersionActivationFields') THEN
    ALTER TABLE prompt_versions ADD "ActivatedByUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117142947_AddPromptVersionActivationFields') THEN
    ALTER TABLE prompt_versions ADD "ActivationReason" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117142947_AddPromptVersionActivationFields') THEN
    ALTER TABLE prompt_versions ADD "ChangeNotes" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117142947_AddPromptVersionActivationFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251117142947_AddPromptVersionActivationFields', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE TABLE validation_accuracy_baselines (
        id uuid NOT NULL,
        context character varying(200) NOT NULL,
        dataset_id character varying(100) NOT NULL,
        evaluation_id uuid,
        measured_at timestamp with time zone NOT NULL,
        true_positives integer NOT NULL,
        true_negatives integer NOT NULL,
        false_positives integer NOT NULL,
        false_negatives integer NOT NULL,
        total_cases integer NOT NULL,
        precision double precision NOT NULL,
        recall double precision NOT NULL,
        f1_score double precision NOT NULL,
        accuracy double precision NOT NULL,
        specificity double precision NOT NULL,
        matthews_correlation double precision NOT NULL,
        meets_baseline boolean NOT NULL,
        quality_level integer NOT NULL,
        summary character varying(500),
        recommendations_json jsonb,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT pk_validation_accuracy_baselines PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_context ON validation_accuracy_baselines (context);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_dataset_id ON validation_accuracy_baselines (dataset_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_measured_at ON validation_accuracy_baselines (measured_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_accuracy ON validation_accuracy_baselines (accuracy);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_meets_baseline ON validation_accuracy_baselines (meets_baseline);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    CREATE INDEX ix_validation_accuracy_baselines_evaluation_id ON validation_accuracy_baselines (evaluation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results DROP COLUMN hallucination_rate;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results DROP COLUMN avg_confidence;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results DROP COLUMN citation_correctness;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results DROP COLUMN avg_latency_ms;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results ADD relevance double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results ADD completeness double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results ADD clarity double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    ALTER TABLE prompt_evaluation_results ADD citation_quality double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182605_AddValidationBaselineAndUpdate5MetricFramework') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251118182605_AddValidationBaselineAndUpdate5MetricFramework', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182740_RemoveAgentGameIdAndKind') THEN
    ALTER TABLE agents DROP COLUMN "GameId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182740_RemoveAgentGameIdAndKind') THEN
    ALTER TABLE agents DROP COLUMN "Kind";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118182740_RemoveAgentGameIdAndKind') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251118182740_RemoveAgentGameIdAndKind', '9.0.11');
    END IF;
END $EF$;
COMMIT;

