using Api.Infrastructure.Entities.SessionTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.BoundedContexts.SessionTracking.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity configuration for PlayerNoteEntity (persistence).
/// </summary>
public class PlayerNoteConfiguration : IEntityTypeConfiguration<PlayerNoteEntity>
{
    public void Configure(EntityTypeBuilder<PlayerNoteEntity> builder)
    {
        builder.ToTable("session_tracking_notes");

        builder.HasKey(n => n.Id);

        builder.Property(n => n.Id)
            .HasColumnName("id")
            .ValueGeneratedNever(); // Generated by domain

        builder.Property(n => n.SessionId)
            .HasColumnName("session_id")
            .IsRequired();

        builder.Property(n => n.ParticipantId)
            .HasColumnName("participant_id")
            .IsRequired();

        builder.Property(n => n.NoteType)
            .HasColumnName("note_type")
            .HasMaxLength(20)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(n => n.TemplateKey)
            .HasColumnName("template_key")
            .HasMaxLength(50);

        builder.Property(n => n.Content)
            .HasColumnName("content")
            .HasColumnType("text")
            .IsRequired();

        builder.Property(n => n.IsHidden)
            .HasColumnName("is_hidden")
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(n => n.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.Property(n => n.UpdatedAt)
            .HasColumnName("updated_at");

        // Index for participant notes lookup
        builder.HasIndex(n => new { n.SessionId, n.ParticipantId })
            .HasDatabaseName("idx_notes_session_participant");

        // Foreign key to session (cascade delete)
        builder.HasOne(n => n.Session)
            .WithMany()
            .HasForeignKey(n => n.SessionId)
            .OnDelete(DeleteBehavior.Cascade);

        // Foreign key to participant (cascade delete)
        builder.HasOne(n => n.Participant)
            .WithMany()
            .HasForeignKey(n => n.ParticipantId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}