using Api.Infrastructure.Entities.SessionTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.BoundedContexts.SessionTracking.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity configuration for ScoreEntryEntity (persistence).
/// </summary>
public class ScoreEntryConfiguration : IEntityTypeConfiguration<ScoreEntryEntity>
{
    public void Configure(EntityTypeBuilder<ScoreEntryEntity> builder)
    {
        builder.ToTable("session_tracking_score_entries");

        builder.HasKey(s => s.Id);

        builder.Property(s => s.Id)
            .HasColumnName("id")
            .ValueGeneratedNever(); // Generated by domain

        builder.Property(s => s.SessionId)
            .HasColumnName("session_id")
            .IsRequired();

        builder.Property(s => s.ParticipantId)
            .HasColumnName("participant_id")
            .IsRequired();

        builder.Property(s => s.RoundNumber)
            .HasColumnName("round_number");

        builder.Property(s => s.Category)
            .HasColumnName("category")
            .HasMaxLength(50);

        builder.Property(s => s.ScoreValue)
            .HasColumnName("score_value")
            .HasPrecision(10, 2) // DECIMAL(10,2)
            .IsRequired();

        builder.Property(s => s.Timestamp)
            .HasColumnName("timestamp")
            .IsRequired();

        builder.Property(s => s.CreatedBy)
            .HasColumnName("created_by")
            .IsRequired();

        // Index for session + participant queries
        builder.HasIndex(s => new { s.SessionId, s.ParticipantId })
            .HasDatabaseName("idx_scores_session_participant");

        // Index for round-based queries
        builder.HasIndex(s => new { s.SessionId, s.RoundNumber })
            .HasDatabaseName("idx_scores_round");

        // Foreign key to session (cascade delete)
        builder.HasOne(s => s.Session)
            .WithMany()
            .HasForeignKey(s => s.SessionId)
            .OnDelete(DeleteBehavior.Cascade);

        // Foreign key to participant (cascade delete)
        builder.HasOne(s => s.Participant)
            .WithMany()
            .HasForeignKey(s => s.ParticipantId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}