using Api.Infrastructure.Entities;
using Api.Infrastructure.Entities.SessionTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.BoundedContexts.SessionTracking.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity configuration for SessionEntity (persistence).
/// </summary>
public class SessionConfiguration : IEntityTypeConfiguration<SessionEntity>
{
    public void Configure(EntityTypeBuilder<SessionEntity> builder)
    {
        builder.ToTable("session_tracking_sessions");

        builder.HasKey(s => s.Id);

        builder.Property(s => s.Id)
            .HasColumnName("id")
            .ValueGeneratedNever(); // Generated by domain

        builder.Property(s => s.UserId)
            .HasColumnName("user_id")
            .IsRequired();

        builder.Property(s => s.GameId)
            .HasColumnName("game_id")
            .IsRequired();

        // #2632 SI-1: optional link to the libro-game campaign (GameNight-attached play).
        // Logical FK to gamebook_campaign_sessions; no hard DB constraint (cross-aggregate,
        // nullable) — the invariant is enforced in the attach command.
        builder.Property(s => s.GamebookCampaignId)
            .HasColumnName("gamebook_campaign_id");

        builder.Property(s => s.SessionCode)
            .HasColumnName("session_code")
            .HasMaxLength(6)
            .IsRequired();

        builder.Property(s => s.SessionType)
            .HasColumnName("session_type")
            .HasMaxLength(20)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(s => s.Status)
            .HasColumnName("status")
            .HasMaxLength(20)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(s => s.SessionDate)
            .HasColumnName("session_date")
            .IsRequired();

        builder.Property(s => s.Location)
            .HasColumnName("location")
            .HasMaxLength(100);

        builder.Property(s => s.FinalizedAt)
            .HasColumnName("finalized_at");

        // Asse A semantic alignment #1896 (T2): Session.StartedAt — when the session
        // transitioned to live mode via OpenLiveMode(). Invariante #11.
        builder.Property(s => s.StartedAt)
            .HasColumnName("started_at");

        // Asse A semantic alignment #1896 (T9, DEC-1): Session.ScoringType — polymorphic
        // scoring type string ("Points" | "BinaryWin" | "Objectives" | "Ranking").
        // Defaults to "Points" (covers ~50% catalog board games).
        builder.Property(s => s.ScoringType)
            .HasColumnName("scoring_type")
            .HasMaxLength(20)
            .HasDefaultValue("Points")
            .IsRequired();

        // Asse A semantic alignment #1896 (T9, DEC-1): Session.ScoreData — polymorphic
        // score data as JSONB. Shape varies by ScoringType. Default '{}'.
        builder.Property(s => s.ScoreData)
            .HasColumnName("score_data")
            .HasColumnType("jsonb")
            .HasDefaultValueSql("'{}'::jsonb")
            .IsRequired();

        builder.Property(s => s.IsDeleted)
            .HasColumnName("is_deleted")
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(s => s.DeletedAt)
            .HasColumnName("deleted_at");

        builder.Property(s => s.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.Property(s => s.UpdatedAt)
            .HasColumnName("updated_at");

        builder.Property(s => s.CreatedBy)
            .HasColumnName("created_by")
            .IsRequired();

        builder.Property(s => s.UpdatedBy)
            .HasColumnName("updated_by");

        builder.Property<byte[]>("RowVersion")
            .HasColumnName("row_version")
            .IsRowVersion()
            .IsConcurrencyToken();

        // Session Flow v2.1: Turn order fields
        builder.Property(s => s.TurnOrderJson)
            .HasColumnName("turn_order_json")
            .HasColumnType("jsonb");

        builder.Property(s => s.TurnOrderMethod)
            .HasColumnName("turn_order_method")
            .HasMaxLength(16);

        builder.Property(s => s.TurnOrderSeed)
            .HasColumnName("turn_order_seed");

        builder.Property(s => s.CurrentTurnIndex)
            .HasColumnName("current_turn_index");

        // Unique constraint on session code (excluding soft deleted)
        builder.HasIndex(s => s.SessionCode)
            .HasDatabaseName("idx_sessions_code")
            .IsUnique()
            .HasFilter("is_deleted = false");

        // Index for filtering by user and status
        builder.HasIndex(s => new { s.UserId, s.Status })
            .HasDatabaseName("idx_sessions_user_status")
            .HasFilter("is_deleted = false");

        // Index for game play history
        builder.HasIndex(s => new { s.GameId, s.SessionDate })
            .HasDatabaseName("idx_sessions_game_date")
            .IsDescending(false, true) // DESC on SessionDate
            .HasFilter("is_deleted = false");

        // #2632 SI-1: resolve a campaign's GameNight-attached sittings (the spine read path).
        builder.HasIndex(s => s.GamebookCampaignId)
            .HasDatabaseName("idx_sessions_gamebook_campaign")
            .HasFilter("gamebook_campaign_id IS NOT NULL");

        // Relationship: Session has many Participants
        builder.HasMany(s => s.Participants)
            .WithOne(p => p.Session)
            .HasForeignKey(p => p.SessionId)
            .OnDelete(DeleteBehavior.Cascade);

        // Global query filter for soft delete
        builder.HasQueryFilter(s => !s.IsDeleted);

        // Foreign key to users table
        builder.HasOne<UserEntity>()
            .WithMany()
            .HasForeignKey(s => s.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // FK to shared_games (post-Phase2d: legacy games table dropped, GameId now references shared_games.id)
        builder.HasOne<Api.Infrastructure.Entities.SharedGameCatalog.SharedGameEntity>()
            .WithMany()
            .HasForeignKey(s => s.GameId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}