using Api.Infrastructure.Entities;
using Api.Infrastructure.Entities.SessionTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.BoundedContexts.SessionTracking.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity configuration for SessionEntity (persistence).
/// </summary>
public class SessionConfiguration : IEntityTypeConfiguration<SessionEntity>
{
    public void Configure(EntityTypeBuilder<SessionEntity> builder)
    {
        builder.ToTable("session_tracking_sessions");

        builder.HasKey(s => s.Id);

        builder.Property(s => s.Id)
            .HasColumnName("id")
            .ValueGeneratedNever(); // Generated by domain

        builder.Property(s => s.UserId)
            .HasColumnName("user_id")
            .IsRequired();

        builder.Property(s => s.GameId)
            .HasColumnName("game_id")
            .IsRequired();

        builder.Property(s => s.SessionCode)
            .HasColumnName("session_code")
            .HasMaxLength(6)
            .IsRequired();

        builder.Property(s => s.SessionType)
            .HasColumnName("session_type")
            .HasMaxLength(20)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(s => s.Status)
            .HasColumnName("status")
            .HasMaxLength(20)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(s => s.SessionDate)
            .HasColumnName("session_date")
            .IsRequired();

        builder.Property(s => s.Location)
            .HasColumnName("location")
            .HasMaxLength(100);

        builder.Property(s => s.FinalizedAt)
            .HasColumnName("finalized_at");

        builder.Property(s => s.IsDeleted)
            .HasColumnName("is_deleted")
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(s => s.DeletedAt)
            .HasColumnName("deleted_at");

        builder.Property(s => s.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.Property(s => s.UpdatedAt)
            .HasColumnName("updated_at");

        builder.Property(s => s.CreatedBy)
            .HasColumnName("created_by")
            .IsRequired();

        builder.Property(s => s.UpdatedBy)
            .HasColumnName("updated_by");

        builder.Property<byte[]>("RowVersion")
            .HasColumnName("row_version")
            .IsRowVersion()
            .IsConcurrencyToken();

        // Unique constraint on session code (excluding soft deleted)
        builder.HasIndex(s => s.SessionCode)
            .HasDatabaseName("idx_sessions_code")
            .IsUnique()
            .HasFilter("is_deleted = false");

        // Index for filtering by user and status
        builder.HasIndex(s => new { s.UserId, s.Status })
            .HasDatabaseName("idx_sessions_user_status")
            .HasFilter("is_deleted = false");

        // Index for game play history
        builder.HasIndex(s => new { s.GameId, s.SessionDate })
            .HasDatabaseName("idx_sessions_game_date")
            .IsDescending(false, true) // DESC on SessionDate
            .HasFilter("is_deleted = false");

        // Relationship: Session has many Participants
        builder.HasMany(s => s.Participants)
            .WithOne(p => p.Session)
            .HasForeignKey(p => p.SessionId)
            .OnDelete(DeleteBehavior.Cascade);

        // Global query filter for soft delete
        builder.HasQueryFilter(s => !s.IsDeleted);

        // Foreign key to users table
        builder.HasOne<UserEntity>()
            .WithMany()
            .HasForeignKey(s => s.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Foreign key to games table (nullable)
        builder.HasOne<GameEntity>()
            .WithMany()
            .HasForeignKey(s => s.GameId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}