using Api.BoundedContexts.GameManagement.Application.Commands.SessionSnapshot;
using Api.BoundedContexts.GameManagement.Application.DTOs.SessionSnapshot;
using Api.BoundedContexts.GameManagement.Application.EventHandlers;
using Api.BoundedContexts.GameManagement.Domain.Entities;
using Api.BoundedContexts.GameManagement.Domain.Entities.SessionSnapshot;
using Api.BoundedContexts.GameManagement.Domain.Enums;
using Api.BoundedContexts.GameManagement.Domain.Events;
using Api.BoundedContexts.GameManagement.Domain.Repositories;
using Api.SharedKernel.Infrastructure.Persistence;
using Api.Tests.Constants;
using MediatR;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Time.Testing;
using Moq;
using Xunit;

namespace Api.Tests.BoundedContexts.GameManagement.Application.EventHandlers;

/// <summary>
/// Tests for SessionPausedAutoSnapshotHandler.
/// Issue #5581: Auto-snapshot on Pause + snapshot history.
/// </summary>
[Trait("Category", TestCategories.Unit)]
[Trait("BoundedContext", "GameManagement")]
public class SessionPausedAutoSnapshotHandlerTests
{
    private readonly Mock<ILiveSessionRepository> _sessionRepositoryMock;
    private readonly Mock<ISessionSnapshotRepository> _snapshotRepositoryMock;
    private readonly Mock<IMediator> _mediatorMock;
    private readonly Mock<IUnitOfWork> _unitOfWorkMock;
    private readonly Mock<ILogger<SessionPausedAutoSnapshotHandler>> _loggerMock;
    private readonly FakeTimeProvider _timeProvider;

    public SessionPausedAutoSnapshotHandlerTests()
    {
        _sessionRepositoryMock = new Mock<ILiveSessionRepository>();
        _snapshotRepositoryMock = new Mock<ISessionSnapshotRepository>();
        _mediatorMock = new Mock<IMediator>();
        _unitOfWorkMock = new Mock<IUnitOfWork>();
        _loggerMock = new Mock<ILogger<SessionPausedAutoSnapshotHandler>>();
        _timeProvider = new FakeTimeProvider(new DateTimeOffset(2026, 3, 9, 10, 0, 0, TimeSpan.Zero));
    }

    private SessionPausedAutoSnapshotHandler CreateHandler() =>
        new(_sessionRepositoryMock.Object,
            _snapshotRepositoryMock.Object,
            _mediatorMock.Object,
            _unitOfWorkMock.Object,
            _loggerMock.Object);

    private LiveGameSession CreatePausedSession(Guid? sessionId = null)
    {
        var id = sessionId ?? Guid.NewGuid();
        var session = LiveGameSession.Create(id, Guid.NewGuid(), "Test Game", _timeProvider);
        session.AddPlayer(Guid.NewGuid(), "Player 1", PlayerColor.Red, _timeProvider);
        session.Start(_timeProvider);
        session.Pause(_timeProvider);
        return session;
    }

    private static SessionSnapshotDto CreateMockSnapshotDto(Guid sessionId) =>
        new(Guid.NewGuid(), sessionId, 0, SnapshotTrigger.SessionPaused,
            "Auto \u2014 Pausa turno 1", true, 1, 0, DateTime.UtcNow, null);

    [Fact]
    public async Task Handle_SessionPaused_CreatesAutoSnapshot()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;
        var expectedDto = CreateMockSnapshotDto(sessionId);

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedDto);
        _snapshotRepositoryMock.Setup(r => r.CountAutoGeneratedBySessionIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var handler = CreateHandler();
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);

        _mediatorMock.Verify(m => m.Send(
            It.Is<CreateSnapshotCommand>(c =>
                c.SessionId == sessionId &&
                c.TriggerType == SnapshotTrigger.SessionPaused &&
                c.TriggerDescription!.StartsWith("Auto \u2014 Pausa turno", StringComparison.Ordinal)),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_SnapshotLabelContainsTurnNumber()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(CreateMockSnapshotDto(sessionId));
        _snapshotRepositoryMock.Setup(r => r.CountAutoGeneratedBySessionIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var handler = CreateHandler();
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);

        _mediatorMock.Verify(m => m.Send(
            It.Is<CreateSnapshotCommand>(c =>
                c.TriggerDescription == $"Auto \u2014 Pausa turno {session.CurrentTurnIndex}"),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_SessionNotFound_DoesNotThrow()
    {
        var sessionId = Guid.NewGuid();
        var now = DateTime.UtcNow;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync((LiveGameSession?)null);

        var handler = CreateHandler();

        // Should not throw — just log warning
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);

        _mediatorMock.Verify(m => m.Send(
            It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Handle_ExceedsMaxAutoSnapshots_CleansUpOldest()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(CreateMockSnapshotDto(sessionId));
        _snapshotRepositoryMock.Setup(r => r.CountAutoGeneratedBySessionIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(21); // Exceeds max of 20

        var handler = CreateHandler();
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);

        _snapshotRepositoryMock.Verify(r => r.DeleteOldestAutoGeneratedAsync(
            sessionId, 20, It.IsAny<CancellationToken>()), Times.Once);
        _unitOfWorkMock.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithinMaxAutoSnapshots_DoesNotCleanup()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(CreateMockSnapshotDto(sessionId));
        _snapshotRepositoryMock.Setup(r => r.CountAutoGeneratedBySessionIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(15); // Under max of 20

        var handler = CreateHandler();
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);

        _snapshotRepositoryMock.Verify(r => r.DeleteOldestAutoGeneratedAsync(
            It.IsAny<Guid>(), It.IsAny<int>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Handle_SnapshotCreationFails_DoesNotThrow()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new InvalidOperationException("Snapshot creation failed"));

        var handler = CreateHandler();

        // Should not throw — exception is caught and logged
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Handle_PropagatesCancellationToken()
    {
        var sessionId = Guid.NewGuid();
        var session = CreatePausedSession(sessionId);
        var now = _timeProvider.GetUtcNow().UtcDateTime;
        var ct = TestContext.Current.CancellationToken;

        _sessionRepositoryMock.Setup(r => r.GetByIdAsync(sessionId, ct))
            .ReturnsAsync(session);
        _mediatorMock.Setup(m => m.Send(It.IsAny<CreateSnapshotCommand>(), ct))
            .ReturnsAsync(CreateMockSnapshotDto(sessionId));
        _snapshotRepositoryMock.Setup(r => r.CountAutoGeneratedBySessionIdAsync(sessionId, ct))
            .ReturnsAsync(1);

        var handler = CreateHandler();
        await handler.Handle(new LiveSessionPausedEvent(sessionId, now), ct);

        _sessionRepositoryMock.Verify(r => r.GetByIdAsync(sessionId, ct), Times.Once);
    }
}
