using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RestoreSearchVectorColumns : Migration
    {
        // #2875 follow-up: the consolidated Initial baseline was generated by
        // `ef migrations add`, which only reflects the EF model and therefore DROPPED
        // the raw-SQL DDL that earlier migrations (AddSearchVectorColumns,
        // AlignSearchVectorToEnglishFtsConfig) had applied via migrationBuilder.Sql():
        // three GENERATED-ALWAYS tsvector `search_vector` columns + their GIN indexes.
        // These are not model-tracked, so `has-pending-model-changes` did not flag the
        // gap; the loss surfaced as `42703: column "search_vector" does not exist`
        // failures in the PDF processing pipeline. Restore them verbatim from the
        // pre-consolidation schema (table/column mapping verified via information_schema).
        // IF NOT EXISTS makes this idempotent so it is a no-op on any environment that
        // still has the columns from the pre-consolidation migration chain.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE public.pdf_documents
                    ADD COLUMN IF NOT EXISTS search_vector tsvector
                    GENERATED ALWAYS AS (to_tsvector('english'::regconfig, COALESCE(""ExtractedText"", ''::text))) STORED;");

            migrationBuilder.Sql(@"
                ALTER TABLE public.pgvector_embeddings
                    ADD COLUMN IF NOT EXISTS search_vector tsvector
                    GENERATED ALWAYS AS (to_tsvector('english'::regconfig, text_content)) STORED;");

            migrationBuilder.Sql(@"
                ALTER TABLE public.text_chunks
                    ADD COLUMN IF NOT EXISTS search_vector tsvector
                    GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ""Content"")) STORED;");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS idx_pdf_documents_search_vector ON public.pdf_documents USING gin (search_vector);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS idx_pgvector_embeddings_search_vector ON public.pgvector_embeddings USING gin (search_vector);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS idx_text_chunks_search_vector ON public.text_chunks USING gin (search_vector);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS public.idx_text_chunks_search_vector;");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS public.idx_pgvector_embeddings_search_vector;");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS public.idx_pdf_documents_search_vector;");
            migrationBuilder.Sql(@"ALTER TABLE public.text_chunks DROP COLUMN IF EXISTS search_vector;");
            migrationBuilder.Sql(@"ALTER TABLE public.pgvector_embeddings DROP COLUMN IF EXISTS search_vector;");
            migrationBuilder.Sql(@"ALTER TABLE public.pdf_documents DROP COLUMN IF EXISTS search_vector;");
        }
    }
}
