/**
 * @mockup admin-mockups/design_files/onboarding.html
 *
 * MOCKUP-ANNOTATION marker — do not edit by hand.
 * Regenerated by: pnpm mockup-annotations:inject
 * Audit:          pnpm mockup-annotations:audit
 *
 * Ref: DS-17-1 #2069, umbrella #2063.
 */
/**
 * Welcome Page - Post-Registration Landing
 *
 * Displays a welcome message after successful registration,
 * then automatically redirects to dashboard after 2 seconds.
 */

import { Suspense } from 'react';

import { WelcomeFallback, WelcomeContent } from './_content';

export default function WelcomePage() {
  return (
    <Suspense fallback={<WelcomeFallback />}>
      <WelcomeContent />
    </Suspense>
  );
}
